### ISSUE TITLE
Q: /info endpoint based on processed image

### ISSUE THREAD

**Issue by perosb** [imgproxy/imgproxy#1001]
Hi,

The Pro feature `/info`, doesn't that take all the processing options into consideration? Or is it simply returning the info about the original image.

If the latter, would a `info` option that returns metadata about the resulting image to possible? Of course in the this case the complete image need to be downloaded and processed before knowing the result.

**Comment by DarthSim** [comment]
Hey @perosb!
You can just use the processed image URL as a source URL for `/info`.
