### ISSUE TITLE
Resizing paletted PNG to PNG returns non-sensical result

### ISSUE THREAD

**Issue by DrPhil** [imgproxy/imgproxy#1013]
I have a PNG image with a palette (aka "indexed"?) that imgproxy returns gibberish for. The exact result depends on what size and fit I resize to, but none of them looks anything like the original image, usually I just get fully colored squares.

It needs to be both to PNG *and* the original PNG should be in the "indexed"/palette format to reproduce. 

The PNG with palette
![fairtrade](https://user-images.githubusercontent.com/184889/196483741-996d8aa3-be1d-4582-b4d7-e6675f8ebf0c.png)

The result after imgproxy
![196483741-996d8aa3-be1d-4582-b4d7-e6675f8ebf0c](https://user-images.githubusercontent.com/184889/196484208-3183abb0-5139-4cc0-9591-0705c1e9960c.png)

My settings:
![Screenshot_2022-10-18_18-07-07](https://user-images.githubusercontent.com/184889/196484405-127c6901-8df4-4eaa-8d39-db8749cb4b3e.png)

I tested locally with `docker run -p 8080:8080 -it darthsim/imgproxy` and `docker run -p 8080:8080 -it darthsim/imgproxy:v3.8.0` and could reproduce on both. It was working for version `docker run -p 8080:8080 -it darthsim/imgproxy:v3.7.2`, so this is a recent regression!

**Comment by DrPhil** [comment]
I just want to clarify that this is not limited to just this png, but happens with other indexed pngs as well. For example:  https://upload.wikimedia.org/wikipedia/commons/e/e1/Screen_color_test_Amiga_4colors.png has the same issue.

**Comment by DarthSim** [comment]
Hey @DrPhil!

Thanks for the report! I patched libvips right in the `v3.9.0` Docker image.

**Comment by DrPhil** [comment]
Well done! I've been able to test both locally and in production. This issue is resolved. :smiley: Thanks for great debugging and a speedy resolution. Well done!
