### ISSUE TITLE
OpenTelemetry headers and attributes

### ISSUE THREAD

**Issue by jjhuff** [imgproxy/imgproxy#1026]
I'm super excited for the OTel support. Two things that'd be awesome to add:
1. Configurable headers. We use honeycomb, so if we could specify the header, we could avoid needing the collector.
2. Custom service attributes. We attach things like `environment`, `branch`, `pr`

Thanks!

**Comment by DarthSim** [comment]
Hi @jjhuff!

You can use OTel SDK-provided environment variables for this:

```
OTEL_RESOURCE_ATTRIBUTES="attr1=value1,attr2=value2"
OTEL_EXPORTER_OTLP_HEADERS="header1=value1,header2=value2"
```

**Comment by jjhuff** [comment]
Oh, sweet. I didn't realize those worked. Working great!
