### ISSUE TITLE
Prometheus: Support Remote_Write for metrics

### ISSUE THREAD

**Issue by shakalandy** [imgproxy/imgproxy#1038]
For scenarios where external scraping is not possible, it would be neat to support prometheus `remote_write` feature in addition to the existing scraping.

With remote write applications push their metrics instead of being pulled - would it be possible to implement it for future releases?

Documentation: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write

Older go library for pushing metrics: https://github.com/m3dbx/prometheus_remote_client_golang

**Comment by DarthSim** [comment]
Hey @shakalandy!

As far as I understand, remote write is not used for this. I guess [Pushgateway](https://prometheus.io/docs/practices/pushing/) is what you're looking for. Yet it has its downsides, and I'd recommend using an OpenTelemetry collector with Prometheus exporter instead.

**Comment by shakalandy** [comment]
Ok thanks @DarthSim - we wanted to tackle a use-case, where we can't extend the provided docker-image, and also can't scrape the existing metrics. 
We'll have to look for other solutions than.

Thanks for your help, closing this one.
