### ISSUE TITLE
Force power of 2? 

### ISSUE THREAD

**Issue by antoinemacia** [imgproxy/imgproxy#1039]
Hello!

I'm wondering if imgproxy is able to to transform images to power of 2 through the resize function? 

I'm using imgproxy for modifying textures of 3D assets in an WebGL application which doesn't really like non-power of 2 textures and ends up doing the processing on the client (so they can be mipmapped I believe); Pre-processing server side would be ideal!

**Comment by DarthSim** [comment]
Unfortunately, imgproxy doesn't have such a feature. as its usage area is pretty small. Actually, I can't think of any use case for this feature rather than yours :(
