### ISSUE TITLE
How do I enable signature support expiration time?

### ISSUE THREAD

**Issue by MunMunMiao** [imgproxy/imgproxy#1045]

**Comment by DarthSim** [comment]
Hey @MunMunMiao!
The [expires](https://docs.imgproxy.net/generating_the_url?id=expires) option is probably what you're looking for.

**Comment by MunMunMiao** [comment]
> Hey @MunMunMiao!
> 
> The [expires](https://docs.imgproxy.net/generating_the_url?id=expires) option is probably what you're looking for.

nice, thanks you😀
