### ISSUE TITLE
Invalid control character in source url

### ISSUE THREAD

**Issue by visioncode** [imgproxy/imgproxy#1053]
I'm not able to use image urls like the following:

https://example.com/files/uploads?path=1234/profile.jpg

I already tried to urlencode, base64 encode, but nothing gonna happen. It always results in:

"Source image is unreachable" or "invalid control character in URL". I guess the ? and/or slash in the path is the reason for this error. All other urls are working fine. When I add ?lorem=ipsum add another working image, it is also not possible.

This is my current function:
```
function proxyImg($url)
{
$url = urlencode($url); // does not work with or without ...
    $key = 'xxx';
    $salt = 'yyy';

    $keyBin = pack("H*" , $key);
    if(empty($keyBin)) {
        die('Key expected to be hex-encoded string');
    }

    $saltBin = pack("H*" , $salt);
    if(empty($saltBin)) {
        die('Salt expected to be hex-encoded string');
    }
    $path = "/".base64_encode($url);

    $signature = rtrim(strtr(base64_encode(hash_hmac('sha256', $saltBin.$path, $keyBin, true)), '+/', '-_'), '=');

    return 'https://img.example.com'.sprintf("/%s%s", $signature, $path);
}
```

any ideas?

**Comment by DarthSim** [comment]
Hey @visioncode!
Could you show me the generated URL? You can omit the host part.

**Comment by visioncode** [comment]
@DarthSim 

here we go: https://imgproxy.example.com/ZtxCmMlKR8HLbMg4Xx5latM3s5Kf4nHAeIbmRGjZlPo/aHR0cHMlM0ElMkYlMkZwb3J0YWwuZmxlZXQtZXZlbnRzLmRlJTJGZGUlMkZmaWxlcyUzRnBhdGglM0Rsb2dvcyUyRmJhYmluaS5qcGc=

```
$key = '2b73b2f91ae1c00e880e061cb18b5445c3758be7092238f777c0aa31bc15eeae';
$salt = 'c78c093521373895f4cddfa36aa4c7747fbf0995037fec8406bc111ed805e9b8';
```

**Comment by DarthSim** [comment]
`aHR0cHMlM0ElMkYlMkZwb3J0YWwuZmxlZXQtZXZlbnRzLmRlJTJGZGUlMkZmaWxlcyUzRnBhdGglM0Rsb2dvcyUyRmJhYmluaS5qcGc=` is decoded to escaped (urlencoded) URL. You shouldn't escape the URL before encoding to base64. 
https://go.dev/play/p/QRxbGPsnpY2

**Comment by visioncode** [comment]
@DarthSim you are right and this example now works .. but why do I get an "Source image is unreachable" error while using another path? Could you please try this out:

https://imgproxy.example.com/U7M1N22BUBGrMhmgY6TY1SLFhoV7DXsxwOf9AnAQ_eE/aHR0cHM6Ly9wb3J0YWwuZmxlZXQtZXZlbnRzLmRlL2RlL3VwbG9hZHM/cGF0aD0xMjYyL3Byb2ZpbGUuanBn

Thanks for help!

**Comment by DarthSim** [comment]
You should use URL-safe base64 encoding, meaning you need to replace `/` with `_` and `+` with `-`. Your base64 string contains `/`:

```
aHR0cHM6Ly9wb3J0YWwuZmxlZXQtZXZlbnRzLmRlL2RlL3VwbG9hZHM/cGF0aD0xMjYyL3Byb2ZpbGUuanBn
                                                       ^here
```

**Comment by visioncode** [comment]
thanks, works like a charm now! :)
