### ISSUE TITLE
Feature request: New info endpoint that let's you extract coordinates of detected objects

### ISSUE THREAD

**Issue by marcuslindblom** [imgproxy/imgproxy#1060]
This request has been discussed with @DarthSim over email and is a part of a bigger feature. This is a placeholder issue so we can follow the work and get notified when it's done.

**Comment by DarthSim** [comment]
Hey @marcuslindblom!
The new `/info` endpoint is literally the next thing on our roadmap. We're going to start its development this week. I just need to finish the documentation for the currently developed feature :)

**Comment by marcuslindblom** [comment]
@DarthSim any progress on this one?

**Comment by DarthSim** [comment]
@marcuslindblom We'll probably include this in the next minor release

**Comment by marcuslindblom** [comment]
That sounds awesome 👏

**Comment by DarthSim** [comment]
Here it is https://docs.imgproxy.net/getting_the_image_info?id=crop ☺️
