### ISSUE TITLE
Video thumbnail not generated for specific files

### ISSUE THREAD

**Issue by bsboris** [imgproxy/imgproxy#1065]
Hi @DarthSim!

For some reason, Imgproxy Pro is unable to generate thumbnails for some MP4 files. Log says "Can't download source image: Source image type not supported". I was unable to locate problem myself, files look OK. Can you please take a look? Here is one example: https://drive.google.com/file/d/1CuUuWAT5lkGp1_5D8cch5DWzf6Y_bj6v/view?usp=share_link

**Comment by DarthSim** [comment]
Fixed in the `latest` build. If imgproxy won't recognize other MP4s, feel free to drop me a message at darthsim@imgproxy.net. The first 12 bytes of the file would be enough :)
