### ISSUE TITLE
Animated webp

### ISSUE THREAD

**Issue by marcuslindblom** [imgproxy/imgproxy#1066]
Is animated webp supported? I'm uploading [this](https://mathiasbynens.be/demo/animated-webp) image but I only get a still?

**Comment by DarthSim** [comment]
Hey @marcuslindblom! Did you set `IMGPROXY_MAX_ANIMATION_FRAMES`?

**Comment by marcuslindblom** [comment]
@DarthSim oh, nope. I thought that one was for videos 😀
What value can you recommend?

**Comment by DarthSim** [comment]
IDK, it depends on your case, the RAM you have, the time you're ready to wait for the image to be ready, and stuff. I've seen GIFs with up to 300 frames and theoretically, this is not a limit. Yet most animated images have fewer frames. So there's no silver-bullet value for this config. Some set it to 999 meaning "I don't care, just process everything".

**Comment by marcuslindblom** [comment]
Ok, I'll do some experiments.
