### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by benharvie** [imgproxy/imgproxy#1079]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@emredurmaz4) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by DarthSim** [comment]
Hey @benharvie!

We have a security contact in our README: https://github.com/imgproxy/imgproxy#security-contact. I'll think about adding a `SECURITY.md` file 👍

You can send the vulnerability details to security@imgproxy.net

**Comment by emredurmaz4** [comment]
Hi @benharvie <https://github.com/benharvie>!

How does the process work here?

Do you explain the details or do we?

How shall we proceed?

Best regards,
Emre

Sergey Alexandrovich ***@***.***>, 13 Oca 2023 Cum, 18:39
tarihinde şunu yazdı:
