### ISSUE TITLE
Img urls with multiple periods fail

### ISSUE THREAD

**Issue by Trevogre** [imgproxy/imgproxy#1088]
https://m.media-amazon.com/images/M/MV5BMjA3MjYyNTk0Nl5BMl5BanBnXkFtZTgwODc1NzQ1NTE@._V1_SY1000_SX677_AL_.jpg

The above image url parses out in your program as ._V1_SY1000_SX677_AL_.jpg for the format. Making everything after the first period the format. I'm not sure how extensive an issue this is but these are amazon hosted images so I think it makes sense to work backwards to the first period from the right to determine the file format string.

**Comment by DarthSim** [comment]
Hey @Trevogre!
Multiple periods is not a problem. The problem is the `@` character which should be escaped in plain source URLs: https://docs.imgproxy.net/generating_the_url?id=plain
