### ISSUE TITLE
"Unknown sheme"

### ISSUE THREAD

**Issue by pcj** [imgproxy/imgproxy#1089]
https://github.com/imgproxy/imgproxy/blob/e719c9d39bab0b70d2be1c772fd27a03b617aac7/imagedata/download.go#L145

Error message has a typo.  I'd have created a PR myself via the UI since I don't have it cloned but github seems to be pushing github.dev, which doesn't seem to work.

**Comment by DarthSim** [comment]
Thanks for the catch! Fixed in https://github.com/imgproxy/imgproxy/commit/d5d3e32df06ff62447cf36f487d3c434ee9e6761
