### ISSUE TITLE
SVG source to rasterized format broken

### ISSUE THREAD

**Issue by goldelehr** [imgproxy/imgproxy#1107]
Hi,

when trying to convert SVG files to PNG (or JPG) files we receive strange artifacts on the result and the conversion is missing all text elements of the origin vector image. 

The files we are trying to convert are EU energy labels:

https://eprel.ec.europa.eu/label/Label_446437.svg
![Label_446437](https://user-images.githubusercontent.com/404557/217500196-d7dda585-cd89-4bf7-9739-68c7ca58afdd.svg)

Upon converting we receive this (on every conversion the result is slightly different):

![errora](https://user-images.githubusercontent.com/404557/217500010-567f4f9c-0abc-4f49-bc53-df47510e92de.png)![errorb](https://user-images.githubusercontent.com/404557/217500036-83b4d859-794b-4727-a7ce-5ccd5b399c65.png)![errorc](https://user-images.githubusercontent.com/404557/217500086-11204ee4-34f4-48aa-8b2c-84b3cfe05058.png)

Thanks for your help

**Comment by DarthSim** [comment]
Hey @goldelehr!
I added `fontconfig-config` to the `latest` build. Should solve the issue.
