### ISSUE TITLE
Cache-Control flag for fallback image

### ISSUE THREAD

**Issue by ehiggs-deliverect** [imgproxy/imgproxy#1108]
When a fallback image is used, it has no special information regarding the cache like implemented for #319. This means a fallback image could be cached aggressively even though the image could have been not available due to an intermediate failure.

For fallback image, add another envvar to allow a smaller Cache-Control age than a normal image.

**Comment by DarthSim** [comment]
I guess `IMGPROXY_FALLBACK_IMAGE_TTL` is what you are looking for
