### ISSUE TITLE
Expires option does not adjust expires header

### ISSUE THREAD

**Issue by webjunkie** [imgproxy/imgproxy#1117]
Despite setting an expiration time using the expires option, the expires header is not being updated accordingly. This means that potentially a cached image is not being invalidated as expected, causing stale images to persist for longer than intended. Stale images can pose a security risk, especially if they contain sensitive information that should not be accessible to unauthorized users. If these images are not being invalidated as expected and kept around in caches, they might still be accessed by anyone, even after the expiration time has passed. This can lead to data breaches or other security incidents.

I acknowledge that the expires option is intended to invalidate the URL after a certain time, while the expires header is used for caching purposes. However, since the intention is for the URL to be invalid after the expiration, it may be more appropriate for the expires header to reflect the expiration time as well.

Steps to reproduce:

- Set an expiration time using the Expires option in imgproxy configuration.
- Request an image using imgproxy.
- Check the expires header in the response.

Expected behavior:
The expires header in the response should reflect the expiration time set using the Expires option, to ensure that cached images are invalidated as expected.

Actual behavior:
The expires header in the response is some other value, unaffected by the set expires time.

**Comment by DarthSim** [comment]
Hey @webjunkie!
This makes sense 🤔 I added this to our roadmap.

**Comment by DarthSim** [comment]
Fixed the behavior in the `latest` build

**Comment by webjunkie** [comment]
Great, thank you!

This would be commit https://github.com/imgproxy/imgproxy/commit/50d04d585ef543122a3edbca24702e22abb88917. (Linking here since the commit does not mention this issue)
