### ISSUE TITLE
`IMGPROXY_ONLY_PRESETS` should allow `presets` processing option

### ISSUE THREAD

**Issue by allanlei** [imgproxy/imgproxy#1118]
[The `preset` filter](https://docs.imgproxy.net/generating_the_url?id=preset) allows specifying a list of presets to be applied, but since it itself is a processing option, `IMGPROXY_ONLY_PRESETS` will disallow it even if it is the only option.

Dropping the `preset` and using the non-processing option is ok

```
docker run -it --rm \
  -e 'IMGPROXY_PRESETS=64x64=resize:fit:64:64, webp=format:webp' \
  -e 'IMGPROXY_ONLY_PRESETS=1' \
  -p 8080:8080 \
  darthsim/imgproxy:v3.13.2
```

* :x: http://127.0.0.1:8080/unsafe/preset:64x64:webp/plain/https://imgproxy.net/5c3c6ff521c49d78a7f14a7d859964b4.svg
* :heavy_check_mark:  http://127.0.0.1:8080/unsafe/64x64:webp/plain/https://imgproxy.net/5c3c6ff521c49d78a7f14a7d859964b4.svg

**Comment by DarthSim** [comment]
The whole idea of presets-only mode is to remove processing options from the URL, keeping only preset names. What’s the use case of keeping the `preset` option name?

If you have reasons to have your presets list starting with `preset:`, you can add a useless preset called `preset`. Something like `preset=cb:1`

**Comment by allanlei** [comment]
Our use case for `preset` is that we will have multiple instances of imgproxy with/without `IMGPROXY_ONLY_PRESETS` (OSS/licensed)

It just seemed that both formats should be compatible with `IMGPROXY_ONLY_PRESETS` for consistency sake as both only provide a list of presets. Maybe add a note for `IMGPROXY_ONLY_PRESETS` that it doesn't support `preset`.

The workaround works. We use the same method for preset list generation with nginx.  Would supporting a `noop` be possible?

---

Not sure if this is the right place to ask, but I didn't get any responses for purchasing licenses for imgproxy

**Comment by DarthSim** [comment]
Sorry for the delay.
Making `preset` an unsupported name for a preset in the middle of the feature lifecycle is not a good idea. So current users might use `preset` as a preset name, and this will break their setup.
