### ISSUE TITLE
How do I use the prebuilt docker image with local filesystem?

### ISSUE THREAD

**Issue by rouilj** [imgproxy/imgproxy#1126]
I develop an issue tracking system. People add images to the issues (screenshots etc.). I would like to use imgproxy to optimize the delivery of these images.

The images are stored in files on local disk. My first thought was to replace an image URL that
normally looks like this:
```
    https://example.com/issues/file14/face.jpg 
```
with (URL wrapped for readability; I explain why I am using expires below):
```
    https://example.com/imgproxy/security_hash/rs:fit:300:200:0:0/
           filename:face/expires:XXXXX/plain/local:///0/file14 
```
Then I run imgproxy with `IMGPROXY_LOCAL_FILESYSTEM_ROOT=/images` to reference the data stored in the file
```
   ~tracker/db/files/0/file14
```
and mount `~tracker/db/files` on `/images` in the docker volume.

I tried this, but it does not look like the distributed docker image has a volume/mount point exposed
according to docker inspect.

The `expires` value `XXXX` will be set to  5 seconds after the web page request has been received. Using expires is an attempt to prevent the URL from being used by another party. Images have access controls
in the tracker that determine if the image is accessible to the user. So I use a short duration time to allow the user to access it while the web page is loading, but not be able to use the URL outside of the loading time for the current page. Granted the user can screenshot the image etc. however this
is additional protection to prevent direct access to imgproxy from leaking potentially sensitive data
since it can't authenticate/authorize the user.

So three questions:

  1) can the distributed docker image be generated with a volume at `/images` (or other suitable mountpoint)

  2) does my proposed deployment method sound workable

  3) will the use of `expires` help "secure" the image data
 
Thanks and have a great week.

Also I added: https://github.com/imgproxy/imgproxy/pull/1135 to add /images volume to the
Dockerfile and image.

[ edited replacement url to put / between the processing options components and fix the resize option argument, and remove explicitly requesting a file type to set imgproxy choose the best
alternative. Added pull request]

**Comment by DarthSim** [comment]
Hi @rouilj!

If your images are located in the filesystem available to your Docker engine, then using the `local:///` scheme is the most optimal way.

If you run imgproxy with `docker run`, you can use the `-v` flag to mount you:

```
docker run -v /path/to/local/dir:/images -it darthsim/imgproxy:latest
```

If you run imgproxy with `docker service run` you can use the `--mount` flag:

```
docker servive run --mount type=bind,src=/path/to/local/dir,dst=/www -t darthsim/imgproxy:latest
```

I don't think the `expires` option will enhance security much. If someone with access to the image wants to share it, they can just save the image and share it without the URL. If you don't want random people to be able to craft a URL for an image they don't have access to, it's enough to sign your URLs.

However, the `expires` option may make it difficult to share images by sharing their URLs. Though I think 5s is a too short period. If one has a bad internet connection, they may not be able to request the images.

**Comment by rouilj** [comment]
Hello @DarthSim,

> If you run imgproxy with `docker run`, you can use the `-v` flag to mount you:
> ```
> docker run -v /path/to/local/dir:/images -it darthsim/imgproxy:latest
> ```
> If you run imgproxy with `docker service run` you can use the `--mount` flag:
> ```
> docker servive run --mount type=bind,src=/path/to/local/dir,dst=/www -t darthsim/imgproxy:latest
> ```

Interesting. I didn't realize you could mount a volume when the directory didn't exist in the docker image.
I thought you had to have a VOLUME directive in the Dockerfile to create/mount onto. I'll have to look
for docs on this and try it..

> I don't think the `expires` option will enhance security much. If someone with access to the image wants
>to share it, they can just save the image and share it without the URL. If you don't want random people
>to be able to craft a URL for an image they don't have access to, it's enough to sign your URLs.

Well only the people with access to the original issue would be able share the image. I am concerned
about unintended leakage of the link to unauthorized parties.

> However, the `expires` option may make it difficult to share images by sharing their URLs.

True, but if you didn't have authorization to see the image in the first place, having the original
URL (not pointing to imgproxy) wouldn't let you see it either. As it turns out, a short expired
option makes saving an image difficult. On chrome at least saving an image appears to download
it again. Which is weird. I would have expected it to pull from the cache. But the cache lifetime
is the URL lifetime apparently. So saving the file after 5 seconds may require downloading the
file again as it had been purged from the browser cache???

Speaking of cache, can I change the cache header to use private rather than public? I have the cache
lifetime set to 1 (`IMGPROXY_TTL=1`). Apparently 0 is not allowed. So it should disappear from any caching servers even if the expires property is set to 3 minutes.

Just out of curiosity, is there a way to modify the varies header? Currently it includes Accept.

I am running imgproxy behind a reverse proxy, so I could change the Varies and Cache headers seen upstream at the reverse proxy. That probably is a better choice than complicating imgproxy.

>Though I think 5s is a too short period. If one has a bad internet connection, they
>may not be able to request the images.

Good point. I have run into this when I had 30 images displayed in a ticket as well. Lazy loading
also can delay loading long enough to time out. I have a working implementation
I need to finish documenting it. It allows the user to set the TTL/expires time for just this
reason. I'll toss the URL for the implementation in this ticket in case anybody is interested.

I think of the signed URL the same way I think of a Java Web Token (JWT).
The signed URL in this use case is effectively an authentication/authorization token signed by the
URL generator. Same as a JWT. We can't revoke either a URL or a JWT, so I use short lifetimes to
reduce the risk from them leaking.

I also looked at thumbor. They have a similar signing mechanism for preventing DOS attacks. But they
are missing the ability to invalidate the URL (no expires equivalent).

This may be an incorrect way to look at the signed URL, but that's how I view them.

Thanks for your feedback. Have a great week.

-- rouilj

**Comment by rouilj** [comment]
Just to close this up, I documented using this with [Roundup](https://www.roundup-tracker.org) at https://wiki.roundup-tracker.org/EfficientImageServing.

Thanks for the AWS reference. It looks like they move the expiration into into a policy tied to the
request by public/private key signature on the url. So they find the key used to sign the URL, determine
the expiration time using the key. Since the expiration time is not in the URL multiple URL's can
access the same data with a different expiration time.

Have a great weekend.

-- rouilj
