### ISSUE TITLE
Removing "insecure" from url

### ISSUE THREAD

**Issue by veveme** [imgproxy/imgproxy#1138]
Hi. I'm using presets `IMGPROXY_PRESETS` and `IMGPROXY_ONLY_PRESETS`. I know signing url is best option for security, but I need to give control to front, as a alternative for imgix. For me defined presets plus cloudflare is enough secure. But I still have that `/insecure/` in url. Hot to get rid of that? 

What's weird - if I remove that part from url, image still works, but it returns original instead edited one.

**Comment by DarthSim** [comment]
Hey @veveme!
It works because imgproxy always treats the first segment of the path as a signature. If key/salt pairs are not configured, the signature segment can be literally anything, `insecure` is not a mandatory value.

**Comment by veveme** [comment]
@DarthSim already tried that. When I change "/insecure/" to any another word, like "/xyzabc/" I'm getting "Invalid URL". Key/salt is not set.

**Comment by DarthSim** [comment]
You can take a look at imgproxy's logs to find out what's going wrong

**Comment by veveme** [comment]
@DarthSim I'm so sorry. My url was actually broken (wrong image path), but it worked with "insecure" only due to imgproxy or browser cache. Changing "insecure" to any less scary text really works :) I would still love to see a option to remove that part as a whole, but Your solution is still ok :)
