### ISSUE TITLE
Source image is unreachable

### ISSUE THREAD

**Issue by Pijamo** [imgproxy/imgproxy#1142]
Hi 

Im not sure whats wrong but when i want to use the url 
http://localhost:8080/insecure/rs:fill:300:400/g:sm/plain/https://image-hub.reproindialtd.com/9789383331888.jpg 

i get the error "Source image is unreachable". 

There are actually a few thousand (100s of thousands) images I want to process but they are all stored in the same domain. 

Some insight would be very much appreciated.

**Comment by DarthSim** [comment]
Hi @Pijamo!

You can check the imgproxy's logs to see what's going wrong. For security reasons, imgproxy doesn't respond with the full error message and just points to a general cause. But its logs contain the full error message.

Alternatively, you can use the `IMGPROXY_DEVELOPMENT_ERRORS_MODE` config so imgproxy will respond with full error messages. Yet I wouldn't recommend doing it in production.
