### ISSUE TITLE
Add `imagor` to benchmark

### ISSUE THREAD

**Issue by victordidenko** [imgproxy/imgproxy#1143]
Subj, can you please add [imagor](https://github.com/cshum/imagor) to [benchmark](https://github.com/imgproxy/imgproxy/blob/master/BENCHMARK.md)?

[Here](https://news.ycombinator.com/item?id=29514322) is author's word about it:

> A bit of our background: we have been a long time user of Thumbor, with millions of images serving under it and applications built around the Thumbor syntax. However Thumbor is not quite in active development anymore. Support is getting stale, and its stable version is still using Python 2.
> 
> So we started to look to alternatives. We wanted to keep the Thumbor syntax as it is a pretty good one, and we want no disruption to our existing image urls being created, and applications that built around it. So we wanted a drop-in replacement. We studied closely with Imaginary and Imgproxy which both are made with Go and libvips. Imgproxy is a pretty solid one, but we are not happy it is charging for premium, even for common features like Chained pipelines (a.k.a filters). Imaginary is very popular, but the feature parity gap is pretty large between Imaginary and Thumbor, with ongoing memory issues and the author seems not interested in maintaining it recently. And most importantly, neither of both sides are interested in adopting Thumbor's URL syntax. And building a proxy around them would be a half baked solution, as their high level APIs are unlikely meet the Thumbor's feature parity. And so we decided to do the hard work and here it is.
> 
> We have already implemented all features we need and it is working great for us in production. The S3 Loader/Storage is battle tested, but the file store is not though. We do acknowledge it has a long way to go to meet the Thumbor's feature parity. But this is just our first step and of course we wanna keep pushing it.

**Comment by DarthSim** [comment]
When we'll find time for a new benchmark – sure

**Comment by DarthSim** [comment]
We posted the new benchmark results to our blog some time ago: https://imgproxy.net/blog/image-processing-servers-benchmark/
