### ISSUE TITLE
Raw URL with extension

### ISSUE THREAD

**Issue by pcj** [imgproxy/imgproxy#1144]
Is it possible to use `raw:1` in conjunction with a file extension?  I'm using imgproxy to serve some audio files.  The encrypted URL does work (OK 200), but the path is extensionless.  I'm trying to serve a raw file with the extension, but it attempts to apply a format if the extension is present in the URL.  For an audio file, this results in an error like "Invalid image format: wav".

OK: 

https://example.com/1EHza8rHO6NkAseaHS5eIKhx_HS4Y03W-nUc0Ij7k9g/g:ce/raw:1/aHR0cDovL2Nhcy5pc3AvY2FzLzZmZTcwY2NjNWZmZjQwMmY3MzRkNWYxMWE4NGE2MzJhYzFjNDIwMjZhOTkzMTNjNjNhZTliYWY1N2MyY2YyMDE

Want:

https://example.com/1EHza8rHO6NkAseaHS5eIKhx_HS4Y03W-nUc0Ij7k9g/g:ce/raw:1/aHR0cDovL2Nhcy5pc3AvY2FzLzZmZTcwY2NjNWZmZjQwMmY3MzRkNWYxMWE4NGE2MzJhYzFjNDIwMjZhOTkzMTNjNjNhZTliYWY1N2MyY2YyMDE.wav

**Comment by DarthSim** [comment]
Hey @pcj!
I disabled the extension checking if the `raw` option is used

**Comment by pcj** [comment]
Gotcha, looks like this was implemented in https://github.com/imgproxy/imgproxy/commit/25459ef88c3ee7f3ec3b8ec235002e2eb6d000cd.  I'll close the issue, thanks!
