### ISSUE TITLE
[Question] Can we use strip_metadata if the default is true?

### ISSUE THREAD

**Issue by HardeepAsrani** [imgproxy/imgproxy#1151]
Doc ref: https://docs.imgproxy.net/generating_the_url?id=strip-metadata

If we've configured imgproxy to use the strip_metadata default of true, can we override it by adding `sm:0` or `sm:false` to request metadata on image basis?

**Comment by DarthSim** [comment]
Hey @HardeepAsrani! Sure you can

**Comment by HardeepAsrani** [comment]
Hey @DarthSim,

We've this image here: https://sealdrink.s1-tastewp.com/wp-content/uploads/2023/05/IMG_0506.jpg - it seems to have the metadata. And here we have it over imgproxy and it doesn't have the metadata, regardless what I use:

- https://mlhjitngqdy0.i.optimole.com/sm:false/https://sealdrink.s1-tastewp.com/wp-content/uploads/2023/05/IMG_0506.jpg
- https://mlhjitngqdy0.i.optimole.com/sm:0/https://sealdrink.s1-tastewp.com/wp-content/uploads/2023/05/IMG_0506.jpg
- https://mlhjitngqdy0.i.optimole.com/strip_metadata:false/https://sealdrink.s1-tastewp.com/wp-content/uploads/2023/05/IMG_0506.jpg

FYI, it had other attributes too which I've removed to share as an example.

Any idea if we're doing something wrong or something else might be causing it?
