### ISSUE TITLE
Config timeout not woking

### ISSUE THREAD

**Issue by toannv1803** [imgproxy/imgproxy#1154]
My config
```
IMGPROXY_CONCURRENCY=1
IMGPROXY_READ_TIMEOUT=30
IMGPROXY_WRITE_TIMEOUT=30
IMGPROXY_KEEP_ALIVE_TIMEOUT=30
IMGPROXY_CLIENT_KEEP_ALIVE_TIMEOUT=30
IMGPROXY_DOWNLOAD_TIMEOUT=15
```
Docker version: darthsim/imgproxy:v3.14.0

I set IMGPROXY_CONCURRENCY=1 and resize gif take 1h23m, while processing this gif, all request will timeout.
But I set all timeout config, and don't known why it not work in this context.
This bug can't reproduce. I try resize this gif to reproduce this bug but image proxy resize success. 
![Some log](https://user-images.githubusercontent.com/53045024/236751765-a67e0cd8-0826-4658-9e2c-e54bbb583eb5.png)

**Comment by DarthSim** [comment]
Hey @toannv1803!

Unfortunately, imgproxy can't interrupt image processing in the middle of a libvips operation. This may lead to a case where a request may take more time than allowed by `IMGPROXY_WRITE_TIMEOUT`.

Unlike ImageMagick and friends, libvips doesn't perform operations immediately. Instead, it stacks operations and performs them only when it needs access to pixels. Most often it happens at the image-saving stage. This allows to speed up the processing and lower memory footprint.

Theoretically, it is possible to stop processing after a pixel block evaluation, but this will slow down the processing.
