### ISSUE TITLE
Force a format

### ISSUE THREAD

**Issue by phaberest** [imgproxy/imgproxy#1158]
I installed imgproxy in a docker container proxied by nginx. I would like to be able to use it to process my images and save them in many formats to allow multiple sizes as well as multiple formats(mainly jpg, webp and avif) I can then use to feed a `picture` tag.

I tried using the [format](https://docs.imgproxy.net/generating_the_url?id=format) parameter, but it looks like it is ignoring it.

```
http://localhost:8080/insecure/f:png/rs:fill:300:400/g:sm/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL00v/TVY1Qk1tUTNabVk0/TnpZdFkyVm1ZaTAw/WkRSbUxUZ3lPREF0/WldZelpqaGxOemsx/TnpVMlhrRXlYa0Zx/Y0dkZVFYVnlOVGMz/TWpVek5USUAuanBn.jpg
```

With an url like the above I keep getting a jpg. I tried adding `@png` and it simply returns a 404.

What am I missing?

**Comment by DarthSim** [comment]
Hey @phaberest!

You are using [base64-encoded source URL](https://docs.imgproxy.net/generating_the_url?id=base64-encoded) with an extension. Extension rewrites the `format` option value. You need either remove the extension or use it to specify the resulting format.

**Comment by phaberest** [comment]
Thank you @DarthSim it was definitely a PEBCAK 🥲

Silly me.

Thanks again!

**Comment by DarthSim** [comment]
No problem ☺️
