### ISSUE TITLE
Feature request: Override DPI metadata

### ISSUE THREAD

**Issue by sagebind** [imgproxy/imgproxy#1160]
Howdy! I'm the annoying DPI guy from [this issue](https://github.com/imgproxy/imgproxy/issues/668) back again for more DPI punishment. As I mentioned in that previous issue, our customers are pretty sensitive about DPI metadata, even though it does nothing technically when a thumbnail is simply used on the web. That definitely still holds true (much to my chagrin) and now I'm back with another feature request related to DPI.

Well, we have a new need for being able to set _arbitrary_ DPI values (`xres` and `yres`) on thumbnails we return, and after some thought it seems like doing this within imgproxy itself makes the most sense, as it is something imgproxy is already privy to via libvips, and our other solutions that add some kind of processing in _front_ of imgproxy would not be great for performance.

So basically, the feature that we'd like to see in imgproxy is the introduction of a new processing option called `dpi` (or `resolution`, or whatever really) that accepts at least one absolute number to use as a DPI value to set on the image before returned in the response. I could see how accepting separate X and Y values as two distinct values would potentially make sense, though that is not necessary for our use-case (we'd just always pass the same number for both). Probably still premultiplied in units of pixels-per-inch though from the caller's perspective.

As far as to how this would interact with the `strip_metadata` option, I'd expect this new option to take precedence. For example, if both `strip_metadata:1` and `dpi:300` were to be passed, I'd expect the DPI to be unconditionally "reset" to 300 rather than 72. But also, this option should work if `strip_metadata` were not used at all.

That said, this is kind of a weird request and I'd understand if this wasn't something really in scope for imgproxy (though it would make my life _way_ easier). Thanks!

**Comment by DarthSim** [comment]
Hey @sagebind!

You're not the first one asking for this 🙂 Here you go https://docs.imgproxy.net/latest/generating_the_url?id=dpi. Available in the `latest` build
