### ISSUE TITLE
Q: upstream caching proxy?

### ISSUE THREAD

**Issue by michaelherger** [imgproxy/imgproxy#1163]
My application would often request the same image in different sizes within a second. While I do understand that imgproxy doesn't do any caching by design, I was wondering whether my use case would cause imgproxy to download the origin picture each time?

If that was the case, would using an upstream caching proxy make sense? Eg. have Squid or the like cache the origin file "locally" so imgproxy wouldn't have to pull it across the internet each time? I tried to find a configuration option for an upstream proxy. But it's kinda hard to search for "proxy" in the imgproxy documentation :joy:.

Here's a snippet from the log where four versions of the same file were requested:

```
Completed in 1.901793239s /x/rs:fit:1024:1024:0/g:no/plain/https%3A%2F%2Flastfm.freetls.fastly.net%2Fi%2Fu%2F_%2F3d1ea510ce3c874fff36b0c41fdb88b9.png%3Fsizes%3D300x300%7C300x300%7C174s%7C64s%7C34s@jpg
Completed in 1.721464706s /x/rs:fit:300:300:0/g:no/plain/https%3A%2F%2Flastfm.freetls.fastly.net%2Fi%2Fu%2F_%2F3d1ea510ce3c874fff36b0c41fdb88b9.png%3Fsizes%3D300x300%7C300x300%7C174s%7C64s%7C34s@jpg
Completed in 1.504430614s /x/rs:fit:480:480:0/g:no/plain/https%3A%2F%2Flastfm.freetls.fastly.net%2Fi%2Fu%2F_%2F3d1ea510ce3c874fff36b0c41fdb88b9.png%3Fsizes%3D300x300%7C300x300%7C174s%7C64s%7C34s@jpg
Started /x/rs:fit:480:480:0/g:no/plain/https%3A%2F%2Flastfm.freetls.fastly.net%2Fi%2Fu%2F_%2F3d1ea510ce3c874fff36b0c41fdb88b9.png%3Fsizes%3D300x300%7C300x300%7C174s%7C64s%7C34s@jpg
Started /x/rs:fit:300:300:0/g:no/plain/https%3A%2F%2Flastfm.freetls.fastly.net%2Fi%2Fu%2F_%2F3d1ea510ce3c874fff36b0c41fdb88b9.png%3Fsizes%3D300x300%7C300x300%7C174s%7C64s%7C34s@jpg
Started /x/rs:fit:1024:1024:0/g:no/plain/https%3A%2F%2Flastfm.freetls.fastly.net%2Fi%2Fu%2F_%2F3d1ea510ce3c874fff36b0c41fdb88b9.png%3Fsizes%3D300x300%7C300x300%7C174s%7C64s%7C34s@jpg
```

This is a relatively heavy 1.8MB, 1342x1342px PNG file. Considering the processing time I must assume it was downloaded afresh on each request.

**Comment by y3ti** [comment]
Content caching is a significant topic. I suppose it's simpler to utilize a CDN such as Amazon CloudFront or CloudFlare. Alternatively, if you're not operating 'in the cloud', it would be more effective to position nginx in front of imgproxy and configure caching within nginx

**Comment by michaelherger** [comment]
I do understand that a CDN is the way to go on the way out of imgproxy (to cache the resized images). But the case I'm raising is the opposite, on the incoming side. I'm requesting the same image in different sizes. An outgoing cache therefore wouldn't help, as parameters change. But imgproxy would now download the same image from its origin multiple times. I therefore was considering a caching proxy _behind_ imgproxy:

first call: client request -> imgproxy -> cache -> origin -> cache -> imgproxy -> client
second: client request -> imgproxy -> cache -> imgproxy -> client

And as I'd keep the cache on the same system or close to imgproxy there wouldn't be another slow transfer across the internet.

**Comment by michaelherger** [comment]
Great, thanks! I'll play with those variables.
