### ISSUE TITLE
CORS header adding trailing slash automatically

### ISSUE THREAD

**Issue by joaofrca** [imgproxy/imgproxy#1165]
When adding CORS header parameter, such as `IMGPROXY_ALLOW_ORIGIN =https://my.domain.com`, imgproxy always adds a trailing slash by default, converting it to `IMGPROXY_ALLOW_ORIGIN =https://my.domain.com/`. These are different URLs and I believe it is a good practice to avoid the trailing slash.
Is there a way of not adding it? I also tried `IMGPROXY_ALLOW_ORIGIN =https://my.domain.com*` but does not work either.

**Comment by joaofrca** [comment]
Hi @DarthSim, do you eventually know if I am missing something here?
Thanks in advance! 🙇

**Comment by DarthSim** [comment]
Hey @joaofrca!
That's weird that you're facing this problem. imgproxy does nothing fancy but [fetch the env variable](https://github.com/imgproxy/imgproxy/blob/master/config/config.go#L484) as is and [put it to the header](https://github.com/imgproxy/imgproxy/blob/master/server.go#L108) without any modifications.

**Comment by joaofrca** [comment]
Hi @DarthSim !
Thanks lots for your input 🙇 You're totally right, this is not related with imgproxy at all.. Closing the ticket.
Thank you! 🙏
