### ISSUE TITLE
Unprocessable video files

### ISSUE THREAD

**Issue by dmkl** [imgproxy/imgproxy#1167]
Imgproxy PRO fails to create a thumbnail for some video files. We have hundreds of cases. Not sure if it's some new codec that is not yet supported. I attach the video metadata info.

```
/unsafe/rs:fit:2560:2560:0/plain/https://<my cloud storage>/dca99d008fed1b2cf178ccf1822ab0da.mp4  request_id=JHr1fDHCZKe2TAF0emHVM method=GET status=422 client_ip=127.0.0.1 error="Can't download source image: Source image type not supported"
```

Please let me know home many first bytes of the problematic file you need to check it or let me know where I can mail you the example file. I'm not allowed to share it here publicly.

![SCR-20230621-nxut](https://github.com/imgproxy/imgproxy/assets/652653/6b5e9557-354b-4baa-99ef-b7dca06eb4de)

**Comment by dmkl** [comment]
The first 12 bytes:

```
0, 0, 0, 28, 102, 116, 121, 112, 88, 65, 86, 67, ...
```

```
$ cat unprocessable.mp4

^@^@^@^\ftypXAVC^A^@^_<FF>XAVCmp42iso2^@^@^@<94>uuidPROF!<D2>Oλ<88>i\<FA><C9><C7>@^@^@^@^@^@^@^@^C^@^@^@^TFPRF^@^@^@^@ ^@^@^@^@^@^@^@^@^@^@,APRF^@^@^@^@^@^@^@^Btwos^@^@^@^@^@^@^@^@^@^@^F^@^@^@^F^@^@^@<BB><80>^@^@^@^B^@^@^@4VPRF^@^@^@^@^@^@^@^Aavc1^Ad^@)^@^C^@ ...
```

**Comment by DarthSim** [comment]
@dmkl Thanks! I'll add these magick bytes to imgproxy. Do all of the problematic videos have the same first 12 bytes? Also, if you could send a link to one of the problematic videos to darthsim@imgproxy.net, I could test the fix before pushing it.

**Comment by dmkl** [comment]
@DarthSim it seems to work! Thanks a lot!

**Comment by dmkl** [comment]
@DarthSim we found another unprocessable video, please check if it can be fixed

[727b1a08ba5de1a8225c488eb035d91c.mp4.zip](https://github.com/imgproxy/imgproxy/files/12102195/727b1a08ba5de1a8225c488eb035d91c.mp4.zip)

**Comment by DarthSim** [comment]
@dmkl Thanks for the sample! Added its magick bytes to the `latest` build
