### ISSUE TITLE
enabling linear colorspace causes a completely black image on resize

### ISSUE THREAD

**Issue by markmartirosian** [imgproxy/imgproxy#1171]
```
unsafe/quality:100/height:512/g:sm/plain/https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Calliphora_sp_Portrait.jpg/804px-Calliphora_sp_Portrait.jpg
```

This would also affect #145.

**Comment by markmartirosian** [comment]
@DarthSim `v3.0.0` doesn't have this issue, it starts in `v3.1.0`. Hope this helps!

**Comment by DarthSim** [comment]
Hey @markmartirosian!
Thanks for the report! It's a libvips bug that they decided not to fix for some reason: https://github.com/libvips/libvips/issues/2858. Added a walkaround to the latest build.

**Comment by markmartirosian** [comment]
@DarthSim, thank you very much. I am looking forward to the release.
