### ISSUE TITLE
When the cdn cached image is requested again, the server still processes the image, resulting in a log message

### ISSUE THREAD

**Issue by lxccc812** [imgproxy/imgproxy#1175]
I use Cloudflare to cache my images, and when I request a cache image, it still goes through the server and generates a log message, and this is the log message that was generated this week.I already know how to separate the log messages and limit the log size, so let's not discuss this for the moment,I just want to know that the cached images still need to go through the server when they are asked again?Is this a normal phenomenon?
![image](https://github.com/imgproxy/imgproxy/assets/110974969/b8cf7343-750d-45b6-9b20-79476a7df05d)

**Comment by DarthSim** [comment]
Hi @lxccc812,

Usually, CDNs don't need to reach the origin to serve cached content. Unfortunately, I can't say why you're having problems with Cloudflare since I aint work in Cloudflare.

I'm closing the issue since it is not directly related to imgproxy, and Cloudflare has its own community.
