### ISSUE TITLE
Working with GIF

### ISSUE THREAD

**Issue by schonert** [imgproxy/imgproxy#1176]
Hey there!

We're opening up support for different filetypes - which includes gif. 
For some reason whenever pass through a gif, with or without any processing options, it returns a still image. Setting the format to @gif or @mp4 does not help. Adding `/raw:1/` was the only option that resulted in a gif.

While debugging I've set
```
IMGPROXY_MAX_ANIMATION_FRAME_RESOLUTION=10000000000000000000000000000000000
IMGPROXY_MAX_SRC_RESOLUTION=50000000000000000000000000000000000000000000000
```

Tried multiple files without luck. What am I missing? 🤓

**Comment by DarthSim** [comment]
Hey @schonert! Take a look at the `IMGPROXY_MAX_ANIMATION_FRAMES` config ;)

**Comment by schonert** [comment]
omg... I was certain I copied the correct variable name. Thanks man!
