### ISSUE TITLE
Transparent video thumbnail for webms

### ISSUE THREAD

**Issue by antoinemacia** [imgproxy/imgproxy#1179]
Hello!

We are wondering if imgproxy supports respecting the transparency of the video  (using webm) when generating thumbnails for it? So far it doesnt seem to work OOTB

Thanks

**Comment by antoinemacia** [comment]
Oh awesome thank you for looking into it :) Here's an example webm

[dancer1.webm](https://github.com/imgproxy/imgproxy/assets/18508791/fdeb4fe9-38ac-4c52-8881-dadc3e99dc38)

**Comment by DarthSim** [comment]
Fixed in `v3.20.0`
