### ISSUE TITLE
Special characters + Whitespaces local directories

### ISSUE THREAD

**Issue by serberci** [imgproxy/imgproxy#1180]
Hi,

I'm trying to use the image resize functionality with the local storage option. The problem that I have is with the special characters and the whitespaces, example below:

I have this folder structure: /test/file_with_character_ß.jpg
And also this one: /test/file with whitespaces.jpg

The requested URL for the first one: http://imgproxy.example.com/insecure/rs:fill:300:400:0/plain/local:////test/file_with_character_ß.jpg
The requested URL for the second one:
http://imgproxy.example.com/insecure/rs:fill:300:400:0/plain/local:////test/file%20with%20whitespaces.jpg

Of course, the response of both of them is a not found. Is there any solution for that?

Thank you!

**Comment by DarthSim** [comment]
Hi @serberci!
I believe, the problem is the 4th slash after `local:`. It should be `local:///`, not `local:////`

**Comment by serberci** [comment]
Hi, with the local://// works for the rest of the files except for the files that has special characters or whitespaces.

Is there no issue related with that?

**Comment by serberci** [comment]
Issue solved by adding the environment configuration in docker:

`
environment:
  LANG: C.UTF-8
  LC_ALL: C.UTF-8
`

**Comment by serberci** [comment]
Tested and working, the solution is just add the configuration for docker
