### ISSUE TITLE
Incorrect orientation detection

### ISSUE THREAD

**Issue by bsboris** [imgproxy/imgproxy#1182]
Hi,

For this specific file Imgproxy /info/ endpoint returns `"Orientation":"Top-left"`.
ExifTool says it `Rotate 270 CW`, so I guess it's not the image problem.

![IMG_6821_view](https://github.com/imgproxy/imgproxy/assets/591230/4ed8c607-7517-4db6-931f-17bdfba67c16)

**Comment by DarthSim** [comment]
Hey @bsboris!

Actually, there're problems with both the image and the way the info endpoint handles this problem. The image contains two EXIF blocks, which I believe is against spec. Libvips and macOS's Preview app parse only the first block while the info endpoint parses the latest one. ExifTool parses both of them, but again, I believe this is against the spec. At least, I can't find how an application should act in this case. So I guess the right thing would be to make the info endpoint parse the first EXIF block.

**Comment by DarthSim** [comment]
Fixed the behavior in the `latest` build

**Comment by DarthSim** [comment]
Fixed in `v3.19.0`
