### ISSUE TITLE
Add average color calculation

### ISSUE THREAD

**Issue by dmkl** [imgproxy/imgproxy#1183]
It would be great to have an option to get an average image color via the `/info` endpoint. Maybe it can be controlled by an ENV var option. Basically, the image can be shrinked down to 1px and its RGB(A) value is returned in hex format. Is there a chance it can be included into the next `/info` update?

**Comment by DarthSim** [comment]
Hey @dmkl!

We're working on some improvements to the info endpoint that will include an optional palette and dominant colors calculation. Would this work for you?

**Comment by dmkl** [comment]
I think we can pick the major dominant color. Not sure what palette is exactly. But if there is anything close enough to the average color it'd satisfy our needs.

**Comment by DarthSim** [comment]
If you're going to use the average color for a kind of placeholder, I'd recommend to take a look at https://blurha.sh. We'll add its calculation to the info endpoint, too

**Comment by dmkl** [comment]
Thanks, @DarthSim! We have experimented with blurhashes already, it looks great, but we still need an average color.

**Comment by DarthSim** [comment]
We added info options to `v3.20.0`. There's an options for the average color: https://docs.imgproxy.net/getting_the_image_info?id=average
