### ISSUE TITLE
Thumbnail of a large svg file will crash imgproxy

### ISSUE THREAD

**Issue by explodi** [imgproxy/imgproxy#1187]
It appears that trying to make a thumbmail of an svg with a large canvas (10800x10800) will make imgproxy crash. Or at least, the following image will fail:

https://drive.google.com/file/d/1s7RLvDZxigXMG9D4tFfdbOhUhPLebEDT/view?usp=sharing

**Comment by explodi** [comment]
After more testing I found that the image can be resized correctly, but the problem is when using the `/trim:0:FF00FF/` option. Examples:

* http://localhost:8080/pr:sharp/rs:fit:120:120:0/plain/https://test-kittl-com.s3.eu-central-1.amazonaws.com/artboard_test.svg@png (succeeds)
* http://localhost:8080/pr:sharp/rs:fit:120:120:0/trim:0:FF00FF/plain/https://test-kittl-com.s3.eu-central-1.amazonaws.com/artboard_test.svg@png (fails)

**Comment by DarthSim** [comment]
Hey @explodi!
`trim` requires decoding the whole image to the memory, and in this case, this causes OOM. This is definitely a problem, I'll take a look.

**Comment by DarthSim** [comment]
`v3.20.0` contains the fix
