### ISSUE TITLE
Colorize transformation

### ISSUE THREAD

**Issue by kartikrao** [imgproxy/imgproxy#1202]
Would it be possible to have a **colorize** transformation that colours the foreground ? This would be very useful for SVG's where one can generate icons of various colours. Typically the background would be transparent.

We are moving a very large site (30M images) from **Cloudinary** to img proxy and this is the last missing piece.

While not in pro currently, we will be signing up shortly.

@DarthSim - I am also willing to do a case study if you DM me.

**Comment by DarthSim** [comment]
Hey @kartikrao!

We have [style](https://docs.imgproxy.net/generating_the_url?id=style) option that was initially added exactly for SVG coloring. You can color your SVG like this: `.../style:KiB7ZmlsbDogI2YwMCAhaW1wb3J0YW50fQ/...`. `KiB7ZmlsbDogI2YwMCAhaW1wb3J0YW50fQ` is base64-encoded `* {fill: #f00 !important}`

> I am also willing to do a case study if you DM me.

Oh, we love case studies! ☺️ I'll drop you a line on LinkedIn

**Comment by kartikrao** [comment]
Thanks @DarthSim, style looks like it will do the trick, do we need to be on PRO before we can try/test it ?

Got your DM on LinkedIn, please leave it with me to action.

**Comment by DarthSim** [comment]
> do we need to be on PRO before we can try/test it ?

Yup, it's a Pro feature. Sent you the trial keys

**Comment by kartikrao** [comment]
@DarthSim - Thanks for the keys, I've got PRO up and running locally.

![Screen Shot 2023-09-20 at 10 35 27](https://github.com/imgproxy/imgproxy/assets/736365/a0e6c9d5-4fb3-4fc9-b761-c01416c2b662)

Tried style out, but unfortunately I _cannot get it to work_.

Here is an example URL where I've attempted to color an SVG icon per your instructions above.
`http://localhost:8080/unsafe/st:KiB7ZmlsbDogI2NjYyAhaW1wb3J0YW50fQ/plain/https://images.drive.com.au/driveau/image/upload/v1/cms/theme/icons/HamburgerMenuIconStraight`

I can see its being picked up and interpreted by imgproxy looking at the logs
```INFO    [2023-09-20T00:32:06Z] Completed in 63.856542ms /unsafe/st:KiB7ZmlsbDogI2NjYyAhaW1wb3J0YW50fQ/plain/https://images.drive.com.au/driveau/image/upload/v1/cms/theme/icons/HamburgerMenuIconStraight  request_id=eQzZpiV_LP_UTcmDLbLL3 method=GET status=200 client_ip=172.17.0.1 image_url="https://images.drive.com.au/driveau/image/upload/v1/cms/theme/icons/HamburgerMenuIconStraight" processing_options="Style: * {fill: #ccc !important}"```

However in the resultant image there is no style node in the output.
![Screen Shot 2023-09-20 at 10 34 39](https://github.com/imgproxy/imgproxy/assets/736365/505d09bb-1ee9-42f3-b626-4399a8eb4346)

![Screen Shot 2023-09-20 at 10 36 42](https://github.com/imgproxy/imgproxy/assets/736365/0cbde4b3-dacb-452a-83c2-28c5d651e04f)

What am I doing wrong ?

**Comment by DarthSim** [comment]
Nah, you're doing everything right, it's just imgproxy fails on this particular SVG. I made a fix in the `latest` build so it should work now.
Thanks for the sample, BTW 😊

**Comment by kartikrao** [comment]
Thank You, I'll give it a shot as soon as its released @DarthSim

**Comment by kartikrao** [comment]
Hi @DarthSim, just checking to see if you had a chance to release this.

**Comment by DarthSim** [comment]
Hey @kartikrao!
We'll probably make a release next week. We'll extend your trial

**Comment by kartikrao** [comment]
@DarthSim - Just following up on this to see if you had a chance to push a new release ?

**Comment by DarthSim** [comment]
`v3.20.0` contains the fix
