### ISSUE TITLE
Demo image from NASA is gone

### ISSUE THREAD

**Issue by shinsenter** [imgproxy/imgproxy#1206]
@DarthSim 
I have noticed that some images used as demos on your website are no longer accessible. The source images taken from NASA's website are also no longer available there.

https://www.nasa.gov/sites/default/files/thumbnails/image/pia22228.jpg

**Comment by DarthSim** [comment]
Thanks a lot, @shinsenter! Had to replace a couple of images, but demos are back on track again

**Comment by shinsenter** [comment]
@DarthSim 
I think you should replace the footer link, too. 😄 
https://www.nasa.gov/mission_pages/mars/images/index.html
