### ISSUE TITLE
Image proccessing malfunction

### ISSUE THREAD

**Issue by pucke-uninow** [imgproxy/imgproxy#1212]
Source Image:
![source_image](https://github.com/imgproxy/imgproxy/assets/64527676/f74f0202-cf6b-4bc1-8da8-cdf093ba06d8)

URL Signature: `http://localhost:808/rs:fit:32:32:1/plain/<link_to_public_s3_bucket>`

Final Image:
![final_image](https://github.com/imgproxy/imgproxy/assets/64527676/e1e82455-cbf9-4007-ab26-188fb8a27ba4)

**Comment by DarthSim** [comment]
Hi @pucke-uninow!

This image seems to be broken. All my image viewers show it cropped, Photoshop can't open it, and ImageMagick fails to convert it.

As for the image not being resized, you missed the signature part of the URL, and imgproxy treats `rs:fit:32:32:1` as a signature. The signature part should always be present in a URL, but when the signature check is disabled, it can contain anything, for example, `unsafe`, or `_`.

**Comment by pucke-uninow** [comment]
Thanks @DarthSim!
We found a bug on our side in the upload of the image to s3, there the image was breaking.
Thanks for the advice with the missing signature!

**Comment by DarthSim** [comment]
No problem! Sorry for the confusion about the signature, I added a warning about this to the latest version of the docs: https://docs.imgproxy.net/latest/generating_the_url?id=signature
