### ISSUE TITLE
Promethues exporter

### ISSUE THREAD

**Issue by r-gilani** [imgproxy/imgproxy#1219]
I need more metrics (/metrics)  for the visibility imgproxy. Do you have any recommendations?

**Comment by DarthSim** [comment]
Hi @r-gilani!

The metrics exported with Prometheus is defined here: https://github.com/imgproxy/imgproxy/blob/master/metrics/prometheus/prometheus.go

What exact metrics are you talking about?

**Comment by r-gilani** [comment]
Hi @DarthSim 
I mean some metrics, like HTTP status code, HTTP method. Because imgproxy acts like a web server, so I expect these metrics.

**Comment by DarthSim** [comment]
I added `status_codes_total` to the `latest` build. The HTTP method metric doesn't make sense for imgproxy as it accepts only GET requests
