### ISSUE TITLE
Feature request: Video thumbnail tile behaviour

### ISSUE THREAD

**Issue by marcuslindblom** [imgproxy/imgproxy#1231]
I'm not sure about the implementation details but my use case is that I want to create an image like the one below. The image contains 50 frames where the first frame is from the beginning of the video and the last frame is from the end of the video. This can be done using steps and duration of the video. It would be great if this was handled by imgproxy internally, maybe as a default behaviour?

Discussed in this thread: https://discord.com/channels/1044580211687174236/1183329675121016862/1183725597520830474

This is the source of a short video:
https://github.com/imgproxy/imgproxy/assets/319720/e218b128-a745-4afd-a502-93fe369bf353

This is the tile from the above video (less then 50 frames):
![Scrub thumbnail](https://github.com/imgproxy/imgproxy/assets/319720/34a5d212-3eab-466f-bd22-d927445686bb)

This is a source a longer video: https://file.io/HKvHsfX4E4rN
And this is the tile from a longer video (50 frames):
![Scrub thumbnail (1)](https://github.com/imgproxy/imgproxy/assets/319720/d7fea105-118a-46b8-8057-4d15118c1247)

**Comment by DarthSim** [comment]
As discussed in Discord, the `latest` build allows to set negative value for the `step` argument of `video_thumbnail_tile` for automagical step calculation.
