### ISSUE TITLE
Im Confused on how to code

### ISSUE THREAD

**Issue by Dreginaldwells** [imgproxy/imgproxy#1243]

**Comment by DarthSim** [comment]
Hey @Dreginaldwells!
Sorry, I can't understand what issue you're facing. Could you elaborate?

**Comment by Dreginaldwells** [comment]
my phone is hacked and i want to learn how to code and to see everything
thats going on with my phone system

**Comment by DarthSim** [comment]
Sorry, this is an issue tracker of imgproxy. We don't teach coding here.

**Comment by Dreginaldwells** [comment]
what exactly do you do if you dont mind me asking? whats a imgproxy
