### ISSUE TITLE
Can warning logs `Recursive preset usage is detected: default` be suppressed?

### ISSUE THREAD

**Issue by rakiyoshi** [imgproxy/imgproxy#1245]
## What

Hi,

We use the `IMGPROXY_ONLY_PRESETS` option and the `default` as the preset name. With that configuration, the imgproxy shows `Recursive preset usage is detected: default` warning logs for each request for the `default` preset.
Can these warning logs suppressed? It's too noisy for us.
We know that warning logs can be suppressed using the `IMGPROXY_LOG_LEVEL` option, but we want to show them because warning logs other than `Recursive preset usage is detected: default` is useful.

## Steps to Reproduce

```console
$ cat presets
default=size:1600:1600
$ docker run \
    -p 8080:8080 \
    -it \
    -v $(pwd)/:/etc \
    -e IMGPROXY_ONLY_PRESETS=true \
    darthsim/imgproxy \
    imgproxy -presets /etc/presets
WARNING [2024-02-15T09:54:42Z] No keys defined, so signature checking is disabled
WARNING [2024-02-15T09:54:42Z] No salts defined, so signature checking is disabled
INFO    [2024-02-15T09:54:42Z] Starting server at :8080
INFO    [2024-02-15T09:54:46Z] Started /-/default/plain/favicon.ico  request_id=d3SMQG8p6I_aDjDKCiRK2 method=GET client_ip=192.168.65.1
WARNING [2024-02-15T09:54:46Z] Recursive preset usage is detected: default
ERROR   [2024-02-15T09:54:46Z] Completed in 773.084µs /-/default/plain/favicon.ico  request_id=d3SMQG8p6I_aDjDKCiRK2 method=GET status=404 client_ip=192.168.65.1 error="Can't download source image: Unknown scheme: "
```

**Comment by DarthSim** [comment]
Hey @rakiyoshi!
I fixed recursive preset usage detection in the `latest` build. Thanks for the report!

**Comment by rakiyoshi** [comment]
Thanks! I confirmed that it does not appear in the warning logs!
