### ISSUE TITLE
Documentation does not mention that presets should be used with a `preset:` prefix in the Presets Guide

### ISSUE THREAD

**Issue by felixmeziere** [imgproxy/imgproxy#1250]
Hi, I just lost a few hours trying to make presets work until I found in the comments of some old issue that I should prepend `preset:` to the presets in the url to make them work (I was always getting `Unknown processing option: blurry` or `Multiple formats are specified: blurrydpr:3g:smq:80plainhttps:host.docker.internal:3000_nextstaticmediajumbotron-image-summer.54637005.webp`).

After looking again in the docs, I found that this is mentioned in the `Processing an Image` guide, but maybe it would be worth mentioning it in the Presets Guide for next people in my case, since I didn't find this after a few hours?

Thanks!

![image](https://github.com/imgproxy/imgproxy/assets/11617630/156e6c93-11b5-4e54-b000-23fa9c122308)

**Comment by DarthSim** [comment]
Hey @felixmeziere!

Thanks for the feedback! I added a few words to the docs to make it clearer
