### ISSUE TITLE
SVG source format doesn't work with WEBP_DETECTION and AVIF_DETECTION

### ISSUE THREAD

**Issue by Frezyy123** [imgproxy/imgproxy#1251]
Hi, I am facing with some undocumented behaviour
If I have svg image as a source and enable all features with [AVIF/WebP support detection](https://docs.imgproxy.net/configuration/options#avifwebp-support-detection), svg image will not be processed and imgproxy return svg image.

Looks like it skips everytime, when we have svg source image with missing extension https://github.com/imgproxy/imgproxy/blob/5d4a612db79f824f3acd93954f7f30c17aef6a4e/processing_handler.go#L371-L375

So, everytime, when I have svg source, I need to add any extension, just to force this feature with detection. For example
https://example.com/image `returns svg image`
https://example.com/image@jpeg `returns in respect of accept header, webp or avif`

Could you please explain to me, why it works like this? Is there any problem with conversion svg?

**Comment by DarthSim** [comment]
Hey @Frezyy123!

SVGs are not rasterized unless the resulting format is explicitly specified. In the vast majority of cases rasterizing SVG doesn't bring any benefit. The only case I know where it makes sense is email.

However, having a `rasterize_svg` option may be useful 🤔

**Comment by Frezyy123** [comment]
In some cases svg icon is much more easier to draw, but iOS application have troubles with svg and choose webp format (or pdf but this is really bad way :))

I will try to implement this option and bring pull request to you
Thank you
