### ISSUE TITLE
Only first 10 parameters are pulled from AWS parameter store

### ISSUE THREAD

**Issue by felixmeziere** [imgproxy/imgproxy#1252]
Hi!

I just completed the AWS SAM setup to deploy imgproxy to lambda. This setup (and your product) are genius and are going to divide our costs by gazilions, thank you so much!

One issue I'm encountering in the setup: I'm using AWS systems manager parameter store (which is the default setup of your SAM template) to store the environment variables (and share them with my local `imgproxy`) and after some debugging I realised **imgproxy only uses the first 10 parameters of the store** (I have 18 related to `imgproxy` config).

After checking [imgproxy's code](https://github.com/imgproxy/imgproxy/blob/6a96d07d5a2040273767ebff94454d7281b8cc41/config/loadenv/aws.go#L94) I can confirm that the code of imgproxy uses `GetParametersByPath` (documented [here](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParametersByPath.html)), which only returns 10 results. To get the next results, it's necessary to do another call with pagination.

Is it possible to fix this problem or should we just document it and I move to using aws secrets manager?

**Comment by DarthSim** [comment]
Hey @felixmeziere!

Thanks for the report! Fixed in the `latest` build

**Comment by felixmeziere** [comment]
You're so responsive, thanks, amazing!

**Comment by DarthSim** [comment]
It was an easy fix, no problem
