### ISSUE TITLE
Feature request: send more data to Sentry

### ISSUE THREAD

**Issue by ingria** [imgproxy/imgproxy#1255]
I suggest adding more info to Sentry reports: having additional request info and performance monitoring data would be very helpful.

#### Adding more error details

<details>this
<summary>Here's how the image download error looks like at the moment</summary>
<img src="https://github.com/imgproxy/imgproxy/assets/2178368/cdddc503-7988-465e-a7bd-488bff254f97"/>
</details>

The most painful problem is that there's no way to get the image URL from error report. You'll need to find the request URL somewhere in the issue details, copy the trailing part, cut off the extension and then decode base64 elsewhere. It would me much more convenient if we had the exact source image url in the report. Sentry SDK has [several tools](https://docs.sentry.io/platforms/go/enriching-events/) to help with that.

Adding some other details like processing options and request id could also be useful.

#### Performance monitoring

Sentry also allows to track some performance metrics ([docs](https://docs.sentry.io/product/performance/)). Adding this to imgproxy would also be useful: for example, we could detect and optimize slow image transform operations or analyze image download errors more closely.

**Comment by DarthSim** [comment]
Hey @ingria!

That's a good idea. Added request ID, processing/info options, and source image URL to error reports.

As for performance monitoring with Sentry, PRs are always welcome 😉
