### ISSUE TITLE
Resize images

### ISSUE THREAD

**Issue by zlodey321** [imgproxy/imgproxy#1256]
Version: 3.22 amd64 (image`darthsim/imgproxy` in docker)
Use: S3
Link example: https://x.x/image/rs::320:::/quality:90/plain/s3://x-x/prod/x-1900x.jpeg
Expected action: resize image 
action result:  there is no resize of image  and picture given as is , line from log:
 INFO [2024-03-05T11:02:56Z] Completed in 426.299352ms /rs::640:::/quality:90/plain/s3://x-x/prod/6579f8141950d0f33d19584f-1900x.jpeg request_id=a69e5065bd59a6739ed4c9451c5d4410 method=GET status=200 client_ip=x.x.x.x processing_options="Format: webp; Quality: 90; PreferWebP: true; EnforceWebP: true" image_url="s3://x-x/prod/6579f8141950d0f33d19584f-1900x.jpeg"
Add : in another site , it is ok and processing_options in log looks like //processing_options="Width: 828; Format: webp; Quality
: 90;// ,seems issue is here , in width

**Comment by DarthSim** [comment]
Hey @zlodey321!

It seems like you're missing the [signature](https://docs.imgproxy.net/usage/processing#signature) part of the URL, so imgproxy treats `rs::320:::` as a signature.

**Comment by DarthSim** [comment]
Please read the docs carefully:

> The signature part should always be present in a URL. If the signature check is disabled (no key/salt pairs are provided), the signature part may contain anything (for example, `unsafe` or `_`).

**Comment by zlodey321** [comment]
@DarthSim thank you!
