### ISSUE TITLE
Structured logging (JSON)

### ISSUE THREAD

**Issue by edevil** [imgproxy/imgproxy#126]
It would be great to have support for JSON structured logging.

**Comment by charlie-wasp** [comment]
@edevil hi 👋 did you started working on this feature? If not, I would like to give it a try

**Comment by edevil** [comment]
@charlie-wasp Hello! No, I haven't yet. Feel free to do it. :)

**Comment by DarthSim** [comment]
Added to v2.5.0

**Comment by Mistic92** [comment]
Hi, is there an option to change field names? For GCP Structured Logging field name should me ```message``` instead of ```msg```. Also ```level``` should be ```severity```. 

https://cloud.google.com/logging/docs/structured-logging

**Comment by DarthSim** [comment]
I don't think changing the names is a good idea as it breaks backward compatibility. It's better to add another log format for GCP.
