### ISSUE TITLE
3.23.0 causes S3 errors (works in 3.22.0)

### ISSUE THREAD

**Issue by mdmm13** [imgproxy/imgproxy#1262]
**Problem**: 3.2.3 breaks S3 loading of files from source, downgrade back to 3.2.2 resolves problem.

**Error**: 
```
ERROR   [2024-03-29T22:25:53Z] Completed in 935.689µs /unsafe/size:140:140:1:1/resizing_type:fit/sharpen:0.3/plain/s3://XXXXXX/rr/DJI_1234-Verbessert.jpg@webp  request_id=9mbu4TpqeiXXXXXXXX method=GET status=500 client_ip=XXX.XXX.XXX.XXX error="Can't download source image: Get \"s3://XXXXXX/rr/DJI_1234-Verbessert.jpg\": operation error S3: GetObject, resolve auth scheme: resolve endpoint: endpoint rule error, Custom endpoint `s3.eu-central-003.XXX.com` was not a valid URI"
```

**Debugging**: Unclear what causes this, because the only change was a "docker compose pull" to upgrade and restart, no other config changes were made. Possibly S3 dependency upgrades to `aws-sdk-go-v2`?

**Comment by DarthSim** [comment]
Hey @mdmm13!

I believe you mean `v3.23.0`, and yes, we migrated to `aws-sdk-go-v2`. I guess the problem is that your custom S3 endpoint lacks URL schema.

**Comment by mdmm13** [comment]
> Hey @mdmm13!
> 
> I believe you mean `v3.23.0`, and yes, we migrated to `aws-sdk-go-v2`. I guess the problem is that your custom S3 endpoint lacks URL schema.

Thank you for the swift reply. Correct (updated title), but what do you mean by "custom S3 endpoint lacks URL schema"? Do we have to configure the environment variables differently in 3.23 vs 3.22? I checked the changelog and wasn't aware of any breaking changes.

**Comment by DarthSim** [comment]
From the error message you've posted, I guess that you've set a custom S3 endpoint using the `IMGPROXY_S3_ENDPOINT` config. An S3 endpoint should contain a URL schema:

Bad: `example.com`
Good: `https://example.com`

It seems like `aws-sdk-go` allows providing custom endpoints without URL schema (while I believe it should not) but `aws-sdk-go-v2` requires it.

**Comment by jantomgid** [comment]
Hi @DarthSim I'm also getting issues with S3, we use AWS buckets, not custom endpoints, the same configuration works fine in version `3.22.0`

```
{"client_ip":"x.x.x.x", "error":"Can't download source image: Status: 404; operation error S3: GetObject, https response error StatusCode: 404, RequestID: xxx, HostID: xxx, NoSuchKey: ","level":"error","method":"GET","msg":"Completed in 10.264341ms /plain/resize:fit:640:640:0:sm/plain/s3://example-bucket//foo/bar/baz@jpg","request_id":"xxx","status":404,"time":"2024-05-08T08:35:06Z"}
```

I have confirmed manually that the object actually exists in the bucket.

**Comment by jantomgid** [comment]
We have found an issue, for some reason imgproxy adds two slashes after the bucket name

`example-bucket//foo`

instead of 

`example-bucket/foo`

This happens even in `v3.24.1`, but works fine in `v3.22.0`

**Comment by DarthSim** [comment]
Yeah, `aws-sdk-go-v2` seems to be more strict

**Comment by DarthSim** [comment]
I patched the `latest` build so S3 integration works more like before:

- `http://` is added to the custom endpoint if it has no scheme.
- All the leading slashes are trimmed from object keys.
