### ISSUE TITLE
Base64 encoding of local url doesn't work

### ISSUE THREAD

**Issue by semaperepelitsa** [imgproxy/imgproxy#1267]
Raw local URL works fine:

> 2024-04-07T06:31:42.478904219Z app[web.1]: INFO    [2024-04-07T06:31:42Z] Started /insecure/rs:fit:300:200:false:0/plain/local:///bb/1z/bb1ze1spscsb9huyxxb81ljsdasw  request_id=QNRcqDORB2P70t8tL7zOs method=GET client_ip="redacted"
> 2024-04-07T06:31:42.491965144Z app[web.1]: INFO    [2024-04-07T06:31:42Z] Completed in 13.050272ms /insecure/rs:fit:300:200:false:0/plain/local:///bb/1z/bb1ze1spscsb9huyxxb81ljsdasw  request_id=QNRcqDORB2P70t8tL7zOs method=GET status=200 processing_options="Width: 300; Height: 200; Format: jpeg" image_url="local:///bb/1z/bb1ze1spscsb9huyxxb81ljsdasw" client_ip="redacted"

However, encoding it in Base64 results in an error:

```
> Base64.urlsafe_encode64 "local:///bb/1z/bb1ze1spscsb9huyxxb81ljsdasw", padding: false
=> "bG9jYWw6Ly8vYmIvMXovYmIxemUxc3BzY3NiOWh1eXh4YjgxbGpzZGFzdw"
```

> 2024-04-07T06:32:06.285019134Z app[web.1]: INFO    [2024-04-07T06:32:06Z] Started /insecure/rs:fit:300:200:false:0/plain/bG9jYWw6Ly8vYmIvMXovYmIxemUxc3BzY3NiOWh1eXh4YjgxbGpzZGFzdw  request_id=QbT3mdFFjyWcJdCDCheer method=GET client_ip="redacted"
> 2024-04-07T06:32:06.285134704Z app[web.1]: ERROR   [2024-04-07T06:32:06Z] Completed in 279.042µs /insecure/rs:fit:300:200:false:0/plain/bG9jYWw6Ly8vYmIvMXovYmIxemUxc3BzY3NiOWh1eXh4YjgxbGpzZGFzdw  request_id=QbT3mdFFjyWcJdCDCheer method=GET status=404 client_ip="redacted" error="Can't download source image: Unknown scheme: "

I tried an example with encoded http URL and it worked fine:

> 2024-04-07T06:42:54.008437307Z app[web.1]: INFO    [2024-04-07T06:42:54Z] Started /insecure/rs:fill:300:400/g:sm/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL00v/TVY1Qk1tUTNabVk0/TnpZdFkyVm1ZaTAw/WkRSbUxUZ3lPREF0/WldZelpqaGxOemsx/TnpVMlhrRXlYa0Zx/Y0dkZVFYVnlOVGMz/TWpVek5USUAuanBn.jpg?  request_id=51l4tU65SqtdgESEh52vY method=GET client_ip="redacted"
> 2024-04-07T06:42:54.214166523Z app[web.1]: INFO    [2024-04-07T06:42:54Z] Completed in 205.717509ms /insecure/rs:fill:300:400/g:sm/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL00v/TVY1Qk1tUTNabVk0/TnpZdFkyVm1ZaTAw/WkRSbUxUZ3lPREF0/WldZelpqaGxOemsx/TnpVMlhrRXlYa0Zx/Y0dkZVFYVnlOVGMz/TWpVek5USUAuanBn.jpg?  request_id=51l4tU65SqtdgESEh52vY method=GET status=200 client_ip="redacted" image_url="https://m.media-amazon.com/images/M/MV5BMmQ3ZmY4NzYtY2VmYi00ZDRmLTgyODAtZWYzZjhlNzk1NzU2XkEyXkFqcGdeQXVyNTc3MjUzNTI@.jpg" processing_options="ResizingType: fill; Width: 300; Height: 400; Gravity: {Type: sm}; Format: jpeg"

Am I doing something wrong?

**Comment by DarthSim** [comment]
Hey @semaperepelitsa!

You don't need `/plain/` with base64 encoded URLs
