### ISSUE TITLE
Resizing with "fit" mode leads to blurry images in some cases

### ISSUE THREAD

**Issue by bsboris** [imgproxy/imgproxy#1268]
Hi! I believe I've stumbled upon some issue in Imgproxy logic (or maybe it's libvips logic that can be handled somehow).

So, there is source jpeg image 2560x1697px in size:  
![origin_2560x1697](https://github.com/imgproxy/imgproxy/assets/591230/bcd528ee-0576-445e-8b32-c78f92027f01)

The goal was to resize given image to 1280px in width, so I made following attempts (please, click images to view them in full size to get my point):

| Attempt No. | Imgproxy options  | Resulting image size | Result image
| - | --------------------- | ------------- | ------------- |
| 1 | `/rs:fit:1280:0:0/`       | 1280x849px  | ![wf_1280x849_fit](https://github.com/imgproxy/imgproxy/assets/591230/9ea27146-39a9-478a-ae1b-4332ae55d016) |
| 2 | `/rs:fit:1281:0:0/`        | 1281x849px  | ![wf_1281x849_fit](https://github.com/imgproxy/imgproxy/assets/591230/e701b77b-4d3c-4ca6-a628-a3a1a57132fb) |
| 3 | `/rs:fill:1280:849:0/`  | 1280x849px  | ![wf_1280x849_fill](https://github.com/imgproxy/imgproxy/assets/591230/b02d524f-94b6-4413-8a40-4dbb2776326f) |

Attempt No.1 has noticeable degradation in clarity of fine details, like hairs in a braid. Probably, this is due to odd source image height (resulting height should be 1697/2=848.5, was rounded to 849).

To confirm this "half-a-pixel" hypothesis, I made attempt No.2. Quality is much better here, no blurriness in the hair at all (the best way to compare is to open both images in adjacent browser tabs and switch between them back and forth).

But, there is more. I needed exactly 1280px in width, so I made attempt No.3 and got exactly 1280x849 and no blurriness.

So, my point is, is this possible to make options from No.1 provide result like in No.3?

**Comment by DarthSim** [comment]
Hi @bsboris!

This happened because of over-shrinking during the scale-on-load stage. I fixed this in the `latest` build:

![jpg21_no_ush](https://github.com/imgproxy/imgproxy/assets/380856/05492e7c-a887-44e4-9d0d-a847b0ebbd89)

Also, the Pro version applies an unsharp masking filter to reduce blurriness appearing after resizing:

![jpg21_ush](https://github.com/imgproxy/imgproxy/assets/380856/27010f2b-6ccd-4093-8f53-8f26165e3aeb)

**Comment by bsboris** [comment]
Hi @DarthSim,

Can confirm the fix, blurriness is gone now. Thank you!
