### ISSUE TITLE
"is not a video" error when trying to source PSD file

### ISSUE THREAD

**Issue by dbackeus** [imgproxy/imgproxy#1271]
We noticed that the logged error when trying to source a PSD file is "Can't download source image: The requested file is a video"

While what we'd actually love to see is PSD support (https://github.com/imgproxy/imgproxy/issues/378), maybe something can be done to improve this error message.

**Comment by DarthSim** [comment]
Hey @dbackeus!

This looks like a false-positive video detection. Should already be fixed in the `latest` build.

**Comment by DarthSim** [comment]
The fix is released in `v3.24.0`
