### ISSUE TITLE
Feature request: Gradient improvements

### ISSUE THREAD

**Issue by marcoreni** [imgproxy/imgproxy#1277]
Hi all,

we're experimenting with the gradient feature and we'd like to have the ability to create oblique gradients, similar to the following image

![oblique](https://github.com/imgproxy/imgproxy/assets/2797489/32540785-7776-4047-bfce-56ee29cf9390)

For these we think we may need:
- a gravity point
- to be able to set "degrees" as directions

The image attached may be created as:
- gravity: south west
- degrees: 30

**Comment by DarthSim** [comment]
Hi @marcoreni!

I'm not sure how gravity can be used to build a gradient. I believe, the ability to use degrees as direction should be pretty enough to build the gradient from your example.

**Comment by DarthSim** [comment]
> Do you think that start & stop params will be enough?

Exactly

**Comment by marcoreni** [comment]
Even better, one less parameter to handle! :)

**Comment by DarthSim** [comment]
The `latest` build allows using degrees (clockwise) as the gradient direction: https://docs.imgproxy.net/latest/usage/processing#gradient

Here's a reproduction of your example with `gr:0.8:f00:31:0.62:0.88`:

![gradient](https://github.com/imgproxy/imgproxy/assets/380856/66154a40-98ad-421d-8628-3561b4a91ea2)
