### ISSUE TITLE
Text is illegible when a PDF has non-embedded CID TrueType and no character map

### ISSUE THREAD

**Issue by swishstache** [imgproxy/imgproxy#1278]
When a PDF uses CID TrueType fonts and does not embed them and does not provide a character map, imgproxy pro is not able to produce a legible image extraction.

This is occurring with both versions 3.5.1 and 3.18.2.

I looked at the behavior from other tools and they are able to produce a legible image:
- ImageMagick 7.1.1-26
  - `convert missing_cmap.pdf -colorspace gray missing_cmap_preview.jpg`
- mutool version 1.23.9
  - `mutool convert -O colorspace=gray -F png -o missing_cmap_preview.png missing_cmap.pdf`

Below are example files. One has a character map and the other does not.

| Has CMAP | Missing CMAP |
| -- | -- |
| [has_cmap.pdf](https://github.com/imgproxy/imgproxy/files/15165367/has_cmap.pdf)<br/>![has_cmap preview](https://github.com/imgproxy/imgproxy/assets/343210/71624c9e-df2b-420e-a65f-76dc1a6829b2) | [missing_cmap.pdf](https://github.com/imgproxy/imgproxy/files/15165369/missing_cmap.pdf)<br/>![missing_cmap](https://github.com/imgproxy/imgproxy/assets/343210/244d9bae-51e2-4ddb-873d-38436a0e2d6f) |

**Comment by DarthSim** [comment]
Hey @swishstache!

I guess `convert` and `mutool` work correctly because your system has the `Trebuchet MS` font installed. If you put `Trebuchet MS` to `/usr/share/fonts` in the imgproxy's Docker image, imgproxy will render this PDF correctly.

As far as I understand, there's no way to map characters correctly without having a font or a character map.

We provide only a single font in imgproxy's distribution because this is usually enough for most users, and a full font set could weigh more than the whole imgproxy distribution.

**Comment by swishstache** [comment]
> As far as I understand, there's no way to map characters correctly without having a font or a character map.

That makes sense. I assume substitution (using Dejavu) doesn't occur because the document claims it has a mapping (the "uni" column below) but does not. WDYT?


```
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
Courier-Bold                         Type 1            WinAnsi          no  no  no       2  0
UniversLTStd45Light,Bold             CID TrueType      Identity-H       no  no  yes      5  0
TrebuchetMS,Bold                     CID TrueType      Identity-H       no  no  yes      9  0
TrebuchetMS                          CID TrueType      Identity-H       no  no  yes     13  0
```

**Comment by DarthSim** [comment]
Yeah, it seems so
