### ISSUE TITLE
Option to report source image errors

### ISSUE THREAD

**Issue by koenpunt** [imgproxy/imgproxy#1283]
Apart from reporting unexpected and download errors, it would be useful to have an option to get reports when a source image exceeds for example the "max source resolution".

Would you accept a PR for an additional option for this?

**Comment by DarthSim** [comment]
Image format and resolution checks are a part of the downloading flow, so these errors are reported if `IMGPROXY_REPORT_DOWNLOADING_ERRORS` is set to `true`.

**Comment by koenpunt** [comment]
Hm that's weird, because we're not getting those reported in sentry. The only error we've seen was one for using an invalid path.
I'll check again tomorrow.

**Comment by koenpunt** [comment]
To get back at this; what could be a cause for a "Can't download source image: Source image resolution is too big" error not being reported (to Sentry), when other errors are?

![image](https://github.com/imgproxy/imgproxy/assets/351038/905ddea2-c50b-4b61-96ba-66de9802d1f1)

**Comment by koenpunt** [comment]
Could it be because the resolution error is reported as warning instead of error?

```
{"client_ip":"x.x.x.x","error":"Can't download source image: Source image resolution is too big","message":"Completed in 55.089129ms /_/plain/tmp-koen/cloud.jpg?","method":"GET","request_id":"_QWMwXkE1T9SmXPld3dTk","severity":"warning","status":422,"time":"2024-05-19T21:11:48Z"}
```
