### ISSUE TITLE
Can't download source image: invalid JPEG format: missing SOF marker

### ISSUE THREAD

**Issue by danielwestendorf** [imgproxy/imgproxy#1286]
With a working setup, occasionally get these errors. Attached is an example image.
![image](https://github.com/imgproxy/imgproxy/assets/44478/35c2eca8-2587-4c33-a525-6051dc1b0da7)

I am running the latest version via docker sha256:1eb800357cb56808413677c22038e6664b06858ecf6e186826bbb2b667359ac3

**Comment by DarthSim** [comment]
Hey @danielwestendorf!

The file has an invalid JPEG structure: it contains two SOI markers. I should probably add a check for this so imgproxy returns a correct error message, but this won't solve the problem. Libjpeg can't open this image, so we won't be able to process it anyway.

I checked other tools: ImageMagick, Photoshop, Gimp, Google Chrome, and Firefox can't open this image either.

Here's the fixed image file without duplicating SOI marker:

![jpg3_fix](https://github.com/imgproxy/imgproxy/assets/380856/ab1fdc3a-2b6a-48a9-b5ea-2c9f03f6de48)

**Comment by danielwestendorf** [comment]
Thanks for the response! Yes, this appears to be bad input data.
