### ISSUE TITLE
Support for external IDs when using S3 with assumed roles

### ISSUE THREAD

**Issue by riyadhalnur** [imgproxy/imgproxy#1289]
Currently, `imgproxy` does not support passing in an external ID when assuming a role for S3 backends. The external ID provides an extra layer of security. The change itself is pretty straight forward. If interested, I can open a PR to add this functionality in.

**Comment by DarthSim** [comment]
Hey @riyadhalnur!

Sure, PRs are always better than issues and are always welcome 🙂

**Comment by riyadhalnur** [comment]
PR opened for this

**Comment by riyadhalnur** [comment]
Corresponding documentation PR - https://github.com/imgproxy/imgproxy-docs/pull/2
