### ISSUE TITLE
Requests to `imgproxy` randomly start timing out

### ISSUE THREAD

**Issue by Vincent-Vais** [imgproxy/imgproxy#1294]
We are running into an issue when all the requests to `imgproxy` start timing out. When testing we uncovered that after sending ~25 requests in parallel to `imgproxy` service it stops processing any new requests. Healthcheck endpoint is still returning 200, but any requests to process an image will result in the timeout. We have tried updating the `IMGPROXY_WRITE_TIMEOUT`, but after the issue was triggered any request to process any image will result in the timeout no matter the timeout value. We have looked at the CPU graph and after the issue was triggered it looks almost flat no matter how many requests we send to it - so the assumption is that it never gets to the "processing" step and gets stuck somewhere before that. We have found a [similar issue](https://github.com/imgproxy/imgproxy/issues/1014) in this repo, but looks like it is been marked as "completed".  We store images in GCS, so we tried switching from `gs://` source URLs to plain `https://storage.googleapis.com/` urls, but that did not help. We also tried some other suggestions - setting the `IMGPROXY_CLIENT_KEEP_ALIVE_TIMEOUT` to 0 and looking for existing TCP connections on port 443 . Setting `IMGPROXY_CLIENT_KEEP_ALIVE_TIMEOUT` to 0 did not have an affect and as for existing TCP connections - it looks like they get closed in a timely manner. One thing we have noticed is that after we encounter the issue all the TCP connections on port 443 (assuming they were all open by `imgproxy`) get closed immediately opposed to being gradually closed when `imgproxy` works as expected. Also after the issue is encountered no new connections are being open on the port 443 , so we think the issue might be somewhere before that? Or maybe the issue is opening them back after they got abruptly closed? After we restart the pod, `imgproxy` gets back to working normally. One last thing we have noticed, is that the issue is harder to trigger when the pod was running for a while. So for example if we first send 50 requests sequentially we would have to send more than 25 requests in parallel to trigger the issue. Sending 25 requests to a "fresh" pod would always trigger an issue. (This might be a red herring though 🤔  ).

Do you have any ideas on what could be causing this, and how we could troubleshoot this further?

We are using `imgproxy` version `3.24.0`, and here are the config values we used (the excessive timeout values were just for testing, ideally we don't want them anywhere near that high):
IMGPROXY_CONCURRENCY = 4
IMGPROXY_WRITE_TIMEOUT = 40s
IMGPROXY_READ_TIMEOUT = 30s
IMGPROXY_CLIENT_KEEP_ALIVE_TIMEOUT = 0s
IMGPROXY_KEEP_ALIVE_TIMEOUT = 0s
IMGPROXY_DOWNLOAD_TIMEOUT = 25s

**Comment by DarthSim** [comment]
You can use `features.custom.GODEBUG: "http2client=0"` for this.

If it doesn't fix the issue, you can set `GODEBUG="http2debug=1"` or `GODEBUG="http2debug=2"` to enable debug messages from HTTP2 clients.

**Comment by Vincent-Vais** [comment]
@DarthSim Thanks for the suggestions. I tried setting `http2client=0` through `features.custom.GODEBUG` - still seeing the same issue. I am going to enable debug messages tomorrow via `GODEBUG="http2debug=1"` and hopefully will get more information on why the client is seemingly getting "stuck"

**Comment by DarthSim** [comment]
Did the requests before the stuck one complete? Maybe some of them stuck somewhere else and did not release their semaphore tokens

**Comment by Vincent-Vais** [comment]
I assume they did complete, but we are missing a couple of the from DataDog dashboard. We sent 25 requests to imgproxy, and received back 25 successful responses, but only 22 of those are displayed in the DataDog dashboard, 3 are missing. We then sent another request to imgproxy and it got "stuck"

**Comment by DarthSim** [comment]
How do you send those requests? I'm trying to reproduce the issue, but I can't no matter how many requests I send

**Comment by Vincent-Vais** [comment]
Try using this command? `seq 1 {numRequests} | xargs -n1 -P10  curl {url}` - this would send `{numRequests}` in parallel

We are proxying request through another service, but the resolved URL that the service uses would be something like `{host}/insecure/gravity:fp:0.5:0.5/plain/gs:/{path_to_image}`

Also here is an image that we were testing with
![test-image](https://github.com/imgproxy/imgproxy/assets/61588369/6dda81eb-7e75-47bf-9ead-28bba1131942)

Let me know if that makes sense or you need more info :)

**Comment by Vincent-Vais** [comment]
Sorry forgot to mention important thing - we are only seeing this behavior in the cloud. Locally everything works as expected, maybe because of the differences in resources available?

**Comment by DarthSim** [comment]
Are you able to connect to the container shell (since you've mentioned pods, I believe you can)? If you send SIGQUIT to imgproxy, it should quit and print its current stack trace. Can you show me a stack trace of a stuck instance?

**Comment by Vincent-Vais** [comment]
Hm, I am not seeing any stacktrace when killing the pod (tried during the request and after receiving timeout). I have used `kill -3 1` to kill the pod and the only output I am seeing is
```
imgproxy@host:/$ command terminated with exit code 137                                                                                                                                                                  
```

Is there any other command that I could try?

**Comment by DarthSim** [comment]
You need to send SIGQUIT right to imgproxy's process. PID 1 is most probably not imgproxy.

**Comment by Vincent-Vais** [comment]
I used `top` to display all the running processes in the pod and looks like `imgproxy` is running under the PID 1? Or am I missing something here? 🤔 

![Screenshot 2024-05-29 at 3 07 32 PM](https://github.com/imgproxy/imgproxy/assets/61588369/a791cda0-6c2b-4856-afcb-5b3c08d07d2b)

**Comment by DarthSim** [comment]
I somehow was sure that `sh` should've been PID 1... But ok.

Any Go app flushes its stack trace to STDERR when receiving SIGQUIT. I'm not quite familiar with k8s but I believe it should store it somewhere.

**Comment by Vincent-Vais** [comment]
Cool, I will try to find the stack traces and get back to you. Thanks!

**Comment by Vincent-Vais** [comment]
Found the logs from `SIGQUIT`

[output.log](https://github.com/imgproxy/imgproxy/files/15491271/output.log)

**Comment by DarthSim** [comment]
Ok, this is interesting. I see 4 goroutines writing HTTP responses. Let's make a very clean experiment:

1. Run imgproxy and bring it to a stuck condition. To remove any obstacles, send all requests right from imgproxy's pod.
2. Stop sending any requests to imgproxy.
3. Check the logs. Check if all the `Started...` records have corresponding `Completed...` records. The `request_id` field will help you with this.
4. Send SIGQUIT and give me the stack trace.

**Comment by Vincent-Vais** [comment]
Thanks for taking a look at the logs! So far we have not been able to reproduce the issue when making requests from imgproxy's pod. Going to look more at it tomorrow, but the thinking is maybe the "stuck" request is not releasing the semaphor token, because it is busy trying to write a response to the connection that we have already closed? So maybe we can try adjusting the timeout value on our reverse proxy 🤔

**Comment by Said-Ait-Driss** [comment]
https://github.com/Said-Ait-Driss/resizer

**Comment by Vincent-Vais** [comment]
@DarthSim Thanks for all your help on this. It looks like our issue was due to the incorrect handling of prematurely closed connections by the upstream proxy library. This was causing a socket on `imgproxy` side to stay open and prevented the worker from releasing the semaphore token. After applying this patch https://github.com/http-party/node-http-proxy/issues/1586 to an upstream library the issue was resolved. Thanks again for all your help and best wishes with the project!
