### ISSUE TITLE
[Feature Request] Apply an overlay over the whole image

### ISSUE THREAD

**Issue by cspeer** [imgproxy/imgproxy#1296]
Hi,

I'm looking for an option to sort of darken the whole image.
Similar services like ImageKit achieve this by overlaying the whole image with layer that can be given a color and an opacity.
To dim the image, I could then add an overlay, give it a color of #000 and an opacity et voilà.

I think it could sort of work like the existing gradient feature, except that there would be no gradient. Only the color applied evenly over the whole image with an opacity. Hope that makes sense.

Thanks a lot!

**Comment by cspeer** [comment]
Oh nice, thank you so much!
Have you got an idea when this is gonna make it into a stable release?

**Comment by DarthSim** [comment]
The "Unreleased" part of the changelog looks pretty fat already. I guess, we could make a release soon.

**Comment by cspeer** [comment]
I'm gonna close this since it's been implemented!
