### ISSUE TITLE
Source image is unreachable

### ISSUE THREAD

**Issue by schonert** [imgproxy/imgproxy#1298]
Hi there,

We have a few users who upload files with "%20" in the filename. Users upload directly via FTP and we would rather not modify files. Also files are stored in AWS S3.

I can't seem to escape, encode or find any way to make the Imgproxy find the actual file.

An example of a filename:
`3js%205-something-something.jpg`

✅ A direct signed s3 url will load the image `https://s3....`
❌ A signed s3 url as Imgproxy source will load the image `/plin/https://....3js%205-something-something.jpg?.....`
❌ The S3 path as Imgproxy source will not load the image `/plan/s3://3js%205-something-something.jpg`
❌ The base64 encoded S3 path as Imgproxy source will not load the image `/czM6Ly8zanMlMjA1LXNvbWV0aGluZy1zb21ldGhpbmcuanBn`

Not sure how to debug further - any suggestions?

**Comment by DarthSim** [comment]
Hey @schonert!

Thanks for the catch! I fixed the problem with the percent-encoded characters treatment in the `latest` build. However, note that imgproxy unescapes plain (not base64-encoded) source URLs, so you need to escape `%` in your source URLs (basically, replace them with `%25`).

**Comment by schonert** [comment]
@DarthSim Thanks! I missed the notification for this - appreciate you looking into this!
