### ISSUE TITLE
Font overlaps when converting SVG to JPG/PNG

### ISSUE THREAD

**Issue by kevn-m** [imgproxy/imgproxy#1300]
Hi there, 

I am having some issues with fonts overlapping in the jpg/png output when converting from an SVG:

Source SVG (might need to download to see properly):
![source-image](https://github.com/imgproxy/imgproxy/assets/79607104/64699d07-1a38-495d-8d99-a50c2c9c4a4c)

Output JPG:
![output](https://github.com/imgproxy/imgproxy/assets/79607104/48e7b014-6f90-455e-822c-9a0c4b05ffa9)

Any ideas on what might be causing this?

**Comment by DarthSim** [comment]
Hey @kevn-m!

The text in this SVG is split into spans with their own coordinated.  To be aligned properly, they need the font used in the SVG to be available in the system. imgproxy only provides a single fallback font – DejaVu. You can put the needed fonts into the `/usr/share/fonts` dir inside the imgproxy image.

**Comment by kevn-m** [comment]
Thanks for the speedy response @DarthSim 

Fantastic, this worked perfectly.
