### ISSUE TITLE
[Question] I cannot manage to get watermarks to work

### ISSUE THREAD

**Issue by nfrankel** [imgproxy/imgproxy#1301]
I'm using the OSS version.

I've configured the watermark as an environment variable. I can check that it's set to the correct value inside the container:

```
IMGPROXY_WATERMARK_URL=http://server:3000/apisix.svg
```

Now, when I'm calling imgproxy, I expect that it uses the watermark:

```
http://localhost:8080/wm:opacity:1.0/plain/http://server:3000/my.jpg
```

Even with 1.0 opacity, I cannot see the watermark on my image. What did I miss?

**Comment by DarthSim** [comment]
Hi @nfrankel!

You're missing the [signature part of the URL](https://docs.imgproxy.net/usage/processing#signature) which should present even if signature checking is disabled. In your case, imgproxy treats `wm:opacity:1.0` as a signature, not as a processing option.

Also, the option format is invalid. It should be `wm:1.0`

**Comment by nfrankel** [comment]
Indeed, it works much better 😅 Thanks for your quick feedback.

I must have missed this change, because it was not necessary in [my resize demo](https://github.com/nfrankel/resize-on-the-fly/blob/master/apisix/apisix.yml#L10-L12), which used v3.23.

**Comment by DarthSim** [comment]
In your demo, `rs:fill` is treated as a signature. You can replace it with whatever and nothing will change.

**Comment by nfrankel** [comment]
Thanks for the explanation 🙏
