### ISSUE TITLE
Force transcoding/re-encoding

### ISSUE THREAD

**Issue by akhayyat** [imgproxy/imgproxy#1303]
For security purposes, I want to force transcoding or re-encoding any image I push through imgproxy, to make sure it's a valid image, and to get rid of any appended data (if any).

1. Does imgproxy strip non-image data from the files it processes, e.g. if arbitrary non-image data is appended to the image file?
2. Does imgproxy decode-then-encode the images it processes?
3. In many steps in the processing pipeline, there are short-circuit conditions (when met, the step does nothing). In general, at the entire pipeline level, and assuming the answer to question 2 above is positive, is it possible to ensure that imgproxy always re-encodes all the images it processes?

**Comment by DarthSim** [comment]
Hey @akhayyat!

1. If you're talking about image metadata, imgproxy strips it all except the copyright data by default. If you're talking about "garbage" data at the end of the file, it is skipped during the processing.
2. imgproxy always re-encodes images unless the processing is skipped. The processing can be skipped only by using the `IMGPROXY_SKIP_PROCESSING_FORMATS` config, `skip_processing` processing option, or `raw` processing option

**Comment by akhayyat** [comment]
Thank you!
