### ISSUE TITLE
Disable source image download logs

### ISSUE THREAD

**Issue by legopin** [imgproxy/imgproxy#1304]
Is there a setting to disable the logging of source image download errors since we don't really care that the users have deleted an image and tried to access it.

# Env
Version: 3.24.1

IMGPROXY_LOG_LEVEL=warn
IMGPROXY_REPORT_DOWNLOADING_ERRORS=false

Image source from Google Cloud Storage (GCS)

# Expected
GIVEN IMGPROXY_REPORT_DOWNLOADING_ERRORS=false
WHEN accessing an image that is already deleted on GCS through imgproxy
THEN no error should be logged

# Actual
WIth above settings still has the following log:

```
{"client_ip":"xxx.xxx.xxx.xxx", "error":"Can't download source image: Get "gs://bucket/folder/path.ext": googleapi: got HTTP response code 403 with body: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>name@PROJECT.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist).</Details></Error>", "level":"error", "method":"GET", "msg":"Completed in 54.273428ms /signature/w:1440/source_url", "request_id":"yjfXDehbjafGp4jEWQ5Ct", "stack":"/app/processing_handler.go:319 main.handleProcessing.func2
/app/processing_handler.go:306 main.handleProcessing
/app/server.go:114 main.buildRouter.withCORS.func1
/app/server.go:171 main.buildRouter.withPanicHandler.func2
/app/router/router.go:156 github.com/imgproxy/imgproxy/v3/router.(*Router).ServeHTTP
/usr/local/go/src/net/http/server.go:3138 net/http.serverHandler.ServeHTTP
/usr/local/go/src/net/http/server.go:2040 net/http.(*conn).serve
/usr/local/go/src/runtime/asm_amd64.s:1696 runtime.goexit", "status":500}
```

**Comment by DarthSim** [comment]
`IMGPROXY_REPORT_DOWNLOADING_ERRORS` does nothing with the logs. This config controls if downloading errors should be reported to Sentry/Bugsnag/etc.

imgproxy logs all the requests and responses, and the error is a part of the response log record. All the log records about responses with status >= 400 have a `warning` level.

**Comment by legopin** [comment]
I see, thank you for clarifying. I'll close the issue then
