### ISSUE TITLE
Problem URL Encoded Parameters 

### ISSUE THREAD

**Issue by Jnoack331** [imgproxy/imgproxy#1305]
Hi,

is there a way for imgproxy to understand URL encoded parameters like resize for example? The Problem i have is i use a framework which url encodes the complete URL for thumbnails. I can write a Package/Patch that would disable this functionality but we still need to URL encode only the path of the image and writing patches for filtering path segments seems unnecessary hacky. The Problem is that the ":" Character gets url encoded and is not understood by imgproxy.

I searched the documentation if i can base64 the actions e.g. resize as well but that does not seem the case.
Is there a way to tell imgproxy it should url decode the action as well, or do you have any other suggestion besides call it the right way :satisfied:?

Example URL from my testing:

https://local-dev-host/unsafe/resize%3Afit%3A280%3A280%3Ano%3A0/plain/local%3A//media/8d/c1/07/1720015084/4k%20Bild%201525041.jpeg%40webp

**Comment by DarthSim** [comment]
Hey @Jnoack331!

Sorry for the delay. I see two problematic symbols:

* `@`. You can use the `format` processing option instead
* `:`. I added the [IMGPROXY_ARGUMENTS_SEPARATOR](https://docs.imgproxy.net/latest/configuration/options#IMGPROXY_ARGUMENTS_SEPARATOR) config that allows to replace it with another symbol like `,`.
