### ISSUE TITLE
All imgproxy instances become unhealthy at the same time

### ISSUE THREAD

**Issue by schonert** [imgproxy/imgproxy#1308]
Hi!

We've had quite some trouble with our Imgproxy instances the last week. For some reason all 3-4 ec2 instances, managed by beanstalk, become unhealthy at the exact same time. Digging through the logs i found an "oom" comment in the docker logs indicating they were out of memory. However there was no load in the period so there was 2gb free.

All trails end and there are no clear indications on why all imgproxy docker images shut down or restart.

We're running docker-compose in ELB with 3-4 t4g.small instances.

I'm no devops expert an I'm not sure how to best go about this. They are only running Imgproxy and the fact that they all go red the same time, for me, is odd. Also - they have been running smoothly for the last 6 months or so - nothing has changed on our end.

Have you changed anything in verifying/limiting running threads for pro users?

Our compose:

```
version: "3.9"
services:
  imgproxy:
    container_name: imgproxy
    image: us-docker.pkg.dev/imgproxy-pro/v3/imgproxy:latest-ml
    restart: always # Added to as an attempt to midigate
    deploy: # Added as an attempt to avoid OOM
      resources:
        limits:
          cpus: "2.0"
          memory: "1.5G"
        reservations:
          cpus: "1.5"
          memory: "1G"
    ports:
      - 80:8080
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
      - IMGPROXY_DOWNLOAD_TIMEOUT=30
      - IMGPROXY_ENABLE_VIDEO_THUMBNAILS=true
      - IMGPROXY_ENABLE_WEBP_DETECTION=false
      - IMGPROXY_ENFORCE_WEBP=false
      - IMGPROXY_MAX_ANIMATION_FRAMES=9999
      - IMGPROXY_MAX_SRC_RESOLUTION=500
      - IMGPROXY_NEW_RELIC_APP_NAME=Imgproxy-shared
      - IMGPROXY_NEW_RELIC_KEY=***
      - IMGPROXY_QUALITY=100
      - IMGPROXY_REPORT_DOWNLOADING_ERRORS=true
      - IMGPROXY_S3_REGION=eu-central-1
      - IMGPROXY_USE_S3=true
      - IMGPROXY_TTL=31556952
      - IMGPROXY_VIDEO_THUMBNAIL_SECOND=0
      - IMGPROXY_WRITE_TIMEOUT=30
```

**Comment by DarthSim** [comment]
Hey @schonert!

Sorry, I don't quite understand if it was imgproxy container that OOM'ed or Docker itself. And was it a single incident or a regular one? The fact that all the instances went down at the same time makes me believe that was something on the AWS side.

We changed nothing in Pro limits. The only thing that could affect RAM usage that comes to mind is that we now warm up object detection models at launch. But those models would use their memory sooner or later anyway, and we actually decreased memory consumption by ML stuff in the latest release. So this shouldn't affect a thing.

**Comment by schonert** [comment]
From the docker it indicated that the container went OOM. This was before i declared resources. Not seen the OOM since - they do, however, still regually all go red at the same time.

If nothing has changed on your side - I'll go bother someone else. Thanks for the fast response!

Also - If you have any suggestions on how to go about investigating this I'll appreciate any input.
