### ISSUE TITLE
Returns 404 for existing file in S3 bucket

### ISSUE THREAD

**Issue by andreas-venturini** [imgproxy/imgproxy#1316]
Due to legacy requirements, we need to support S3 image paths with special characters, such as the following example: `s3://BUCKETNAME/production/John_Doe #1 (Programm 1)[5].mp4.jpg` (this is an anonymized example, but all special characters have been retained).

These paths are triggering 404 errors in our Sentry error reporting. The S3 URI shows up correctly in the Sentry report so we believe this is a bug in imgproxy.

```
*ierrors.Error
Can't download source image: Status: 404; operation error S3: GetObject, https response error StatusCode: 404, RequestID: XXX, HostID: XXX=, NoSuchKey: 

/app/errorreport/sentry/sentry.go in Report at line 43
/app/errorreport/errorreport.go in Report at line 44
/app/server.go in buildRouter.withPanicHandler.func2.1 at line 154
/app/processing_handler.go in handleProcessing at line 353
/app/server.go in buildRouter.withCORS.func1 at line 113
/app/server.go in buildRouter.withPanicHandler.func2 at line 170
/app/router/router.go in (*Router).ServeHTTP at line 157
```

![image](https://github.com/user-attachments/assets/b4bb9dfa-0e3b-4ac4-8b6b-4ac3ea54c969)

![image](https://github.com/user-attachments/assets/318b4c28-a74a-4300-b1a5-31614b9c0bf5)

**Comment by DarthSim** [comment]
Hey @andreas-venturini!

Thanks for the report! The problem is in the `#` symbol which is treated by Go as the start of the fragment part of the URL. Fixed in the `latest` build.

**Comment by andreas-venturini** [comment]
Cool, thanks for the quick fix :+1:

**Comment by andreas-venturini** [comment]
confirmed this is resolved by https://github.com/imgproxy/imgproxy/releases/tag/v3.26.0
