### ISSUE TITLE
"VipsJpeg: Invalid component ID 0 in SOS" error when image resolution is bigger than Imgproxy configured limit

### ISSUE THREAD

**Issue by diegoatpitch** [imgproxy/imgproxy#1318]
Hello :wave: 

In our Imgproxy deployment we use 10000 as max resolution for images. That's by design since we have many cases of highres images that are simple and highly compressable.

For a couple of days we tested a smaller limit for max resolution.
One problem we saw is that an image a customer uploaded was triggering the error "VipsJpeg: Invalid component ID 0 in SOS", which sent us in a fix for that issue. We didn't considered the max resolution change at all.

Eventually when we reverted the value to 10000 the image processing succeed. The image was indeed bigger than the lower resolution  we were testing.

Is the error in any way correct and we can't read it the right way or is it bug?

Thanks.

**Comment by DarthSim** [comment]
Hey @diegoatpitch,

The `IMGPROXY_MAX_SRC_RESOLUTION` check happens before vips touches the image, so the error seems unrelated to it.

Could you share the image?

**Comment by diegoatpitch** [comment]
Sorry about the delay, I am waiting for the customer to send us the image. When I have an faulty image at hand I'll provide it to you.

**Comment by diegoatpitch** [comment]
Closing the issue for now. If there is any complain that I can provide more info and reproducibility, I'll re-open it.
Thanks for your time @DarthSim
