### ISSUE TITLE
Add request path to error attributes in DataDog

### ISSUE THREAD

**Issue by diegoatpitch** [imgproxy/imgproxy#1319]
I am looking for some issues with image processing, we collect logs in DataDog.

This is how warnings look like:
```
{
	"id": "",
	"content": {
		"timestamp": "",
		"tags": [],
		"service": "imgproxy",
		"message": "Completed in 20ms /_/<some-options-here>/plain/<some-path-here>",
		"attributes": {
			"method": "GET",
			"level": "warning",
			"service": "imgproxy",
			"client_ip": "",
			"source": "stdout",
			"time": "",
			"error": "Request was cancelled after 20ms",
			"request_id": "",
			"timestamp": 0,
			"status": 499
		}
	}
}
```

I'd appreciate if the URL path that is in the message was also included in the attributes. That way we  could group error together and avoid scrolling through a huge list of error with tons of duplicates.

If it's not too much to ask it could even have two new attributes, one with the entire path and another "source" with only the source part of the path. That would make it even easier and quick to spot images that are causing trouble.

Thanks.

**Comment by DarthSim** [comment]
Hey @diegoatpitch!

I believe that logs are not the right place to track errors. It's better to configure error reporting to one of the supported error trackers. imgproxy sets `Source Image URL` and `Processing Options` attributes for error reports when possible. Also, the `latest` build sets `imgproxy.source_image_url` and `imgproxy.processing_options` attributes for DataDog and New Relic traces.

**Comment by diegoatpitch** [comment]
I was on vacation and catching up with things now.
Somehow I skipped over the error tracker integration section of the documentation. I've set it up now.
I've also updated to v3.26. and can see both attributes in DataDog now.

Thanks a lot again @DarthSim
