### ISSUE TITLE
S3 Request signature does not match provided

### ISSUE THREAD

**Issue by Tam** [imgproxy/imgproxy#1324]
I'm trying to get [Serving files from Amazon S3](https://docs.imgproxy.net/image_sources/amazon_s3) working (we're currently using DigitalOcean Spaces, but the two should be interchangeable), along with signed URLs.

If I use the public CDN URL of the image everything works correctly (the url is signed and the image is transformed). But when I switch to the `s3://` URL I get this error:

```
ERROR   [2024-08-30T14:44:56Z] 
Completed in 779.915696ms /img/pWZhId0PtSjcrE5EELX0IyW2M3-vsTXXQVW5nJcLKpc/rs:fill:400:267/czM6Ly9nYWxsb3AvdXBsb2Fkcy9sb2NhbC9jMTVhNDViNS0xZDg3LTQxMzMtYjAwOC0yODdkZWFhMjc0OGYuanBn.jpg  
request_id=y8mXoAdYrfqpDWWxUbAtE
method=GET
status=404
client_ip=[...]
error="
  Can't download source image: Status: 403;
  operation error S3: GetObject,
  https response error StatusCode: 403,
  RequestID: ba88c5f4-6650-93503697,
  HostID: ,
  api error SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
"
```

I've tested with unsafe plain URL's and get the same error, so I'm guessing it's not got anything to do with the imgproxy URL signing.

I'm using the env vars `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` which I know are correct since they're also being used to upload the images to Spaces (using the AWS S3 SDK). And setting `IMGPROXY_S3_REGION` and `IMGPROXY_S3_ENDPOINT` to the correct values. (And `IMGPROXY_USE_S3` to turn it on, obviously).

Is there a way I can verify that imgproxy is seeing the environment variables correctly? I've tried setting the log mode to debug but that isn't giving me much more information.

**Comment by DarthSim** [comment]
Hey @Tam!

How do you run imgproxy and how do you set env variables?

**Comment by DarthSim** [comment]
I have just tested imgproxy with DO Spaces and everything went smoothly. Here's what I did:

- Set `AWS_REGION` to whatever. According to DO Spaces docs, it doesn't affect anything.
- Set `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to the key ID and key that I obtained from the DO dashboard.
- Set `IMGPROXY_S3_ENDPOINT` to `https://<region>.digitaloceanspaces.com`. `<region>` is the DO region the bucked is located in: `nyc3` for New York, `fra1` for Frankfurt, etc. Take note that the endpoint listed in the DO dashboard also includes the bucket name, you need to remove it.

I managed to reproduce the error you posted when I specified an invalid `AWS_SECRET_ACCESS_KEY`, so may want to double-check it.

**Comment by Tam** [comment]
@DarthSim Ah, yep, the endpoint was wrong (I forgot that elsewhere I was computing it from region and domain, and wasn't doing that for imgproxy)! Thanks for your help!
