### ISSUE TITLE
TLS Handshake Failure when Fetching Image from Remote Server

### ISSUE THREAD

**Issue by a-roomana** [imgproxy/imgproxy#1325]
Hello ImgProxy team,

I'm encountering a TLS handshake failure when ImgProxy tries to fetch an image from a remote server. The error occurs consistently for specific URLs, while others seem to work fine.

Here’s the error message:

```
Can't download source image: Get "https://Ebtekarstore.ir/host/Ebtekaar/2024/8/9944053727288.jpg": remote error: tls: handshake failure
```

Steps to Reproduce:

 ```
http://127.0.0.1:8080/preset:default/mb:1048576/rs:fit:4096:4096/aHR0cHM6Ly9FYnRla2Fyc3RvcmUuaXIvaG9zdC9FYnRla2Fhci8yMDI0LzgvOTk0NDA1MzcyNzI4OC5qcGc=.jpg
```

**Comment by DarthSim** [comment]
Hey @a-roomana!

I guess that's because the hostname contains a capital `E`, so the hostname doesn't match the one specified in the certificate and the TLS handshake fails.

**Comment by DarthSim** [comment]
On the other hand, I can't reproduce this issue with other source servers. So this may be an issue on `ebtekarstore.ir`. Anyway, changing the hostname to `ebtekarstore.ir` solves the issue.

**Comment by a-roomana** [comment]
**Thank you** @DarthSim 

Your guess was absolutely correct! The issue was indeed with the capital "E" in the hostname. Once I corrected that, the TLS handshake worked perfectly. I really appreciate your help and quick response. Thanks again for pointing me in the right direction!
