### ISSUE TITLE
Get pics from S3 directly

### ISSUE THREAD

**Issue by myl82** [imgproxy/imgproxy#1326]
Hi, 

Faced issue, can't get pics from S3, e.g.:
`https://imgproxy.mydomain.dev/insecure/resize:fill:450:250/plain/s3://stage-resizer/pic123.jpg` 

Getting error:
` Completed in 8.71687ms /insecure/resize:fill:450:250/plain/s3://stage-resizer/pic123.jpg  request_id=cb87135f60255f1f0c3c753a2120fc72 method=GET status=500 client_ip=10.0.17.122 error="Can't download source image: Get \"s3://stage-resizer/pic123.jpg\": operation error S3: GetObject, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Get \"http://stage-resizer/stage-resizer/pic123.jpg?x-id=GetObject\": dial tcp: lookup stage-resizer on 172.20.0.10:53: no such host"
/app/processing_handler.go:331 main.handleProcessing.func2
/app/processing_handler.go:318 main.handleProcessing
/app/server.go:114 main.buildRouter.withCORS.func1
/app/server.go:171 main.buildRouter.withPanicHandler.func2
/app/router/router.go:158 github.com/imgproxy/imgproxy/v3/router.(*Router).ServeHTTP
/usr/local/go/src/net/http/server.go:3138 net/http.serverHandler.ServeHTTP
/usr/local/go/src/net/http/server.go:2040 net/http.(*conn).serve
/usr/local/go/src/runtime/asm_amd64.s:1696 runtime.goexit`

Cant udnderstand, where is I'm mistake. Why it use s3 name twice in get request:
` Get \"http://stage-resizer/stage-resizer/pic123.jpg?x-id=GetObject\"`

I use imgproxy v3.25.0 in k8s with roleAssume. 
Bucket policy: `get, list, put, delete` 
`aws sts get-caller-identity` works fine and I can get image from s3 inside the pod as well with `aws s3 ls s3://stage-resizer/pic123.jpg`

Thanks in advance!

**Comment by DarthSim** [comment]
Hey @myl82!

I guess, you've set the `features.aws.s3Endpoint` value in the Helm chart to `stage-resizer`. You shouldn't set this value when using AWS S3.

**Comment by myl82** [comment]
Thanks, it helped
looks like `features.aws.s3Endpoint` need only for Minio
