### ISSUE TITLE
Handle Cookie Challenge for Redirects in ImgProxy

### ISSUE THREAD

**Issue by a-roomana** [imgproxy/imgproxy#1331]
I am encountering an issue when using ImgProxy with URLs that involve cookie-based challenges. Specifically, when a fetch request to a URL results in a redirect to the same URL, a cookie is set by the server. The fetch request then needs to be retried using the new cookie. Currently, this scenario results in an error message: "stopped after 10 redirects".

For example, trying to access the following URL raises this issue:

https://nameniko.shop/wp-content/uploads/2024/09/250082_1.jpg

While I understand that ImgProxy supports [cookie passthrough](https://github.com/imgproxy/imgproxy/pull/730), it appears that this functionality is not working correctly for URLs that involve redirects. As a result, ImgProxy fails to handle these types of requests, making it impossible to process images from such sources.

**Request:**

Please enhance ImgProxy to properly handle situations where a fetch request is redirected, and a cookie is set by the server. Specifically:

1. **Detect Redirects with Cookies**: When a fetch request encounters a redirect, detect if a cookie has been set by the server.
2. **Retry with New Cookie**: Use the newly set cookie to retry the fetch request.
3. **Limit Redirect Loops**: Ensure there is a sensible limit on the number of retries to avoid infinite loops but make sure the first few retries with new cookies are attempted.

This enhancement will significantly improve ImgProxy's compatibility with websites that use cookie-based challenges, ensuring that images can be fetched and processed correctly.

Thank you for your attention to this matter. I look forward to your response.

**Comment by a-roomana** [comment]
i solved it in [this](https://github.com/imgproxy/imgproxy/pull/1334) merge request.

@DarthSim

**Comment by DarthSim** [comment]
Solved with #1334
