### ISSUE TITLE
error code 499; request was cancelled

### ISSUE THREAD

**Issue by yohanb** [imgproxy/imgproxy#1336]
Hi!
We're rolling out `imgproxy` internally and are seeing some odd errors.  About 90% of the errors are of type:
```
WARNING [2024-09-30T18:59:34Z] Completed in 124.245776ms /unsafe/rt:fill-down/w:100/h:60/el:true/plain/s3:...  method=GET status=499 ... error="Request was cancelled after 124.237502ms"
```
After searching in this repository's issues, I found this similar issue and [your response to it](https://github.com/imgproxy/imgproxy/issues/1000#issuecomment-1276620011).  I've since tried setting `IMGPROXY_CONCURRENCY` to the pod CPU limit x2 but that hasn't changed anything.

Our pods are currently pretty inactive and I aren't being flooded with that many requests.
Any idea what could be causing this? Thanks for your help.

---
![image](https://github.com/user-attachments/assets/b7c0f563-4b98-430c-a67a-f81f74034b01)
---
![Monosnap imgproxy   New Relic 2024-09-30 15-25-58](https://github.com/user-attachments/assets/5e80758f-4a42-4231-a056-4f67d2fea344)
---
![Monosnap imgproxy   imgproxy   New Relic 2024-09-30 15-26-23](https://github.com/user-attachments/assets/73e84c42-2e11-4e8f-b8c3-ce00659deb16)

**Comment by DarthSim** [comment]
Hey @yohanb!

`Request was cancelled` means the client canceled the request before imgproxy finished processing it. This is not an error per se, but imgproxy still should respond with something and log the fact that the request was canceled.

In case of timeout, the error is `Request was timed out...` and the status code is `503`.
