### ISSUE TITLE
Support calculate Phash

### ISSUE THREAD

**Issue by 3himmers** [imgproxy/imgproxy#1338]
First of all, thank you for open-sourcing imgproxy, which is very important for our application!
Imgproxy now supports hashsum based on file data such as MD5 and sha256, it is possible to add hashsum based on image content such as phash?

**Comment by DarthSim** [comment]
Hey @3himmers!

The current use of hash sums in imgproxy is to prevent the processing of files with mismatched hash sums. Calculating a content-based hash sum requires decoding an image which is a part of the processing, so it doesn't fit the current use of hash sums.

On the other hand, adding some content-based hash to the `/info` endpoint output may be useful. However, it doesn't seem possible to add pHash support to imgproxy:

1. The original implementation has lots of dependencies that imgproxy doesn't. Adding them just for adding pHash support doesn't look reasonable.

2. The original implementation is licensed by GPLv3 and the "pHash" name is a trademark. So it doesn't seem legally possible to either use the original implementation or make our own implementation.

**Comment by 3himmers** [comment]
I see. Thanks for the reply.
