### ISSUE TITLE
Getting "Internal Error" or "Source image is unreachable" from v23.0 (using S3)

### ISSUE THREAD

**Issue by StitiFatah** [imgproxy/imgproxy#1354]
Hi, 

I'm using imgproxy without a signature and with s3 links with files stored on Blackblaze B2, my urls look like that : `https://domain.com/_/rs:fit:500:0:0:0/plain/s3://bucket_name/path/to/image.png` 

I have the following env variables set : 

```
IMGPROXY_ENABLE_WEBP_DETECTION=True
IMGPROXY_USE_S3=True
AWS_ACCESS_KEY_ID=****
AWS_SECRET_ACCESS_KEY=****
IMGPROXY_S3_REGION=us-east-005
IMGPROXY_S3_ENDPOINT=s3.us-east-005.backblazeb2.com
```

Everything works fine until v32.0 included, then it throws `Internal Error` on v23.0 and `Source image is unreachable`  from v25.0 

Any idea why it doesn't work anymore from v23.0 ? 

Thanks in advance.

**Comment by DarthSim** [comment]
Hi @StitiFatah!

It should be `IMGPROXY_S3_ENDPOINT=https://s3.us-east-005.backblazeb2.com`

**Comment by StitiFatah** [comment]
Thanks it fixed the error !
