### ISSUE TITLE
Multiple Relative URLs

### ISSUE THREAD

**Issue by stumct** [imgproxy/imgproxy#136]
I have a use case where I need to be able to support multiple relative URLs - this will enable me to stop exposing these to the public internet and route all requests through imgproxy, which will decide which backend server to route to.

This could be implemented with a map built up from an environment variable e.g.
`IMGPROXY_BASE_URL_PATHS="srv1=http://example1.com/,srv2=http://example2.com/,srv3=http://example3.com/"`

This would then translate to relative image URLs which are prefixed with the map keys e.g. `srv1/path/to/image.jpg` translates to `http://example1.com/path/to/image.jpg`
`srv2/path/to/image.jpg` translates to `http://example2.com/path/to/image.jpg`

Something like this could then be implemented in the function `decodePlainURL` with code similar to 
```
	var fullURL string
	if len(conf.BaseURLPaths) > 0 {
		imageURLParts := strings.Split(urlParts[0], "/")
		if len(imageURLParts) < 2 {
			return "", "", errInvalidRelativeURL
		}
		baseURLPath, exists := conf.BaseURLPaths[imageURLParts[0]]
		if !exists {
			return "", "", errInvalidRelativeURL
		}
		fullURL = fmt.Sprintf("%s%s", baseURLPath, strings.Join(imageURLParts[1:], "/"))
	} else {
		fullURL = fmt.Sprintf("%s%s", conf.BaseURL, urlParts[0])
	}
`

I am happy to provide a PR for the work, assuming we can agree on the details.

**Comment by DarthSim** [comment]
Hi,

The feature looks good, I'd like to take a look at a PR. A few notes here:

1. Don't like `BaseURLPaths` name. Let's name is just `BaseURLs`.
2. Since URL completion logic becomes complex, it makes sense to extract it to a function and use one in `decodePlainURL` and `decodeBase64URL`.
3. `strings.HasPrefix` + `strings.Replace` solution is twice faster than `strings.Split` + `strings.Join`.

**Comment by igkuz** [comment]
any update on this? It would be nice to work with multiple urls from 1 instance. But I'm not sure what is the best way to implement this.

**Comment by shinsenter** [comment]
@igkuz the setup in #714 may help

**Comment by DarthSim** [comment]
You can do this with `IMGPROXY_URL_REPLACEMENTS` https://docs.imgproxy.net/configuration?id=source-image-urls
