### ISSUE TITLE
libimagequant support for smaller .png output?

### ISSUE THREAD

**Issue by russelgal** [imgproxy/imgproxy#137]
https://pngquant.org/lib/
https://github.com/ultimate-guitar/go-imagequant

**Comment by DarthSim** [comment]
Hi,
If your libvips is built with libimagequant support, you can enable PNG quantization in v2.2.10 with `IMGPROXY_PNG_QUANTIZE` and set max palette size with `IMGPROXY_PNG_QUANTIZATION_COLORS`. Official Docker image includes libimagequant.
