### ISSUE TITLE
Sentry reporting optimization: 404's *ierrors.Error

### ISSUE THREAD

**Issue by swistaczek** [imgproxy/imgproxy#1378]
Hey @DarthSim,
We have observed that imgproxy has been frequently reporting 404 errors to Sentry, which depletes our quota and raises reporting costs. Could I request that you handle 404 errors as expected instead of reporting them as crashes?

<img width="1339" alt="Screenshot 2024-11-12 at 09 34 27" src="https://github.com/user-attachments/assets/760be48e-b8a5-43b1-8f26-26358df08751">

**Comment by DarthSim** [comment]
Hey @swistaczek!

You can set `IMGPROXY_REPORT_DOWNLOADING_ERRORS=false`
