### ISSUE TITLE
Watermark from URL

### ISSUE THREAD

**Issue by matclayton** [imgproxy/imgproxy#138]
We have a requirement to have different watermarks on different images. It would be very useful to make the watermark configurable from the URL structure and not an ENV variable.

Further to this, it would also be ideal if this could be loaded from the Google Storage/S3 backends, I need to confirm if this is possible at present, but thought I would log it now incase it isn't

**Comment by DarthSim** [comment]
This feature was already released in the pro version and won't be the part of the OSS version
