### ISSUE TITLE
404 for existing file in S3 bucket (filename with %)

### ISSUE THREAD

**Issue by scrazy77** [imgproxy/imgproxy#1396]
file in S3:
s3://bucket/1732673088_test%image.jpg.jpeg

imgproxy url:
/insecure/plain/s3://bucket/1732673088_test%25image.jpg.jpeg

INFO    [2024-11-27T02:06:54Z] Started /insecure/plain/s3://bucket/1732673088_test%25image.jpg.jpeg  request_id=pSIi3lfj597JxUlKxRWST method=GET client_ip=
ERROR   [2024-11-27T02:06:54Z] Completed in 168.621µs /insecure/plain/s3://bucket/1732673088_test%25image.jpg.jpeg  request_id=pSIi3lfj597JxUlKxRWST method=GET status=404 client_ip= error="Can't download source image: parse \"s3://bucket/1732673088_test%image.jpg.jpeg\": invalid URL escape \"%im\""

This only happened when filename contains "%"

**Comment by Kemel91** [comment]
> file in S3: s3://bucket/1732673088_test%image.jpg.jpeg
> 
> imgproxy url: /insecure/plain/s3://bucket/1732673088_test%25image.jpg.jpeg
> 
> INFO [2024-11-27T02:06:54Z] Started /insecure/plain/s3://bucket/1732673088_test%25image.jpg.jpeg request_id=pSIi3lfj597JxUlKxRWST method=GET client_ip= ERROR [2024-11-27T02:06:54Z] Completed in 168.621µs /insecure/plain/s3://bucket/1732673088_test%25image.jpg.jpeg request_id=pSIi3lfj597JxUlKxRWST method=GET status=404 client_ip= error="Can't download source image: parse "s3://bucket/1732673088_test%image.jpg.jpeg": invalid URL escape "%im""
> 
> This only happened when filename contains "%"

We also encountered this error, the extension should be jpg instead of jpeg

**Comment by DarthSim** [comment]
Hey @scrazy77,

Thanks for the report! Fixed in the `latest` build.

**Comment by scrazy77** [comment]
Hi @DarthSim :
I can confirm this bug fixed in latest build.
Thanks for help!
