### ISSUE TITLE
Is it possible to compile Imgproxy to wasm?

### ISSUE THREAD

**Issue by ambrt** [imgproxy/imgproxy#1398]
I'm looking for a way to host Imgproxy at the Edge and wasm is one option (or Rust).
I haven't coded in golang so i got question, is it possible to compile it to wasm?

**Comment by DarthSim** [comment]
Hey @ambrt!
While you can write WASM apps in Go, it's hardly possible to compile imgproxy to WASM. There are lots of reasons for that: external dependencies, IO operations (which are very tricky in WASM), etc.
