### ISSUE TITLE
Adding HEIC support

### ISSUE THREAD

**Issue by daneren2005** [imgproxy/imgproxy#140]
We have users that are wanting to be able to use .HEIC files.  Most edge case image formats we are able to just tell users no, but since Apple has thrown their weight being heic files it is becoming more difficult.  iOS 11 saves everything in this format I believe.

It looks like libvips just added support very recently: https://github.com/libvips/libvips/issues/671.  It is now in the latest version 8.8.0: https://github.com/libvips/libvips/blob/1a836052385c220ad32f9ce0c9a3363f1f919ad6/ChangeLog#L26.  Are you able to add HEIC files to the list of supported source files?

**Comment by DarthSim** [comment]
I have successfully implemented HEIF config decoder (need one for a format detection and dimensions checking). As soon as libvips 8.8.0 is released imgproxy will get HEIC support.

**Comment by daneren2005** [comment]
Ack I didn't realize 8.8 wasn't already out.  Well thank you I look forward to that being added!

**Comment by DarthSim** [comment]
HI,

v2.3 includes HEIC support. Note that imgproxy converts HEIC to JPEG by default since web browsers do not support it yet. You can save images to HEIC by explicitly specifying `heic` format.

**Comment by daneren2005** [comment]
Sweet that sounds like what I wanted anyways.  Thank you for all you do with this project it is awesome!

**Comment by jakenuts** [comment]
Has HEIC support been restored? The docs and recent commits seem to suggest so, but when I reference an HEIC image I get 503 errors.
