### ISSUE TITLE
Issue with JXL Support in Latest Docker Image

### ISSUE THREAD

**Issue by HansVanEijsden** [imgproxy/imgproxy#1409]
Hi,

Thank you for implementing JXL support in the latest Docker image! Unfortunately, I’m having trouble getting it to work, even though WebP and AVIF formats work perfectly.

Here’s what I’m doing, just a random image from one of my servers with the latest Docker-imgproxy:
`curl -I "https://1zwolle.nl/static/img/2023/11/foto-marslanden-2022-fotograaf-john-davids_1699340828@2x.jpg" --header 'Accept: image/jxl'`

However, I receive the following error in the logs:
`2024-12-09T18:01:16.666576180Z WARNING [2024-12-09T18:01:16Z] Completed in 61.314µs /1zwolle.nl/aHR0cHM6Ly8xendvbGxlLm5sL3N0YXRpYy9pbWcvMjAyMy8xMS9mb3RvLW1hcnNsYW5kZW4tMjAyMi1mb3RvZ3JhYWYtam9obi1kYXZpZHNfMTY5OTM0MDgyOEAyeC5qcGc=.jxl  request_id=Oz6Xn0I1vnpYTXMfrz2L1 method=GET status=422 client_ip=172.17.0.1 error="Resulting image format is not supported: jxl"`

Here’s what I’ve done so far to troubleshoot:

1. Pulled the latest Docker image.
2. Set IMGPROXY_AUTO_JXL to true.
3. Observed the following in the Docker logs for some web requests: `processing_options="Format: avif; PreferWebP: true; PreferAvif: true; PreferJxl: true"` (it mentions JXL but falls back to AVIF.)
4. Using Safari and/or curl I receive the `"Resulting image format is not supported: jxl"` error
5. Double-checked my Nginx configuration and mappings. .jxl is activated in the map, just like .avif and .webp.

Am I missing something? Let me know if you need additional information to diagnose the issue.

Thank you for your help and for the great work on Imgproxy!

**Comment by DarthSim** [comment]
Hey @HansVanEijsden!

My bad, I didn't update the base image. It should work fine now.

**Comment by HansVanEijsden** [comment]
> Hey @HansVanEijsden!
> 
> My bad, I didn't update the base image. It should work fine now.

That's quick! Thank you!
