### ISSUE TITLE
Support CEPH storage

### ISSUE THREAD

**Issue by badboyd** [imgproxy/imgproxy#144]
Can imgproxy support get image from CEPH ?  https://ceph.com/

**Comment by DarthSim** [comment]
It looks like Ceph has [S3-compliant API](http://docs.ceph.com/docs/master/radosgw/s3/). Did you try to use it?

**Comment by DarthSim** [comment]
CEPH support requires imgproxy to be linked with additional libraries like libcephfs and librados. I don't think this is a good idea to add an additional requirement for such an uncommon feature. I'd rather recommend using S3-compliant API.
