### ISSUE TITLE
Gamma issues during scaling

### ISSUE THREAD

**Issue by mike-hart** [imgproxy/imgproxy#145]
sRGB colorspace is non-linear. Because of this when scaling imgproxy appears to suffer all of the issues/errors noted by Eric Brasseur in his scaling algorithm/gamma blog post: http://www.ericbrasseur.org/gamma.html

docker run -p 8080:8080 -it darthsim/imgproxy:v2.2.7

//resizing_type:fill/width:256/height:64/gravity:ce/plain/http://www.ericbrasseur.org/gamma_rainbow.jpg

leads to the following:
![gamma_rainbow](https://user-images.githubusercontent.com/4129199/55007931-27c0fc80-4fd8-11e9-8503-c6ed205c0510.jpg)

Whereas it should retain its greyscale appearance as described in the article.

**Comment by DarthSim** [comment]
Hi,

Image resizing inside imgproxy is done by [libvips](https://github.com/libvips/libvips). Please address this issue to the libvips repo.

**Comment by mike-hart** [comment]
Hi again.

Yes, the resize itself is performed by vips, but you load the image before performing the resize and so are likely responsible for handling the conversion to a linear colorspace before doing the scaling (unless I misunderstand).

See https://github.com/libvips/libvips/issues/59#issuecomment-15769507 for examples of colorspace conversion. I'm not sure if there's a quick method to determine if the image you loaded was using a non-linear colorspace to start with.

https://libvips.github.io/libvips/API/current/libvips-colour.html#vips-colourspace might provide the mechanism needed to get there and back again.

**Comment by DarthSim** [comment]
Sorry for closing the issue, you're totally right.

Added conversion to linear colorspace and back to v2.2.8. Note that imgproxy does shrink-on-load for Jpeg and WebP by default. You can disable it with `IMGPROXY_DISABLE_SHRINK_ON_LOAD` config, but this will dramatically slow down resizing and increase memory usage when working with large images.
