### ISSUE TITLE
Large performance hit introduced in v2.2.8

### ISSUE THREAD

**Issue by mike-hart** [imgproxy/imgproxy#148]
Using apachebench, concurrency 4, for 200 requests on the path:  `/resize_type:fit/width:645/height:430/extend:1/gravity:ce/plain/<data-center-local-url>` on 2.2.7 yields 14.4 images/second and on 2.2.8 yields 8.7 on the same hardware. The image used is a 2.3MB 12MP JPEG.

Run as `docker run -p 8080:8080 -it darthsim/imgproxy:v2.2.8`, so no configuration outside the defaults. Attempting to run with `-e IMGPROXY_DISABLE_SHRINK_ON_LOAD=0` makes no difference, and `-e IMGPROXY_DISABLE_SHRINK_ON_LOAD=1` results in an as-expected drop due to linear colorspace use (from 8.7 to 5.5 images per second).

**Comment by DarthSim** [comment]
Hi,

Linear colorspace was used for all images in 2.2.8. Its usage is disabled by default in 2.2.10 and can be enabled with `IMGPROXY_USE_LINEAR_COLORSPACE`.

**Comment by mike-hart** [comment]
Hi, sorry, I guess I had misunderstood. I thought that linear colorspace was not used when shrink-on-load occurred, and that that occurred when loading JPEG or PNG?

**Comment by mike-hart** [comment]
Comparing 2.2.7 to 2.2.10 with defaults (`docker run -p 8080:8080 -it darthsim/imgproxy:v2.2.X` where X is 7 or 10 respectively) yields 21req/s on 7 and 4.5req/s on 10. Is there something else I should modify/attempt? This seems like a large regression.

**Comment by DarthSim** [comment]
Could you give me an image that you use for benchmarking? I especially tested v2.2.10 to mitigate the regression occurred in v2.2.8. Here are my results (I use a locally stored image to remove network delays):

<details>
<summary>v2.2.7</summary>

```
Document Path:          /unsigned/rs:fit:300:200/plain/local:///EM-Wallpaper-Dark-5760x3600.jpg
Document Length:        11024 bytes

Concurrency Level:      4
Time taken for tests:   27.509 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      11339000 bytes
HTML transferred:       11024000 bytes
Requests per second:    36.35 [#/sec] (mean)
Time per request:       110.035 [ms] (mean)
Time per request:       27.509 [ms] (mean, across all concurrent requests)
Transfer rate:          402.54 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       1
Processing:    76  109  16.1    107     191
Waiting:       76  109  16.0    107     191
Total:         76  110  16.1    107     191

Percentage of the requests served within a certain time (ms)
  50%    107
  66%    114
  75%    119
  80%    122
  90%    131
  95%    139
  98%    151
  99%    158
 100%    191 (longest request)
```
</details>
<details>
<summary>v2.2.10</summary>

```
Document Path:          /unsigned/rs:fit:300:200/plain/local:///EM-Wallpaper-Dark-5760x3600.jpg
Document Length:        10851 bytes

Concurrency Level:      4
Time taken for tests:   26.338 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      11166000 bytes
HTML transferred:       10851000 bytes
Requests per second:    37.97 [#/sec] (mean)
Time per request:       105.351 [ms] (mean)
Time per request:       26.338 [ms] (mean, across all concurrent requests)
Transfer rate:          414.02 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       1
Processing:    71  105  13.2    103     199
Waiting:       70  104  13.2    103     199
Total:         71  105  13.2    103     199

Percentage of the requests served within a certain time (ms)
  50%    103
  66%    109
  75%    112
  80%    114
  90%    122
  95%    129
  98%    137
  99%    141
 100%    199 (longest request)
```
</details>

As you see v2.2.10 shows even better results, but such small differences, of course, can be treated as a measurement error.

**Comment by mike-hart** [comment]
![249bca73b03595e88b702de9388b11c551e1e44b](https://user-images.githubusercontent.com/4129199/55719691-bb41f680-59f6-11e9-8da6-a2ca18992fe1.jpg)

**Comment by mike-hart** [comment]
I thought it could have been a regression on the http component, so I ran it with a local volume, with the same outcome:
`docker run -p 8080:8080 -e IMGPROXY_LOCAL_FILESYSTEM_ROOT=/images -v $HOME:/images:ro -it darthsim/imgproxy:v2.2.{7,10}`

2.2.7 is ~25/sec
2.2.10 is ~4.5/sec

**Comment by DarthSim** [comment]
Ah, now I see. v2.2.8 and v2.2.9 include fixes of processing images with embedded ICC. imgproxy imports ICC while processing the image, there are a lot of reasons to do so: 

- This optimizes the resulting size by removing the ICC profile and other metadata from the image;
- Allows getting proper results when saving to formats that don't support ICC, ones like Gif;
- Resolves situations when resulting format doesn't support ICC profile from the source image. For example, converting a Jpeg image to PNG fails with some embedded profiles;
- Watermark colors will also be changed if we keep ICC profile embedded. 

In v2.2.11 I optimized ICC import by doing it after resize if linear colorspace is not used. This doesn't give us the speed of v2.2.7 back but shows much better performance than in v2.2.9.

**Comment by mike-hart** [comment]
2.2.11 improves matters (from 4.5/s to 12.5/s), thank you.

Enabling linear-colorspace causes it to drop back to 4.4/s.

However, disabling resize-on-load seems to have no effect (setting it to false when starting the docker container). There's no difference between `-e IMGPROXY_DISABLE_SHRINK_ON_LOAD=false` and `-e IMGPROXY_DISABLE_SHRINK_ON_LOAD=true` for me. Is this expected? Is there something else I need to change to have this work (or not)? Because it sounds like it's running without shrink-on-load for me always (otherwise linear-colorspace would have no effect on JPEG, if I understand correctly).

**Comment by DarthSim** [comment]
Latest releases don't import `sRGB IEC61966-2.1` profile is linear colorspace is not used. This should give us the same speed as `2.2.7` for most of the images.

Think we can close this now, can we?

**Comment by mike-hart** [comment]
Yes, thank you.
