### ISSUE TITLE
Image placeholder

### ISSUE THREAD

**Issue by jamillosantos** [imgproxy/imgproxy#149]
Hello, I am planning to use the imgproxy in our one of our products but I am missing (at least I could not find it) a feature: a placeholder for not found images (or "errored").

What are your thoughts about it?

**Comment by DarthSim** [comment]
Hi,

If you mean to respond with unprocessed placeholder image on an error, it can be implemented with nginx. Something like this:

```
error_page 404 422 500 = @placeholder;

location @placeholder {
  return 302 http://exampple.com/placeholder.png;
}
```
