### ISSUE TITLE
Invalid URL error if resize optional arguments are omitted in plain mode

### ISSUE THREAD

**Issue by ajsharp** [imgproxy/imgproxy#150]
In the [resize section](https://github.com/imgproxy/imgproxy/blob/master/docs/generating_the_url_advanced.md#resize) of the docs it states "All arguments are optional and can be omited to use their default values".

I specified resize, resize type, width and height, and it returns an error: `http://imgprxy.vinvin.co/resize/fit/100/100/plain/s3://vinvin-assets-prod/boxed-water-is-better-1464049-unsplash.jpg`.

If i specify all options, it works correctly: `http://imgprxy.vinvin.co/resize/fit/100/100/no/0/plain/s3://vinvin-assets-prod/boxed-water-is-better-1464049-unsplash.jpg`.

Am I doing something wrong, or are the docs out of date?

**Comment by DarthSim** [comment]
Hi, 
You are referring to the advanced URL format docs while using the basic one. Basic URL format requires all options to be specified.

If there is any chance you're using Ruby, you can use [the official imgproxy gem](https://github.com/imgproxy/imgproxy.rb) for URL generation.
