### ISSUE TITLE
Error resizing image: icc_import: no input profile

### ISSUE THREAD

**Issue by msdinit** [imgproxy/imgproxy#151]
Resizing the attached image fails with `icc_import: no input profile`.

The image:
https://storage.googleapis.com/misc-testing-196621.appspot.com/img.jpeg

The url I use for resizing on the local container:
http://127.0.0.1:8080/insecure/fit/400/400/no/0/plain/https://storage.googleapis.com/misc-testing-196621.appspot.com/img.jpeg

I unfortunately don't know enough about vips to debug issue myself any further, but it looks like if I ignore error returned by `C.vips_icc_import_go`, image resizes fine, ie change this to return nil
https://github.com/imgproxy/imgproxy/blob/master/process.go#L883

**Comment by DarthSim** [comment]
Hi,

Looks like embedded ICC profile of this image incompatible with the image. v2.2.12 ignores failed ICC imports.

**Comment by msdinit** [comment]
Awesome, thanks for the fast response!
Closing the issue as resolved by 253eae70abbd5c533b8e3396d38195b757a7591d
