### ISSUE TITLE
Ability to auto select fit/fill based on resize aspect ratio compared to image aspect ratio

### ISSUE THREAD

**Issue by mike-hart** [imgproxy/imgproxy#154]
I have a set list of image sizes to scale to, all of which are landscape. When resizing a landscape image it's then fine if bits of the left and right of the image are cropped (if the image's aspect ratio is slightly wider).

However, if resizing a portrait image (say, one taken with a phone held vertically) then the image is much more aggressively cropped since the `fill` will be a landscape rectangle in the middle of the image.

Would there be a way to have the resizer choose fit over fill if the orientation differs from the resize aspect?

**Comment by DarthSim** [comment]
Hi,
v2.3 includes support of `resizing_type:auto`.

**Comment by mike-hart** [comment]
Thank you very much for this!
