### ISSUE TITLE
SVG and supported fonts

### ISSUE THREAD

**Issue by amir20** [imgproxy/imgproxy#157]
I have been trying to use the SVG -> PNG conversion. It seems like something is not installed correctly in the docker image for the fonts to work. 

Here is my original SVG:

<img width="604" alt="Screen Shot 2019-05-01 at 7 43 55 AM" src="https://user-images.githubusercontent.com/260667/57022756-e62dfd80-6be4-11e9-9302-4cb78f4ca18f.png">

Here is that same SVG in JPEG format:

<img width="601" alt="Screen Shot 2019-05-01 at 7 44 15 AM" src="https://user-images.githubusercontent.com/260667/57022788-065dbc80-6be5-11e9-9eba-21da45e4dd34.png">

Fonts are all broken. I have played around with CairoSVG and I remember true fonts had to be installed. Has this been an issue for anyone else? 

If you point me to the right direction, I can provide a PR. 

PS. This is an amazing project. I have been looking for something like this for a long time! The webp auto detection is the best.

**Comment by amir20** [comment]
I think `fontconfig` needs to be installed correctly. https://github.com/mkoppanen/resty-imaging/blob/master/Dockerfile#L14-L51

I can try this tonight.

**Comment by DarthSim** [comment]
Hi,

Fonts in SVG is not a quite common thing. I don't think most of the users need this feature, especially when it adds 40 MB to the image. Ones who need the feature can just build their own image based on `darthsim/imgproxy`. Thanks for workaround though 👍.
