### ISSUE TITLE
Possible incorrect handling of orientation (not sure if bad image/apple-special, or imgproxy)

### ISSUE THREAD

**Issue by mike-hart** [imgproxy/imgproxy#160]
Some images, though they have an orientation EXIF tag set, do not get orientation corrected on resize.

I'm not sure if this is a problem with the image itself, or if there's something that needs looking into here.

The attached original image (click through, because weirdly the github resize renders right-way-up) renders upside down on Linux Firefox, Linux Slack, Linux Chrome, and Windows Chrome. Not sure about Apple.

![2728_property_2019_05_01_08_57_17_984134](https://user-images.githubusercontent.com/4129199/57836079-e0751200-77b7-11e9-83e1-2d548317ad8b.JPG)

**Comment by DarthSim** [comment]
Hi,

It's the image problem. The image pixels are oriented correctly, but its `exif-ifd0-Orientation` header is set to 3, which means it's rotated 180 degrees. Every single application I've tried shows the image upside down.

The reason why Chrome shows one correctly right here is that it doesn't respect  `exif-ifd0-Orientation` header for `img` tags: https://stackoverflow.com/questions/42401203/chrome-image-exif-orienation-issue

**Comment by mike-hart** [comment]
Thank you. That's... frustrating (since people who upload images with this particular issue would complain), but makes sense.

**Comment by DarthSim** [comment]
Well, maybe it makes sense to add a config option to disable autorotation. If you have more images with incorrect `exif-ifd0-Orientation` than with correct ones, the option will help you a little.

**Comment by mike-hart** [comment]
An interesting thought. I guess I'll need to go over the catalogue to find imges with an orientation set and judge which would affect more users.

Thanks.
