### ISSUE TITLE
Query string parameters on health check urls

### ISSUE THREAD

**Issue by rdm** [imgproxy/imgproxy#164]
Currently, /health?label=xyz gives a 404

When running health checks from multiple places, it would be nice to be able to inspect the logs to quickly see which checks have been arriving at that instance.

**Comment by DarthSim** [comment]
Implemented in v2.3

**Comment by shadowlmd** [comment]
This doesn't work properly when IMGPROXY_PATH_PREFIX is defined. For example:
```
shadowlmd@home:~$ docker run --rm -e IMGPROXY_PATH_PREFIX=/i -d darthsim/imgproxy
ac067a0921d489332ece71caca58f09279907af3bafbdfbf0f99c5fcc5bb2f6e
```
```
shadowlmd@home:~$ docker container exec -it objective_dubinsky bash
root@ac067a0921d4:/# imgproxy health

root@ac067a0921d4:/# imgproxy health || echo fail

fail
```

**Comment by DarthSim** [comment]
@shadowlmd It's fixed in v2.17.0

**Comment by DarthSim** [comment]
Oh, sorry, I somehow thought about the info endpoint. I'll investigate this

**Comment by shadowlmd** [comment]
I just realized I commented a closed issue. Can you please reopen it or I better create a new one?

**Comment by DarthSim** [comment]
Yeah, it's better to create the new one.
Actually, it's a problem with the `health` command, not with the `/health` endpoint

**Comment by shadowlmd** [comment]
Done, https://github.com/imgproxy/imgproxy/issues/698
