### ISSUE TITLE
SO_REUSEPORT

### ISSUE THREAD

**Issue by rdm** [imgproxy/imgproxy#165]
I am not skilled with golang, or I would implement this myself:

imgproxy should support SO_REUSEPORT - this could be an option, rather than always.

What this would do is allow us to run one instance of imgproxy for each cpu, for better use of multicore cpu machines.

https://codereview.appspot.com/34580043/ suggests that the necessary support has been incorporated into the language.

**Comment by DarthSim** [comment]
Hi,

Both Go and libvips provide a good concurrency level and utilize multi-core CPUs perfectly. There is no need to run one instance per core. Actually, I don't think this is a good idea at all.

Though I think `SO_REUSEPORT` support may be a good thing for zero-downtime restart without containerization.

**Comment by DarthSim** [comment]
`darthsim/imgproxy:latest` includes `SO_REUSEPORT` support. Can be enabled with `IMGPROXY_SO_REUSEPORT=1`
