### ISSUE TITLE
The "Deploy to Heroku" button is broken

### ISSUE THREAD

**Issue by ssaunier** [imgproxy/imgproxy#170]
I just tried creating an Heroku app with the latest "Deploy to Heroku" button (which points to https://heroku.com/deploy?template=https://github.com/imgproxy/imgproxy) and it's failing with the following error:

![image](https://user-images.githubusercontent.com/414418/59639678-3db80680-915c-11e9-8c12-393f66d43c7d.png)

I also tried the former URL pointing to @DarthSim's repo (https://github.com/imgproxy/imgproxy/commit/1041056977943a6d047a4d0c72c4f8fce2302413) but got the same error.

Thanks!

**Comment by DarthSim** [comment]
Oh, thanks for pointing on this! I moved Dockerfile and totally forgot to change its path in `heroku.yml`. It works now.

**Comment by ssaunier** [comment]
Thanks for fixing it so fast 🙏 !
