### ISSUE TITLE
Constant crashes on moderate load

### ISSUE THREAD

**Issue by nolech** [imgproxy/imgproxy#171]
Hello,
I have your ImgProxy Service deployed as a container behind an application load balancer in AWS using ECS with a fleet of T3.Nano Instances (150) with each container getting 2vcpu and 0.5GB of memory. With minimal resource utilization I find that under moderate load (~100 image requests a second) the containers start failing their load balancer health checks and get set to Draining before being restarted

Any thoughts on what might be causing this? I am starting to get Prometheus and Syslogs to dig deeper but thought I would as here as well. Load tests were done with up to 3000 images per second with AB testing software with no issue, but in real world  load we are seeing this constant draining.

Environment Variables:
IMGPROXY_CONCURRENCY: 10
IMGPROXY_DOWNLOAD_BUFFER_SIZE: 1024000
IMGPROXY_ENABLE_WEBP_DETECTION: true
IMGPROXY_FREE_MEMORY_INTERVAL: 5
IMGPROXY_GZIP_BUFFER_SIZE: 1024000
IMGPROXY_MAX_ANIMATION_FRAMES: 50
IMGPROXY_S3_REGION: us-east-1
IMGPROXY_USE_S3: true
IMGPROXY_WATERMARK_DATA: Base64 Image text
IMGPROXY_WATERMARK_OPACITY: 0.5

**Comment by DarthSim** [comment]
Hi,

I think there may be an issue with keep-alive connections. Until the latest commit, imgproxy used `IMGPROXY_READ_TIMEOUT` as a keep-alive timeout. imgproxy's default read timeout value is 10 seconds, while ELB's default idle connection timeout is 60 seconds, so imgproxy may close idle connections before ELB does. When you provide a high load to imgproxy with AB or something like this, all connections are always in use and aren't treated as idle, so imgproxy doesn't close them.

The latest commit (which is already built to `darthsim/imgproxy:latest`) includes `IMGPROXY_KEEP_ALIVE_TIMEOUT` config. Try to update to the latest build and set `IMGPROXY_KEEP_ALIVE_TIMEOUT` and `IMGPROXY_READ_TIMEOUT` to a greater value than ELB's timeout. If I guessed right, this should fix the issue.

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#connection-idle-timeout

Also, I'd recommend disabling sticky sessions if you've enabled ones: https://docs.aws.amazon.com/en_us/elasticloadbalancing/latest/classic/elb-sticky-sessions.html

**Comment by nolech** [comment]
@DarthSim Thank you very much for the fast response! I will give that time out a shot. After enabling Syslogs we do see out of memory errors. We increased the mem (it was only 450MB) and it lasted longer. I believe it may also be related to a leak (maybe this one https://github.com/imgproxy/imgproxy/issues/116) So we will try that solution.
I will keep you posted.

**Comment by nolech** [comment]
@DarthSim It seems that the LD_PRELOAD did not help with my memory leak.

Do you have any other advice? 

![image](https://user-images.githubusercontent.com/6865493/60206266-5ab1a100-9810-11e9-905e-336e9e26c246.png)

**Comment by DarthSim** [comment]
It still looks like it's GLib's memory fragmentation issue. Do you use `darthsim/imgproxy` or you build your own Docker image? If you build your own, can I take a look at the Dockerfile? If you can't show me one or you don't use Docker at all, can I look at the 'ldd' result for your imgproxy binary?

And sorry, but I have to ask: did you install `jemalloc`?

**Comment by DarthSim** [comment]
Ah, I misunderstood the graph, sorry. 

`go_memstats_alloc_bytes_total` doesn't make much sense since it shows total bytes allocated even if freed. It'll constantly grow no matter what. `go_memstats_sys_bytes` is a much more interesting one. 

Also, it'd be useful to take a look at the following:

```
sum(increase(buffer_size_bytes_sum[1m])) by (type)
/
sum(increase(buffer_size_bytes_count[1m])) by (type)
```

**Comment by nolech** [comment]
@DarthSim I am running your software in AWS in containers. The EC2 instances (as part of their start up) install Jemalloc 5.2, but what is the best way to get this library to the container?  I have tried many changes and my nodes and those changes seemed to help, but i can still see the leak (over 24 hous) 
![image](https://user-images.githubusercontent.com/6865493/60397284-81215600-9b08-11e9-934a-904f8075af4e.png)

What is the best way to get the container to use this library?

**Comment by DarthSim** [comment]
I'm finally out of my vacation and ready to continue :)

Unfortunately, I'm totally not familiar to AWS containers. It would be great if you could give me a bit more explanation of how it works. Does it work with regular Docker containers? If it doesn't, what OS is used there?

It'd still great to take a look at `ldd` result and the metrics I asked for before.

Jemalloc is like a silver bullet when you dealing with Glib memory fragmentation. So I'm pretty surprised it doesn't work for you.

**Comment by nolech** [comment]
I am not on why but this system stopped showing leaks. The solution may have been to give the containers running imgproxy 1vCPU and 2GB ram instead of 0.5vCPU and 1GB and run half as many. It oesn't look like jemalloc is as easy to install on CENTOS based Amazon Linux so I do not believe this was ever installed correctly.

Either way, thanks for getting back to me.
