### ISSUE TITLE
Question: Separating server and libvips library

### ISSUE THREAD

**Issue by gunta** [imgproxy/imgproxy#174]
Hi!

I have a question: Is there a reason, performance or otherwise about why imgproxy is not using a libvips wrapper like https://github.com/h2non/bimg or https://github.com/davidbyttow/govips ?

If so, would it be possible to extract that functionality into a separate library, for the sake of separation of concerns (and getting more contributions)?

**Comment by DarthSim** [comment]
HI,

Both packages are too high level for my case. I fight for every byte and every millisecond and I have to use some hacks for it. Sometimes I need more advanced usage of libvips then those packages provide. So it was easier to bind libvips from scratch than use any package.

For the same reason, I don't see any good in extracting libvips bindings from imgproxy. Maintaining a package requires backward compatibility assurance, which I can not afford. It's much flexible for me to keep things as is.

If you just want libvips in your project, `bimg` is a good choice, h2non did a great job.

**Comment by gunta** [comment]
I see, I guess its hard to balance performance+hacks with high-levelness. Thanks!
