### ISSUE TITLE
Question: file basename customisation

### ISSUE THREAD

**Issue by markfinger** [imgproxy/imgproxy#175]
Hi,

Is it possible to append a more human usable basename to the url, to change the downloaded file name?

For example, given a url like 

`http://imgproxy.example.com/AfrOrF3gWeDA6VOlDG4TzxMv39O7MXnF4CXpKUwGqRM/fill/300/400/sm/0/plain/http://example.com/images/curiosity.jpg`

would it be possible to change it to something like

`http://imgproxy.example.com/AfrOrF3gWeDA6VOlDG4TzxMv39O7MXnF4CXpKUwGqRM/fill/300/400/sm/0/plain/<base_64_encoded_url>/<some_custom_filename.ext>`

the intention being that the user could then download the derivative and it would be saved as `some_custom_file.png`?

Our use-case is that users often download derivative images and we'd like them to automatically include all the operations (crop, resize, etc) within the name of the file. We're currently using thumbor and would only be able to achieve this with a proxy server.

Cheers,
Mark.

**Comment by DarthSim** [comment]
Added [filename](https://github.com/imgproxy/imgproxy/blob/master/docs/generating_the_url_advanced.md#filename) option to v2.4.0

**Comment by pySilver** [comment]
@DarthSim does filename can contain accent characters? I'm getting "Forbidden" response from imgproxy every time `filename` contains some non-latin characters. For instance: `Srebrne czółenka Pepe Jeans z zamszu` (if fails even if urlencoded.

**Comment by DarthSim** [comment]
Hey @pySilver!
I am very sorry for missing this. Please create a new issue so I can track it.

**Comment by pySilver** [comment]
@DarthSim sure thing, here it is https://github.com/imgproxy/imgproxy/issues/437
