### ISSUE TITLE
Overriding options from presets via url path fails sometimes

### ISSUE THREAD

**Issue by graste** [imgproxy/imgproxy#178]
I deployed imgproxy locally and defined presets via env variables. Using those presets and combining them with url base path and d/l from s3 works as expected. Further tests with overriding the options defined by a preset via url path fails from time to time when I reload a page consecutively (a few times when reloading like 20 or 30 times). My manual testing shows, that it's probably only happening, when the option from the url contradicts the preset.

Example:

I used an image that is very high (like 6:2 ratio or so) and resize it to a 4:3 ratio. Using resizing type "fill" I expected the given size constraints to be respected and get a 624x468 image. Using "fit" would give a 468px high image with e.g. 140px width. Regardless of settings the output of the same URL should always be the same.

```
IMGPROXY_PRESETS=article=resizing_type:fit/width:624/height:468/gravity:ce/enlarge:0,…
```

Always correct as expected:

- ``…/imgproxy/asdf/pr:article/plain/some/file.png@jpg``
- ``…/imgproxy/asdf/pr:article/rt:fit/plain/some/file.png@jpg``

Sometimes not as expected:

- ``…/imgproxy/asdf/pr:article/rt:fill/plain/some/file.png@jpg``
  - usually returns "fill", but sometimes uses "fit"
  -  logs show the incorrect usage of the preset's resizing type instead of the contradicting URL path one
- ``…/imgproxy/asdf/pr:article/rt:fill/g:nowe/plain/some/file.png@jpg``
  - usually gives "fill" with "nowe" gravity
  - sometimes returns "fit", sometimes "fill" w/ "center" gravity

Example log from a test of 2 tries without other traffic on that instance of imgproxy as it's a local test via browser:

```
2019/07/16 10:00:12 [f9956cc8fd7db254bc1fe56505fba52c] GET: /sqwretsdfg/pr:article/rt:fill/g:nowe/plain/some/file.png@jpg
2019/07/16 10:00:13 [f9956cc8fd7db254bc1fe56505fba52c] | 200 | Processed in 615.290979ms: s3://somebucket/some/file.png; &amp;{Resize:fill Width:624 Height:468 Dpr:1 Gravity:{Type:nowe X:0 Y:0} Enlarge:false Extend:false Crop:{Width:0 Height:0 Gravity:{Type: X:0 Y:0}} Format:jpg Quality:75 Flatten:false Background:{R:255 G:255 B:255} Blur:0 Sharpen:0 CacheBuster: Watermark:{Enabled:false Opacity:1 Replicate:false Gravity:ce OffsetX:0 OffsetY:0 Scale:0} PreferWebP:false EnforceWebP:false UsedPresets:[article]}
2019/07/16 10:00:24 [b0c68ebc085928d817ce8f2d78977bb2] GET: /sqwretsdfg/pr:article/rt:fill/g:nowe/plain/some/file.png@jpg
2019/07/16 10:00:24 [b0c68ebc085928d817ce8f2d78977bb2] | 200 | Processed in 656.938283ms: s3://somebucket/some/file.png; &amp;{Resize:fit Width:624 Height:468 Dpr:1 Gravity:{Type:ce X:0 Y:0} Enlarge:false Extend:false Crop:{Width:0 Height:0 Gravity:{Type: X:0 Y:0}} Format:jpeg Quality:75 Flatten:false Background:{R:255 G:255 B:255} Blur:0 Sharpen:0 CacheBuster: Watermark:{Enabled:false Opacity:1 Replicate:false Gravity:ce OffsetX:0 OffsetY:0 Scale:0} PreferWebP:false EnforceWebP:false UsedPresets:[article]}
```

First I thought race condition due to slow local machine, but the above log excerpt shows a wrong option being used over 10 seconds later...so might be some reusing issue.

**Comment by DarthSim** [comment]
HI,

Thanks for catching this. Fixed in the master and the `latest` image

**Comment by graste** [comment]
Thank you for your effort!
