### ISSUE TITLE
Corrupted colors in JPEG images

### ISSUE THREAD

**Issue by kemko** [imgproxy/imgproxy#182]
Hello.

Our client has uploaded an image that colors changed after resizing via imgproxy. This issue is reproduced both the master branch and 2.3.0 version.

The first image is an original and the second one is a resized copy.

![image](https://user-images.githubusercontent.com/767743/61727662-698e6380-ad7c-11e9-8cfd-463749ced4ee.png)

![image](https://user-images.githubusercontent.com/767743/61728085-2b457400-ad7d-11e9-9945-32c03018a92a.png)

**Comment by DarthSim** [comment]
Hi,

I can't reproduce the bug with the attached image.

It looks like GitHub processes them somehow since both attached images are PNG, not JPEG. Could you upload the original one somewhere else?

**Comment by kemko** [comment]
Shure.

[original](https://static-eu.insales.ru/images/products/1/3907/234016579/large_Photo_1562256207450.jpg)
[after resize](https://static-eu.insales.ru/r/vPkgXLmYMxE/fit/400/400/ce/1/plain/images/products/1/3907/234016579/large_Photo_1562256207450.jpg)

**Comment by DarthSim** [comment]
Thanks!

The original image is CMYK one without an embedded ICC profile. CMYK images are converted to RGB to be displayed or processed by imgproxy. To be converted correctly, an image needs a color profile (ICC). When an image doesn't have one, tools use some default one. Of course, those default profiles may be different. For example, that's how Preview from macOS shows the provided image:

![](http://img.darthsim.me/UmPrh4Va3H.png)

And that's how it's shown in Photoshop:

![](http://img.darthsim.me/v-soqi1XS2.png)

How you can see, results differ a lot. This is not an imgproxy issue, but the image's one.
