### ISSUE TITLE
how to build to binary for ubuntu

### ISSUE THREAD

**Issue by goldalworming** [imgproxy/imgproxy#184]
How do I build imgproxy for ubuntu server and run it?

**Comment by DarthSim** [comment]
HI,

The [installation manual](https://github.com/imgproxy/imgproxy/blob/master/docs/installation.md#ubuntu) describes how to build it for Ubuntu. The only dependencies are Go and libvips. If you have them in your system, there should be no problem building imgproxy.

Unfortunately, there is no plug-and-play .deb yet, but we're working on it.

**Comment by goldalworming** [comment]
this is the return of go run main.go
# command-line-arguments
./main.go:20:2: undefined: initLog
./main.go:21:2: undefined: configure
./main.go:22:2: undefined: initNewrelic
./main.go:23:2: undefined: initPrometheus
./main.go:24:2: undefined: initDownloading
./main.go:25:2: undefined: initErrorsReporting
./main.go:26:2: undefined: initVips
./main.go:35:37: undefined: conf
./main.go:41:5: undefined: logDebug
./main.go:46:7: undefined: startServer
./main.go:46:7: too many errors

**Comment by DarthSim** [comment]
Please follow the installation guide.

You're running a single file while there are many ones, that's why it doesn't work.

**Comment by goldalworming** [comment]
you should add this in installation guide for compiling imgproxy

sudo CGO_LDFLAGS_ALLOW="-s|-w" go build -v -o /usr/local/bin/imgproxy

**Comment by DarthSim** [comment]
Instructions from the installation guide work fine. You don't need `go build` if you install imgproxy with `go get`
