### ISSUE TITLE
Gif optimization support

### ISSUE THREAD

**Issue by dfarinapb** [imgproxy/imgproxy#186]
When a gif is saved using optimization it only stores partial updates to the image on the next frame. Imgproxy will only display the changes and does not combine the frames, making most of the image go transparent.  Ideally, it should display the same as the unoptimized image.  I tested with Gimp though I think many image editors support optimizing gifs.

**Comment by DarthSim** [comment]
Hi,

Love the idea, but we strongly depend on the way libvips works with ImageMagick. I made a PR with support of GIF optimizations, let's see how it'll go https://github.com/libvips/libvips/pull/1385

**Comment by DarthSim** [comment]
PR to libvips is merged, let's wait for the next release.

**Comment by DarthSim** [comment]
The feature was released in the pro version of v2.10.0
