### ISSUE TITLE
All logs are outputted in standard error

### ISSUE THREAD

**Issue by allanpope** [imgproxy/imgproxy#187]
All logs are being outputted to standard error.
An example is the health check:

```
{	
  line: GET: /health	
  source:	stderr	
  tag: ...
}
```

Any ideas on how to fix this? 

Thanks

**Comment by DarthSim** [comment]
Hi,

This is the default Go behavior. Made logs to be written to STDOUT in the latest build.

**Comment by allanpope** [comment]
Awesome, thanks for doing that so quickly.
