### ISSUE TITLE
Support for logging only unhandled errors in Sentry

### ISSUE THREAD

**Issue by jasmine-q** [imgproxy/imgproxy#192]
I'm using the sentry setup as described here: https://github.com/imgproxy/imgproxy/blob/master/docs/configuration.md#error-reporting

By default all errors are being sent to sentry which included handled exceptions like `invalid path`.
It also looks like all the errors go under the same issue because it's the same exception `*main.imgproxyErrormain.reportError`. Please see the screenshot below for an example:

![Screen Shot 2019-08-14 at 10 40 48 am](https://user-images.githubusercontent.com/4547632/62986751-5a349e80-be80-11e9-81bf-a3350dbcc7af.png)

Is it possible to only send through unhandled exceptions to sentry? I'm looking to log things like 500 errors

**Comment by DarthSim** [comment]
Hi,

This makes sense. v2.4.0 reports only unexpected errors like processing errors or downloading errors.

**Comment by jasmine-q** [comment]
> Hi,
> 
> This makes sense. v2.4.0 reports only unexpected errors like processing errors or downloading errors.

Hi,

Thanks for your work.
Most of the errors in sentry are now gone but I am still getting `Unknown asset` errors reported through to Sentry.

**Comment by DarthSim** [comment]
It should be `Unknown preset`, actually :) But anyway, it shouldn't be reported, and I can't reproduce the issue. Are you sure that you don't have any instances of an older version that report to Sentry?

**Comment by jasmine-q** [comment]
We're not getting the issue anymore after using the latest version of imgproxy so I'm going to close this issue.
Thanks again for the fix :)
