### ISSUE TITLE
Request: Adding the invalid path or url to errors when they are logged

### ISSUE THREAD

**Issue by allanpope** [imgproxy/imgproxy#197]
Currently when an `Invalid image url` or `Invalid path` error is thrown the url or path is not logged.

Could we please log it? It would help to debug potential issues faster. 
Right now you are doing something similar with other errors eg: Unknown asset, which raises the error and logs the unknown preset. `return fmt.Errorf("Unknown asset: %s", preset)`

Currently this is what you see when a `invalid path` error occurs.
![Screen Shot 2019-08-26 at 10 26 03 am](https://user-images.githubusercontent.com/2561365/63658370-60fed200-c7ed-11e9-876b-5f7bd19fc39d.jpg)

**Comment by DarthSim** [comment]
Hi,

Made path and URL parsing errors more verbose in v2.4.1

**Comment by allanpope** [comment]
Awesome! thanks
