### ISSUE TITLE
Transparent background and Watermark

### ISSUE THREAD

**Issue by dfarinapb** [imgproxy/imgproxy#199]
Since the Watermark Opacity is always multiplied by the opacity of the image a transparent background will cause it to not appear even if set to 1.  Is it possible to ignore the opacity of the image instead, and only use IMGPROXY_WATERMARK_OPACITY.

**Comment by DarthSim** [comment]
Hi,

This makes sense. `v2.5.0` does watermarking properly.

**Comment by dfarinapb** [comment]
Thanks
