### ISSUE TITLE
Resize without Cropping

### ISSUE THREAD

**Issue by fionera** [imgproxy/imgproxy#201]
Hi,

is it possible to resize an image without cropping it? Like the max-width/height parameter in CSS?

**Comment by DarthSim** [comment]
Hi,

imgproxy uses `fit` resizing type by default. This type doesn't do the cropping and fits the result to the provided boundaries.

**Comment by fionera** [comment]
Yes but that will fill the pixels that are not covered by the images with the background. What I mean is that it returns an image that retains the ratio... Sorry I cant really describe it ^^

**Comment by DarthSim** [comment]
If you could provide an example of a source and the expected result, it'd help us to understand each other :)

**Comment by fionera** [comment]
The Original Image is 732x540 Pixels. Then I want the Thumbnail of it without any crop with 600x600 Pixels. But since the source is not quadratic it will be 600x443 Pixels because we dont want crop and also no background color.

https://www.shopwaredemo.de/media/image/8c/23/99/SW10078.jpg
https://www.shopwaredemo.de/media/image/bd/29/e0/SW10078_2_600x600.jpg

**Comment by DarthSim** [comment]
> The Original Image is 732x540 Pixels. Then I want the Thumbnail of it without any crop with 600x600 Pixels. But since the source is not quadratic it will be 600x443 Pixels because we dont want crop and also no background color.

That's exactly what imgproxy does by default.

But the provided result is cropped.

**Comment by fionera** [comment]
Oh wait. I am an Idiot and provided wrong Images... These have what I mean :)
https://www.ostermann.de/media/image/0127888.jpg
https://www.ostermann.de/media/image/thumbnail/0127888_720x600.jpg

**Comment by DarthSim** [comment]
Still looks like what imgproxy does by default

**Comment by fionera** [comment]
Ohhhhh I just saw that rs:auto doesnt use fit, nevermind
