### ISSUE TITLE
Javascript example for browser

### ISSUE THREAD

**Issue by volyx** [imgproxy/imgproxy#204]
Now there is only javascript example, that works inside nodejs environment(https://github.com/imgproxy/imgproxy/blob/master/examples/signature.js) due to module 'crypto'.

It would be good to have reference example for usage in browser

**Comment by DarthSim** [comment]
Hi,

I'd not recommend signing URLs on the client-side since you'll leak your keys to the world. But https://github.com/imgproxy/imgproxy/pull/200 makes the example work with browsers anyway.
