### ISSUE TITLE
Switch/config to disable Sentry logging of 4xx errors

### ISSUE THREAD

**Issue by mike-hart** [imgproxy/imgproxy#208]
At present if serving from S3 via http there will be a Sentry error reported for every 403. The problem is that this will include valid exclusions (things marked publicly inaccessible/unreadable). Without adding the ability for the public user to list the S3 bucket we will also get this for anything which should be considered a 404.

We have maybe 20,000 of these per day which is a significant hit on Sentry and not hugely useful to us to know (we could track invalid accesses via cloudwatch logs for example).

Is there a way (or could there be one) to avoid reporting to Sentry on this as it's not a failure of the program or an alert of interest.

**Comment by DarthSim** [comment]
Added `IMGPROXY_REPORT_DOWNLOADING_ERRORS` config to [2.6.0](https://github.com/imgproxy/imgproxy/releases/tag/v2.6.0). Setting it to `false` disables reporting of downloading errors.
