### ISSUE TITLE
Fallback image (or: default / placeholder / 404 image)

### ISSUE THREAD

**Issue by aight8** [imgproxy/imgproxy#220]
When talk about application side image processing, default images are a pain too. The implementation is very fragmented and requires lot of extra logic, placeholder right size.
It could nice together with cachebuster.

The implementation could be similar to watermark. Defining one fallback image would be nice, define it per preset or query even more nicer.

At best, the fallback image can have a full processing pipeline. With croping/resizing/fitting etc. it can create out of a prototype fallback image one, which can be used everywhere. (imagine an icon with a simple background)

Evtl. it makes sense to set the default image size of the fallback image same to the requested size of the original one (if exists). Just an idea.

In term of a proxy this is just defining the 404 page (or image here). So it would be totally legitim and keep imgproxy simple.

*Sidenote for devs*
If you have a deterministic source url for your entities primary image (like: /user/5343.png), you can automatically fetch the image or fallback image only with the users ID. In this case, Deterministic URL, requires an application side signing/encrypting for security.

**Comment by DarthSim** [comment]
Implemented by @ehiggs-deliverect 👍
