### ISSUE TITLE
invalid control character in URL

### ISSUE THREAD

**Issue by komarovf** [imgproxy/imgproxy#241]
Hello. I'm using imgproxy in docker (latest tag 31.10.2019)

My example image:
- img_url: `https://s14.stc.all.kpcdn.net/share/i/12/10497202/inx960x640.jpg`
- key_hex: `7374726f6e676b657973747268657265313233`
- salt_hex: `7374726f6e67736c617473747268657265313233`
- signed_encoded_url: `/Lds_q-f9QGr8uGmVo_rHt0Ur0jfuXGv1Wgvbj81qytw/300/300/aHR0cHM6Ly9zMTQu/c3RjLmFsbC5rcGNk/bi5uZXQvc2hhcmUv/aS8xMi8xMDQ5NzIw/Mi9pbng5NjB4NjQw/LmpwZw`

Got an error:
`
WARNING [2019-10-31T14:34:30Z] Completed in 106.664µs /Lds_q-f9QGr8uGmVo_rHt0Ur0jfuXGv1Wgvbj81qytw/300/300/aHR0cHM6Ly9zMTQu/c3RjLmFsbC5rcGNk/bi5uZXQvc2hhcmUv/aS8xMi8xMDQ5NzIw/Mi9pbng5NjB4NjQw/LmpwZw  request_id=7788b00e-0e96-40d6-a9da-8b40c797a9d8 method=GET status=404 error="parse \xdfM7\xd3F\x87GG\a3\xa2\xf2\xf73\x13B\xe77F2\xe6\x16\xc6\xc2\xe6\xb7\x066F\xe2\xe6\xe6WB\xf76\x86\x17&R\xf6\x92\xf3\x13\"\xf3\x13\x03C\x93s: net/url: invalid control character in URL"
`

I'm generating image_url with `height/width/encoded_url` and use default preset:
`"default=resizing_type:fill/enlarge:1,sharp=sharpen:0.7"`

**Comment by DarthSim** [comment]
Hi,

You can't omit parts of the basic URL format even if you defined them with the default preset. For your case, it's better to use the advanced format like this (a signature is not included in the example):

```
/s:300:300/aHR0cHM6Ly9zMTQu/c3RjLmFsbC5rcGNk/bi5uZXQvc2hhcmUv/aS8xMi8xMDQ5NzIw/Mi9pbng5NjB4NjQw/LmpwZw
```

**Comment by komarovf** [comment]
Thanks, it helps :)
