### ISSUE TITLE
presetfile format:jpg Resulting image format is not supported

### ISSUE THREAD

**Issue by banyaszb** [imgproxy/imgproxy#244]
Hello,
We are trying to implement improxy with  docker

- docker  image v2.6.1 
- env variable IMGPROXY_ONLY_PRESETS=true
- and preset file content set to awesome=resizing_type:fill/format:jpg

at container start we get "Resulting image format is not supported: jpeg"

if we disable IMGPROXY_ONLY_PRESETS and use the in_url format it works

**Comment by DarthSim** [comment]
Fixed in v2.6.2
