### ISSUE TITLE
 Docker container doesn't work

### ISSUE THREAD

**Issue by SNPR** [imgproxy/imgproxy#258]
Hello! I followed this instruction to start docker container with imgproxy:
```
docker pull darthsim/imgproxy:latest
docker run -p 8080:8080 -it darthsim/imgproxy
```
Then I try to open http://127.0.0.1/8080 I see this:

![image](https://user-images.githubusercontent.com/22043414/68921463-abfc0600-079a-11ea-9513-a073ec127433.png)

Can somebody help me to solve this problem?

**Comment by DarthSim** [comment]
Hi,

This is exactly what you should see on the root page. Please read our guide about URL generation https://docs.imgproxy.net/#/generating_the_url_advanced

**Comment by Envek** [comment]
@SNPR, what do you expect to find at `/` of imgproxy service?

---

To check that docker container works you can:
 1. Take any publicly available image, like this one: https://cdn.evilmartians.com/front/blocks/common/images/apple-touch-icon-28d6b28.png (180×180 pixels PNG)
 2. Construct imgproxy url for it (manually or using a client library like imgproxy gem):  http://localhost:8080/unsafe/rs:fill:128:128/plain/https://cdn.evilmartians.com/front/blocks/common/images/apple-touch-icon-28d6b28.png (resize it to 128×128 pixels without url signature)
 3. Open it in your browser (or embed it into your application's page)

If you see scaled image then it works. That is it.

**Comment by SNPR** [comment]
> @SNPR, what do you expect to find at `/` of imgproxy service?
> 
> To check that docker container works you can:
> 
> 1. Take any publicly available image, like this one: https://cdn.evilmartians.com/front/blocks/common/images/apple-touch-icon-28d6b28.png (180×180 pixels PNG)
> 2. Construct imgproxy url for it (manually or using a client library like [imgproxy gem](https://github.com/imgproxy/imgproxy.rb)):  http://localhost:8080/unsafe/rs:fill:128:128/plain/https://cdn.evilmartians.com/front/blocks/common/images/apple-touch-icon-28d6b28.png (resize it to 128×128 pixels without url signature)
> 3. Open it in your browser (or embed it into your application's page)
> 
> If you see scaled image then it works. That is it.

Thank you for your explanation!
I thought that docker container will give me web interface where I can change image size. 
But after your answer I finally understood how to use imgproxy.
