### ISSUE TITLE
Path prefix

### ISSUE THREAD

**Issue by shurik** [imgproxy/imgproxy#280]
Hello,

I'm considering deploying imgproxy behind an AWS application load balancer as an ECS/Docker task. I was hoping that it could live behind a path prefix like `/imgproxy/`. This way other tasks could refer to it via the same URL scheme, i.e. another app would handle all other paths.

http://example.org/* - some other app
http://example.org/imgproxy/* - imgproxy URLs

I've looked through the docs and source and it looks to me that imgproxy expects the signature to be the first in the URLs and this is not supported.

Is the only solution to put imgproxy behind another domain or proxy capable of re-writing URLs?

**Comment by selul** [comment]
@shurik not sure if this is the best workaround, but you could set CloudFront in front of this and use Lambda@Edge at Origin Request event to rewrite the request sent to the origin by trimming the prefix.

**Comment by shurik** [comment]
@selul Thank you for the idea. I've deployed it behind own load balancer so it can live at the root.
