### ISSUE TITLE
How to use the imgproxy command on ubuntu.

### ISSUE THREAD

**Issue by higherstar** [imgproxy/imgproxy#286]
Hello?
When I deploy imgproxy server on remote ubuntu18.04  server.
But after install the go and libvips-dev, I tried to install image proxy server using CGO_LDFLAGS_ALLOW="-s|-w" go get -f -u github.com/imgproxy/imgproxy.
Then After install it, I can not `imgproxy` command.
In order to generate the sale and private key, Do we need to use them?

Please show me the solution and deploy method.
Thanks.

**Comment by DarthSim** [comment]
Hi,
If `imgproxy` command is not found, you probably need to add Go binary path to your `PATH`. You can do this with `export PATH=$PATH:$GOPATH/bin`.

**Comment by Bruno-Meowtel** [comment]
I was experiencing the same issue and spent a while trying to figure out what was going on :) This worked.

It would be awesome to add at the end of the [Ubuntu installation instructions](https://github.com/imgproxy/imgproxy/blob/master/docs/installation.md).

**Comment by DarthSim** [comment]
We spend time and money to keep all the libraries inside the Docker image up to date, patched, and optimized so you can just run it and enjoy it. And you guys keep building imgproxy from the source. Why? 🙂
