### ISSUE TITLE
1px transparent in the border

### ISSUE THREAD

**Issue by mixmastertube** [imgproxy/imgproxy#289]
When extending and enlarging an image I get 1px transparent around the image.
It's a png image.

Should be completely purple, but there's a 1px small transparent border.

<img width="171" alt="Screenshot 2019-12-10 at 16 32 28" src="https://user-images.githubusercontent.com/81303/70543497-c1323d80-1b6a-11ea-9ee7-652de1e5404f.png">

Using these parameters
rs:fill:width:height:1:1

Also there's any way to skip the transparency in a PNG image, I would like to be an opaque PNG as Apple for example doesn't allow splash screens PNG images with alpha channels.

Thanks!

**Comment by DarthSim** [comment]
Hi,
Sorry, I can't reproduce the issue with my sample? Could you give your sample image and exact processing options?

> Also there's any way to skip the transparency in a PNG image, I would like to be an opaque PNG as Apple for example doesn't allow splash screens PNG images with alpha channels.

You can use [background](https://docs.imgproxy.net/#/generating_the_url_advanced?id=background) option for this.

**Comment by mixmastertube** [comment]
Thanks DarthSim, just tried and seems the problem was the image (had already the 1px transparency from before). 

Will try with the "background" option. 

Thanks a lot for the support!
