### ISSUE TITLE
support negative offsets for gravity 

### ISSUE THREAD

**Issue by gorkunov** [imgproxy/imgproxy#292]
I'm trying to make larger image from original image where empty area should be blank. Something like:
```
----------------------------
| final image              |
|                          |
|      ------------------  |
|      | original image |  |
|      |                |  |
|      ------------------  |
|                          |
----------------------------

```
For that I'm trying to use crop with `crop:final_width:final_height:nowe:-x:-y`.
But it seems currently crop doesn't support negative offsets. 
Maybe I'm missing something and this transformation could be achieved with different options?

**Comment by DarthSim** [comment]
Hi,
`crop` is definitely not the right instrument for this purpose. I think it should be something like `border` or `margin`, but imgproxy currently doesn't support stuff like this.

**Comment by gorkunov** [comment]
Seems I found a solution with double transformation using `original image` -> `intermediate image (resized)` -> `final image (crop + resize)`. Not a good one but as you said imgproxy has no other options for that now.

**Comment by arthuraliiev** [comment]
> Seems I found a solution with double transformation using `original image` -> `intermediate image (resized)` -> `final image (crop + resize)`. Not a good one but as you said imgproxy has no other options for that now.

@gorkunov, could you provide more details please? I need to add white margin around a picture, but can't find a workaround..

**Comment by gorkunov** [comment]
ok, I can share my code on elixir I hope it pretty simple for understanding (b/c it's mostly some basic math):
```elixir
  def build_image_url(%Image{viewport: viewport} = image, extension, width, height) do
    with {:ok, url} <- raw_image_url(image) do
      final_image_url =
        case viewport do
          %{x: x, y: y, width: w, height: h, natural_width: nw, natural_height: nh}
          when (x < 0 or y < 0 or w > nw or h > nh) and is_integer(nw) and is_integer(nh) ->
            dx = if x < 0, do: abs(x) + nw / 2, else: nw / 2 - x
            dy = if y < 0, do: abs(y) + nh / 2, else: nh / 2 - y
            max_dx = Enum.max([dx, w - dx, nw / 2])
            max_dy = Enum.max([dy, h - dy, nh / 2])
            max_w = round(2 * max_dx)
            max_h = round(2 * max_dy)
            img_proxy_opts = [rs: [:fill, max_w, max_h, "0", "t"], q: 100]
            max_image_url = Imgproxy.build_url(url, extension, img_proxy_opts)
            ddx = max_dx - dx
            ddy = max_dy - dy
            img_proxy_opts = [rs: [:fill, width, height, "t", "t"], q: 100, c: [w, h, :nowe, ddx, ddy]]
            Imgproxy.build_url(max_image_url, extension, img_proxy_opts)

          %{x: x, y: y, width: w, height: h} when x >= 0 and y >= 0 ->
            img_proxy_opts = [rs: [:fill, width, height, "t", "t"], q: 100, c: [w, h, :nowe, x, y]]
            Imgproxy.build_url(url, extension, img_proxy_opts)

          _ ->
            img_proxy_opts = [rs: [:fit, width, height], q: 100, el: 0, g: "ce"]
            Imgproxy.build_url(url, extension, img_proxy_opts)
        end

      {:ok, final_image_url}
    end
  end
```

Some notes:
for input we have original image with original (natural) width and height. We also have viewport this is selected area on image (x, y, width, height) this viewport could be more that image area. And finally we also have expected final image width, height and extension.

**Comment by gorkunov** [comment]
This flow of transformation also should help:

![image](https://user-images.githubusercontent.com/378207/72798637-f1d2c000-3c5c-11ea-94e3-90a5fcc5a1f2.png)

**Comment by arthuraliiev** [comment]
@gorkunov thank you a lot!!

**Comment by DarthSim** [comment]
#358 added a new [padding](https://docs.imgproxy.net/#/generating_the_url_advanced?id=padding) option. Thanks to @a1tus!
