### ISSUE TITLE
IMGPROXY_USE_S3=true allowing not only S3 resources

### ISSUE THREAD

**Issue by jfcalvo** [imgproxy/imgproxy#302]
Version: Using Docker latests image.

I have found that using `IMGPROXY_USE_S3=true` allow you to access images located at S3 as expected but is allowing requests to any other resource/URL too (not S3 URLs).

I didn't expect that from the security point of view. I understand that this option is more flexible but I was expecting that setting `IMGPROXY_USE_S3=true` only allows the service to retrieve images from `s3://` URLs and returning an error in the case that you try to specify a URL that is not for s3.

Any reason why this is the default? 

I believe that this can cause some confusion and can be a possible security problem for people that believes that after that setting only S3 resources can be specified.

Thanks for the good work creating this service.

**Comment by StaleSpace** [comment]
@jfcalvo Did you find any workaround for the same?

**Comment by DarthSim** [comment]
Hi,

The options that enable alternative protocols (`s3`, `gs`, `local`) doesn't disable other ones. Docs don't say that they should do so, sorry if it's confusing. There is PR https://github.com/imgproxy/imgproxy/pull/169 that allows configuring which protocols imgproxy should use, but it looks abandoned.

As a workaround, you could set `IMGPROXY_BASE_URL="s3://"` and exclude `s3://` from your urls.

**Comment by DarthSim** [comment]
Just released v2.8.0, now you can do the following to allow only s3 links:

`IMGPROXY_ALLOWED_SOURCES="s3://"`

Or you can do the following to allow only specific buckets:

`IMGPROXY_ALLOWED_SOURCES="s3://bucket1,s3://bucket2"`

**Comment by jfcalvo** [comment]
Thank you very much @DarthSim I think `IMGPROXY_ALLOWED_SOURCES` will solve my problem allowing only S3 resources. :+1:
