### ISSUE TITLE
Gravity with fit + extend

### ISSUE THREAD

**Issue by orofarne** [imgproxy/imgproxy#310]
Is it possible?
I tried urls like this:
`http://.../unsafe/rs:fit:200:600:1:1/g:so:0:0/plain/http://....jpg`
no effect.

**Comment by DarthSim** [comment]
Hi,
Currently, gravity doesn't affect the way imgproxy extends the image. I'll think about this.

**Comment by DarthSim** [comment]
Just released v2.8.0. Now you can set gravity for the `extend` option. You can do so with `rs:fit:200:600:1:1:so` or with `ex:1:so`
