### ISSUE TITLE
Memory leak above `v2.7`.

### ISSUE THREAD

**Issue by freakst** [imgproxy/imgproxy#315]
Hello. We have been using imgproxy on moderate production load in kubernetes. Recently I've noticed significant amount of `OOM Kill` and `Eviction` events on our deployments. Increasing available memory would not help, It would just eat 100+Gb in less than an hour. I decided to back to 2.7 due to core image change and `max_bytes ` option (looked suspicious to me). That confirmed being stable in production with like 35x less memory used opposing to `v2.8.1`. Judging by the logs: I see that problems with mem usage started much earlier (like 30+ days ago) just they did not affect us much until load was there.

**Comment by freakst** [comment]
Important to add: we've been using `latest` image tag before the incident.

**Comment by freakst** [comment]
https://i.gyazo.com/39a8738db52c28bb34918d2056ba81e8.png
This is the screen of memory usage after downgrade to 2.7 (load remains the same)

**Comment by MarcBoeing** [comment]
I can confirm this. We jumped from 2.7 to 2.8.1 today and see the same "higher than normal" memory usage.

**Comment by Chocksy** [comment]
Same with my heroku instance. I did not manage to investigate where this comes from.
![image](https://user-images.githubusercontent.com/178892/71872612-a6c99080-3125-11ea-80e0-e2c2af74a19e.png)

**Comment by DarthSim** [comment]
Hi everyone,
Sorry for the big delay, I was on new year vacation.

You can try the latest build. Also running the Docker image with the following env variables should solve the problem:

```
LD_PRELOAD=''
MALLOC_ARENA_MAX=2
```

This is not memory leak per se, this is how GLib works. jemalloc usage has been should solve memory growth but it seems like it didn't. `MALLOC_ARENA_MAX=2` seems to work fine here.

**Comment by freakst** [comment]
Ty for advice, @DarthSim, I will give that a shot on Monday/Tuesday. But did why the issue evolve only at `v2.8` did switch to GLib happened there?

**Comment by DarthSim** [comment]
I changed the base image from Alpine to Debian. Alpine uses musl instead of GLib, and its small stack size causes lots of segfaults that I'm tired of fighting. Also, imgproxy works a bit faster on Debian.

Debian uses GLib that has known problems with greedy memory allocation.

**Comment by DarthSim** [comment]
I added `malloc_trim` call to the latest build, this significantly reduced memory usage. I'll observe our instances, and if everything goes well, I'll make a release.

**Comment by MarcBoeing** [comment]
For us, v2.8.2 solves the issue. Thank you very much!

**Comment by freakst** [comment]
Not the case for us, without MALLOC_ARENA_MAX=2 already 4x mem usage from `v2.7` and growing:

<img width="1351" alt="aad09805fc37fe360f8a5e48fd266857" src="https://user-images.githubusercontent.com/64145/72328242-3e495900-36bb-11ea-8f6b-6d6d50334c69.png">

**Comment by DarthSim** [comment]
@freakst Do you use 2.8.2? It already has `MALLOC_ARENA_MAX=2` set.

**Comment by freakst** [comment]
Yes we do,actually afer some time we've got stable usage ~ 70mb, no OOM events registered since rls. 
<img width="1342" alt="99088885540ac6cc5a4eff054c4cb642" src="https://user-images.githubusercontent.com/64145/72338568-7194e380-36cd-11ea-873f-374c9c337f5b.png">
