### ISSUE TITLE
issue with SVG format when it starts with comment

### ISSUE THREAD

**Issue by selul** [imgproxy/imgproxy#317]
Hello, 

It seems when the source is an SVG image that starts with a comment, the decoder fails to properly detect it as an SVG and imgproxy returns `Source image type not supported` even if the SVG markup is valid. 

I have attached a sample file in the zip as I'm not able to attach SVG files here.

[spinner.svg.zip](https://github.com/imgproxy/imgproxy/files/4023420/spinner.svg.zip)

Any idea which is the best way to detect this? Maybe strips the comments

**Comment by DarthSim** [comment]
The easiest way is to add `<!--` as magic bytes for SVG. But we should probably find a better way. I created a new issue for this #334 

Added the fix to the latest build.
