### ISSUE TITLE
Cache-Control header passthrough

### ISSUE THREAD

**Issue by zoul** [imgproxy/imgproxy#319]
Currently the `Cache-Control` header is always set using the TTL value from the config. Was there some discussion about not touching the header if it’s already present? I load the images from S3 where caching metadata is already set for the images and imgproxy overwrites those with bogus TTL. I can change imageproxy’s TTL as a workaround, but I can’t change other contents of the header (such as replacing `public` with `immutable`).

**Comment by DarthSim** [comment]
Added `IMGPROXY_CACHE_CONTROL_PASSTHROUGH` option to the latest build
