### ISSUE TITLE
Resizing animated gif results in broken result

### ISSUE THREAD

**Issue by danielberndt** [imgproxy/imgproxy#326]
In:

![waterfall-p28irqpITY-1](https://user-images.githubusercontent.com/856386/72737653-3f3d2780-3ba0-11ea-8588-1a4b22e7e7f1.gif)

out: (via `/rs:fit:147:104/`)
 
![waterfall-p28irqpITY](https://user-images.githubusercontent.com/856386/72737630-34829280-3ba0-11ea-8be9-6645d929c269.gif)

Same result when outputting it as `.webp`

Seems to work fine for the first frame (thus the flickering), but creates a transparent box for the remaining frames. Not sure whether it's an issue with imgproxy or libvips.

version: brand latest docker image (installed today)

**Comment by DarthSim** [comment]
Hi,
This looks like a libvips' gifload bug. `vipsthumbnail --size=200 -f tn_bad4.gif bad4.gif[n=-1]` produces the same result:

![tn_bad4](https://user-images.githubusercontent.com/380856/73359497-2da7fe00-42cb-11ea-915a-660da79a0ecd.gif)

**Comment by DarthSim** [comment]
John solved this with https://github.com/libvips/libvips/issues/1543. Will be fixed in imgproxy as soon as libvips 8.9.2 is released.

**Comment by danielberndt** [comment]
Thanks a lot :)

**Comment by legopin** [comment]
Hi @DarthSim, libvips 8.9.2 was just out a few days ago, will there be a new version of imgproxy that includes it?
https://github.com/libvips/libvips/releases/tag/v8.9.2

**Comment by DarthSim** [comment]
Just released v2.13.1. Autobuild on Docker Hub takes a lot of time, so the image will be available in an hour.

**Comment by legopin** [comment]
`v2.13.1` fixed the GIF artifacts for us. Thank you for the quick response

**Comment by DanteG41** [comment]
does this fix apply to animated webp output ?

**Comment by DarthSim** [comment]
@DanteG41 Yup, v2.13.1 includes fix for this issue and fixes animation processing broken in 2.13.0

**Comment by DanteG41** [comment]
There may still a bug in libvips for some gif https://github.com/libvips/libvips/issues/1649

**Comment by DarthSim** [comment]
`v2.15.0` uses libvips 8.10 where this bug should be fixed

**Comment by DanteG41** [comment]
thx. this version fixed my case

**Comment by DarthSim** [comment]
Looks like this can be closed
