### ISSUE TITLE
ICO image - unknown image format

### ISSUE THREAD

**Issue by jpalumickas** [imgproxy/imgproxy#337]
Hey!

Currently, we try to load ICO file and we get error: `unknown image format` 

We using official Heroku Docker build so I think it should be supported.
https://docs.imgproxy.net/#/image_formats_support?id=ico-support

Thanks for this amazing project!  😊

**Comment by DarthSim** [comment]
Hi!
Could you give me the ICO that causes the issue?

**Comment by jpalumickas** [comment]
Hey,

Sure! Attaching as ZIP, because I cannot attach ICO files here.
[favicon.ico.zip](https://github.com/imgproxy/imgproxy/files/4197886/favicon.ico.zip)

**Comment by DarthSim** [comment]
Well, that's interesting. Looks like this ICO contains an image that imgproxy can't recognize. Keeping digging.

**Comment by jpalumickas** [comment]
We found a lot more ICO images that are not supported, I think most of them cannot be processed. I think they will be related somehow. 🙂

**Comment by DarthSim** [comment]
Oh, I think, I got it. ICO stores BMP with an incomplete header. That's why ICO with PNG works fine, but ICO with BMP causes an error. I'll try to solve this.

**Comment by DarthSim** [comment]
Looks like I solved this. Docker image build is still in progress, the new image will be available in an hour (yep, DockerHub's autobuild is pretty slow).

**Comment by jpalumickas** [comment]
nice! thanks for all your hard work! 🎉

**Comment by jpalumickas** [comment]
@DarthSim it's working! thank you!
