### ISSUE TITLE
Support for multiple AWS S3 buckets

### ISSUE THREAD

**Issue by nirfse** [imgproxy/imgproxy#347]
Hello, many thanks for a great image server.

Our application uses separate S3 buckets for different types of images. Some buckets store static website images, several buckets for user-generated images, separate bucket for icons, etc. Currently we use stand-alone `imgproxy` docker instances for each bucket, and feels like a bit overkill.

Please consider implementing support for an image source from multiple AWS S3 buckets. It might be implemented via using custom HTTP request headers and/or URL paths. Thanks for consideration.

**Comment by r0stig** [comment]
Not sure if I'm misunderstanding but you're already able to specify different buckets via the s3-url, see: https://docs.imgproxy.net/#/serving_files_from_s3

**Comment by DarthSim** [comment]
Yup, @r0stig is right. S3 link format is `s3://%bucket_name/%file_name`. You can use any bucket that your configured AWS credentials have access to.

**Comment by nirfse** [comment]
Thank you both. I got myself confused using fixed `IMGPROXY_BASE_URL` in envvar, and didn't double-check the page in the documentation. Had no time to refactor the app yet, but I am generally positive that the issue can be closed.
