### ISSUE TITLE
How to deploy on ubuntu 18.04

### ISSUE THREAD

**Issue by thanh858036** [imgproxy/imgproxy#349]
i deploy on ubuntu 18 From the source. I build libvips from the source.
I install imgproxy
`CGO_LDFLAGS_ALLOW="-s|-w" go get -f -u github.com/imgproxy/imgproxy`
it error
`# github.com/imgproxy/imgproxy
/root/go/src/github.com/imgproxy/imgproxy/errors_reporting.go:68:42: sentry.Request literal.FromHTTPRequest undefined (type sentry.Request has no field or method FromHTTPRequest)`

I install package libvips `apt-get install libvips-dev`
It error
`# github.com/imgproxy/imgproxy
/tmp/go-build115805004/b001/_x006.o: In function vips_trim':
go/src/github.com/imgproxy/imgproxy/vips.c:421: undefined reference to vips_find_trim'
collect2: error: ld returned 1 exit status
 github.com/imgproxy/imgproxy
vips.c: In function ‘vips_trim’:
vips.c:421:7: warning: implicit declaration of function ‘vips_find_trim’; did you mean ‘vips_trim’? [-Wimplicit-function-declaration]
   if (vips_find_trim(tmp, &left, &top, &width, &height, "background", bga, "threshold", threshold, NULL)) {
       ^~~~~~~~~~~~~~
       vips_trim`

**Comment by DarthSim** [comment]
Could you try`GO111MODULE=on CGO_LDFLAGS_ALLOW="-s|-w" go get -f -u github.com/imgproxy/imgproxy` with libvips built from source?

**Comment by thanh858036** [comment]
i added gopath `export PATH=$PATH:$GOPATH/bin` but imgproxy: command not found

**Comment by MagiCrazy** [comment]
Hello, I have the exact same problem.

```
$ GO111MODULE=on CGO_LDFLAGS_ALLOW="-s|-w" go get -f -u github.com/imgproxy/imgproxy
go get: -f flag is a no-op when using modules
go: downloading github.com/imgproxy/imgproxy v1.1.8
go: downloading github.com/imgproxy/imgproxy v2.2.11+incompatible
go: github.com/imgproxy/imgproxy upgrade => v2.2.11+incompatible
go: finding module for package github.com/prometheus/client_golang/prometheus
go: finding module for package cloud.google.com/go/storage
go: finding module for package github.com/mat/besticon/ico
go: finding module for package github.com/aws/aws-sdk-go/aws/session
go: finding module for package golang.org/x/image/vp8l
go: finding module for package github.com/bugsnag/bugsnag-go
go: finding module for package golang.org/x/image/vp8
go: finding module for package golang.org/x/image/riff
go: finding module for package github.com/aws/aws-sdk-go/aws
go: finding module for package google.golang.org/api/option
go: downloading cloud.google.com/go/storage v1.6.0
go: downloading github.com/bugsnag/bugsnag-go v1.5.3
go: downloading github.com/prometheus/client_golang v1.4.1
go: downloading golang.org/x/image v0.0.0-20200119044424-58c23975cae1
go: downloading github.com/mat/besticon v3.11.0+incompatible
go: downloading google.golang.org/api v0.19.0
go: downloading github.com/aws/aws-sdk-go v1.29.11
go: downloading cloud.google.com/go v0.53.0
go: finding module for package golang.org/x/sync/errgroup
go: downloading golang.org/x/sync v0.0.0-20190911185100-cd5d95a43a6e
go: finding module for package github.com/getsentry/raven-go
go: downloading github.com/getsentry/raven-go v0.2.0
go: finding module for package github.com/matoous/go-nanoid
go: downloading github.com/matoous/go-nanoid v1.1.0
go: finding module for package github.com/valyala/fasthttp
go: finding module for package github.com/honeybadger-io/honeybadger-go
go: downloading github.com/valyala/fasthttp v1.9.0
go: downloading github.com/honeybadger-io/honeybadger-go v0.5.0
go: finding module for package github.com/newrelic/go-agent
go: finding module for package github.com/prometheus/client_golang/prometheus/promhttp
go: finding module for package github.com/aws/aws-sdk-go/service/s3
go: downloading github.com/newrelic/go-agent v1.11.0
go: downloading github.com/newrelic/go-agent v3.3.0+incompatible
go: found cloud.google.com/go/storage in cloud.google.com/go/storage v1.6.0
go: found github.com/aws/aws-sdk-go/aws in github.com/aws/aws-sdk-go v1.29.11
go: found github.com/bugsnag/bugsnag-go in github.com/bugsnag/bugsnag-go v1.5.3
go: found github.com/getsentry/raven-go in github.com/getsentry/raven-go v0.2.0
go: found github.com/honeybadger-io/honeybadger-go in github.com/honeybadger-io/honeybadger-go v0.5.0
go: found github.com/mat/besticon/ico in github.com/mat/besticon v3.11.0+incompatible
go: found github.com/matoous/go-nanoid in github.com/matoous/go-nanoid v1.1.0
go: found github.com/newrelic/go-agent in github.com/newrelic/go-agent v3.3.0+incompatible
go: found github.com/prometheus/client_golang/prometheus in github.com/prometheus/client_golang v1.4.1
go: found github.com/valyala/fasthttp in github.com/valyala/fasthttp v1.9.0
go: found golang.org/x/image/riff in golang.org/x/image v0.0.0-20200119044424-58c23975cae1
go: found golang.org/x/sync/errgroup in golang.org/x/sync v0.0.0-20190911185100-cd5d95a43a6e
go: found google.golang.org/api/option in google.golang.org/api v0.19.0
go: github.com/imgproxy/imgproxy imports
	github.com/matoous/go-nanoid: github.com/matoous/go-nanoid@v1.1.0: parsing go.mod: go.mod:1: usage: go 1.23
```
I don't have any clue...

**Comment by DarthSim** [comment]
Could you give me your `go version` and `go env` output?

**Comment by thanh858036** [comment]
my go output
`go version go1.14 linux/amd64`
`GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.14/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build843007552=/tmp/go-build -gno-record-gcc-switches"`

**Comment by DarthSim** [comment]
Does this work?

```
GO111MODULE=on CGO_LDFLAGS_ALLOW="-s|-w" go install github.com/imgproxy/imgproxy
```

**Comment by DarthSim** [comment]
Yup, `git clone` + `go build` is a must-work option. I'm trying to figure out why `go get` / `go install` doesn't work for you, because it should.

**Comment by DarthSim** [comment]
Oh geez, the building flow from the docs is broken with Go 1.14.

**Comment by thanh858036** [comment]
`git clone` + `go build` work but can not run command imgproxy
`/root/imgproxy/imgproxy: error while loading shared libraries: libvips.so.42: cannot open shared object file: No such file or directory`

**Comment by MagiCrazy** [comment]
> > Yup, `git clone` + `go build` is a must-work option. I'm trying to figure out why `go get` / `go install` doesn't work for you, because it should.
> 
> `git clone` + `go build` work but can not run command imgproxy
> `/root/imgproxy/imgproxy: error while loading shared libraries: libvips.so.42: cannot open shared object file: No such file or directory`

Did you install libvips and setup your lib path?
It works for me, I don't have any libraries issues.

**Comment by thanh858036** [comment]
> Did you install libvips and setup your lib path?
> It works for me, I don't have any libraries issues.

it worked

**Comment by DarthSim** [comment]
Oh, I figured it out and fixed the problems. This should work:

```
GO111MODULE=on CGO_LDFLAGS_ALLOW="-s|-w" go get -u github.com/imgproxy/imgproxy/v2
```

**Comment by MagiCrazy** [comment]
> Oh, I figured it out and fixed the problems. This should work:
> 
> ```
> GO111MODULE=on CGO_LDFLAGS_ALLOW="-s|-w" go get -u github.com/imgproxy/imgproxy/v2
> ```

yeah, it works! :+1:

**Comment by TommyLee0088** [comment]
And what step to run when after "GO111MODULE=on CGO_LDFLAGS_ALLOW="-s|-w" go get -u github.com/imgproxy/imgproxy/v2"

I have no idea.

**Comment by MagiCrazy** [comment]
> And what step to run when after "GO111MODULE=on CGO_LDFLAGS_ALLOW="-s|-w" go get -u github.com/imgproxy/imgproxy/v2"
> 
> I have no idea.

Just run it. You would find the binary in your `$GO_PATH/bin/`.

**Comment by DarthSim** [comment]
Looks like this can be closed

**Comment by karbiv** [comment]
Docs should not recommend "go get **-u**".
Even minor and patch upgrades can introduce breaking changes, more so when there are many dependencies. It's only a convention.

**Comment by stevelacey** [comment]
> Oh, I figured it out and fixed the problems. This should work:
> 
> ```
> GO111MODULE=on CGO_LDFLAGS_ALLOW="-s|-w" go get -u github.com/imgproxy/imgproxy/v2
> ```

I don't have any idea what is happening, this gets further than what the documentation suggests, but then I get `warning: implicit declaration of function ‘vips_addalpha’` and meh, this is a lot harder than `brew install imgproxy`.

**Comment by DarthSim** [comment]
@stevelacey It's better to build vips from source anyway. Though I try to keep compatibility with old versions, imgproxy uses features from the latest versions, and building imgproxy with very old versions of vips is not even tested. Vips package from Ubuntu 18.04 is VERY old and doesn't have `vips_addalpha`.

**Comment by stevelacey** [comment]
I gave up trying to get this working 18 and built a new Ubuntu 20 image which worked just fine with the apt packages 👌🏼
