### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by gnuletik** [imgproxy/imgproxy#361]
Are there any plan to build the Docker image for ARMv7 and v8 ?
https://docs.docker.com/docker-for-mac/multi-arch/

Thanks for this great tool :)

**Comment by DarthSim** [comment]
Hi Martin,
Yup, I have a plan to play with ARM build, but I'd not expect it in a short time.

**Comment by DarthSim** [comment]
Starting from v2.14.0, imgproxy Pro has Docker images for ARM optimized for AWS Graviton2 (*g instances). For now, it's Pro-only feature, and I'm not sure it will be available for the OSS version.
