### ISSUE TITLE
Support for Backblaze B2 Cloud storage

### ISSUE THREAD

**Issue by enstyled** [imgproxy/imgproxy#365]
I want to start by saying you have done an _amazing_ job with imgproxy, I love the idea and the execution!

I would like to propose adding support for [Backblaze B2 Cloud storage](https://www.backblaze.com/b2/cloud-storage.html) as a source option. It's a great and cheaper alternative to AWS S3.

**Comment by DarthSim** [comment]
Hi Emil,

As far as I see, Backblaze has access to the files by URL. if you need access to private files, you can set the `Authorization` header with `IMGPROXY_CUSTOM_REQUEST_HEADERS` (supported only by Pro version though).

If you want a dedicated URL schema for Backblaze B2, you can make a PR. I'm pretty loaded with other tasks right now, and this feature request may wait for my attention a pretty long time.

**Comment by flagman** [comment]
Backblaze has s3 compatible API. 
So you can use your backblaze creds with imgproxy as follows: 
```
AWS_ACCESS_KEY_ID=keyID 
AWS_SECRET_ACCESS_KEY=applicationKey
IMGPROXY_S3_ENDPOINT=s3.us-west-000.backblazeb2.com
IMGPROXY_USE_S3=true
```
Access your image:
`http://imgproxy.sample.com/[signature]/fill/300/400/sm/0/plain/s3://[backblaze bucket name]/0000011.jpg`
