### ISSUE TITLE
Client Hints Url Structure?

### ISSUE THREAD

**Issue by alteredorange** [imgproxy/imgproxy#377]
Hello! I'm using your wonderful Docker image and things are working great! The only thing I'm just having a real hard time getting client hints to work. Do I need to do something special in the URL to make it work?

I've added  ` <meta http-equiv="Accept-CH" content="DPR, Viewport-Width, Width" />` to the html head.  I have `IMGPROXY_ENABLE_CLIENT_HINTS` set to true in the variables. And then I just request a normal url like: `https://imgproxyURL.herokuapp.com/insecure/plain/https://image-path/test.jpg`. 

In Html I tried picture and img tags:

`  <picture>
    <source media="(max-width: 10em)" sizes="10px" srcset={base + pic} />
    <img sizes="10px" src={base + pic} />
  </picture>
  <img src={base + pic} sizes="50vw" alt="image thing displayed at 50% of viewport width" />`

Do I need to add anything to the url to get things working? Any help would be greatly appreciated, thanks!

P.s., while trying to get this to work, I noticed imgix (https://docs.imgix.com/tutorials/responsive-images-client-hints) allows you to put the client hints in the URL, which would prevent against and Header modification attacks.

**Comment by DarthSim** [comment]
Hi Bob,

What browser do you use? It looks like the current version of Google Chrome doesn't send client hints to third-party endpoints. You can check request headers in the dev tools of your browser.

As for imgproxy side, `IMGPROXY_ENABLE_CLIENT_HINTS` is the only config you need to set as true to get client hints working.

> while trying to get this to work, I noticed imgix (https://docs.imgix.com/tutorials/responsive-images-client-hints) allows you to put the client hints in the URL, which would prevent against and Header modification attacks.

No, it wouldn't. Imgix allows enabling/disabling client hints via URL, just like imgproxy does it via environment variables.

**Comment by alteredorange** [comment]
Ah I see! Ok good to know. I tried Firefox and chrome, looks like they aren't sending anything. So what way would you recommend to get the right size image? Just use srcset with 3-6 sizes? Do you have an example client side? Thanks!

**Comment by DarthSim** [comment]
Sorry, I'm not a frontend developer, so I can't help you here :( Maybe @selul could help since he added client hints to imgproxy.

**Comment by selul** [comment]
I know that the support is slightly limited for this feature on Chrome but I'm not entirely up to date with the recent developments regarding this. 

You might want to experiment by having imgproxy on a subdomain from the main domain where the images are embedded. 

Alternatively using sizes with srcset it's a good choice to serve responsive images.

**Comment by alteredorange** [comment]
Yes it looks like client hints aren't what they used to be :) I just went with using srcset with dynamic sizes, works for my use case.  Thanks for the help!


`    <img
      srcset="{image.srcset}"
      sizes="(max-width: 600px) calc(100vw - 30px), (max-width: 1200px)
      calc(50vw - 30px), calc(33.33vw - 30px)"
      src="{image.src}"
    />`
