### ISSUE TITLE
Problem with filenames with # character in naming

### ISSUE THREAD

**Issue by draev** [imgproxy/imgproxy#385]
There is a problem with filenames that contains **#** character.  Example image name is **4555/9534280P_#1.JPG**

The request is URL Encoded

Here is example:

`2020-04-24T19:55:33.430153000Z WARNING [2020-04-24T19:55:33Z] Completed in 392.512µs /insecure/preset:thumb/plain/local:/4555/9534280P_%231.JPG  request_id=J_oq5CIzA-Tuir0x5ikNz method=GET status=404 error="Get \"local:///4555/9534280P_#1.JPG\": open /pics/4555/9534280P_: no such file or directory"`

The file exists in the filesystem.

This error  reproduced both for local path and gs path

**Comment by DarthSim** [comment]
We have already discussed this privately, so I just explain it to the ones who may face the same issue.

Source image URL is always URL, even if it points to the local storage or S3 or whatever. And it should always act as a URL. imgproxy uses the path of the `local:///...` URL as the path to the file, but strings after `#` or `?` are not a part of the path. So to get access to your file with `#` in its name you need to double-escape the source URL like this:

- First, escape `#` and `?` in your URL.
- Then, escape the whole URL.

Example:
`local:///4555/9534280P_#1.JPG` => `local:///4555/9534280P_%231.JPG` => `local%3A%2F%2F%2F4555%2F9534280P_%25231.JPG`

**Comment by foobargeez** [comment]
> So to get access to your file with # in its name you need to double-escape the source URL

Oh man -- thanks for this.  This *really* needs to go to the docs .. I just wasted couple of hours :-(

**Comment by naglfar** [comment]
Sorry for reviving this old ticket, but can anyone chime in if this is still up to date?
For my current tests with 3.27.0 I do not have to double-escape ```#``` in the local url and the file gets found just fine, on the other hand local files with a question mark do not get found either way. Double escaped characters end up how you would expect it, while normally escaped question marks make the request being cut off:

```
ERROR   [2024-12-29T11:48:16+01:00] Completed in 220.022µs /insecure/plain/local:///tmp/t%253Fest.jpg  request_id=IzABTU6L56E6M6dkDi9PL method=GET status=404 client_ip="" error="Can't download source image: Status: 404; /tmp/t%3Fest.jpg doesn't exist"
ERROR   [2024-12-29T11:43:09+01:00] Completed in 191.909µs /insecure/plain/local:///tmp/t%3Fest.jpg  request_id=L2MgkKtr9gMfpxUOSH08R method=GET status=404 client_ip="" error="Can't download source image: Status: 404; /tmp/t doesn't exist"
```

**Comment by DarthSim** [comment]
Yes, we improved the handling of special characters like `%` and `#` so they don't need double-escaping anymore. I explained why `?` is not handled the same way here: https://github.com/imgproxy/imgproxy/pull/1411#issuecomment-2573330263
