### ISSUE TITLE
IMGPROXY_ENFORCE_WEBP doesn't enforce webp

### ISSUE THREAD

**Issue by mfcndw** [imgproxy/imgproxy#391]
Tested locally using vanilla `darthsim/imgproxy:latest`, only change is `IMGPROXY_ENFORCE_WEBP` set to true.
Tested using multiple images in various format in Chrome (81.0.4044.122). Still getting original format of images.

**Comment by DarthSim** [comment]
Hi Fang,

Sorry, I can't reproduce the issue. When I set `IMGPROXY_ENFORCE_WEBP=1` and make a request from Chrome, imgproxy always responds with WebP. May it happen that you use some caching proxy in front of imgproxy, which doesn't forward the request headers? Also, can I take a look at your `docker inspect ...` output?

**Comment by mfcndw** [comment]
Ah nvm when taking a closer some of my configs are in malformat. It runs fine.
