### ISSUE TITLE
Support crop by percentage

### ISSUE THREAD

**Issue by mfcndw** [imgproxy/imgproxy#392]
Hi,

Seems like currently crop can only be done by giving width & height in pixel. Is it possible to also have an option to take percentage as input?

**Comment by DarthSim** [comment]
Hi Fang,
Could you give me an example use case for this?

**Comment by mfcndw** [comment]
We have a feature to show a zoomed in (by percentage) image. Currently when rendering, we download the original image, then use the percentage in request to zoom into that part (e.g. Starting from (0+20% x, 0 + 20% * y), zoom to 20% of the original width & height) and display the partial image.
By supporting cropping by percentage, we can directly download the cropped image.

**Comment by DarthSim** [comment]
Hey! I'm so sorry, I released crop by percentage in v2.16.0 and forgot to drop a comment here. Just use width/height <1 in the crop option, and imgproxy will treat this as a relative size. Ex: `.../crop:0.5:0.5/...` will crop image by half.
