### ISSUE TITLE
Ability to skip processing of some formats

### ISSUE THREAD

**Issue by legopin** [imgproxy/imgproxy#393]
## Question

Since GIF processing is slow and taxing, is there any way to skip gif processing?
Could we disable processing on certain file types and opt for pass-through?

## Scenario
Our use case is that we are using imgproxy to server user updated content, but sometimes these include gif files.

We noticed that even though GIF -> webp processing is efficient, GIF -> GIF is not. 
A GIF that takes 1.3 sec to resize to webp takes 8 sec to resize to GIF format. 

In these scenarios where processing time is significantly longer with negligible size savings, we would rather have all GIF files get passed through imgproxy without any processing applied to it.

**Comment by DarthSim** [comment]
Hi Sean,

Try to update to v2.13.1. I made some improvements in animations processing, it should go faster now. However, it looks like the problem is not in processing but in saving to GIF, which is done by ImageMagick.

Anyway, the idea of skipping some formats processing is pretty interesting.

**Comment by jpalumickas** [comment]
Skip processing on some formats is really good idea. We thinking about same problem for GIFs too.

**Comment by bandit-hire5** [comment]
When do you think could you implement skipping some formats processing? We really need this opportunity.

**Comment by DarthSim** [comment]
`IMGPROXY_SKIP_PROCESSING_FORMATS` is added to `v2.15.0` https://docs.imgproxy.net/#/configuration?id=skip-processing

**Comment by jpalumickas** [comment]
@DarthSim is it possible to skip this processing from Query params? for example if we want to skip not globally, but in some places?

**Comment by DarthSim** [comment]
@jpalumickas it's not implemented yet it's possible to implement it. If you still need this feature, please, create a new feature request so I can track it.

**Comment by jpalumickas** [comment]
@DarthSim thank you! will do that!
