### ISSUE TITLE
Preventing hotlinking

### ISSUE THREAD

**Issue by nathanhleung** [imgproxy/imgproxy#394]
Is there anyway to only allow images to be loaded from a certain domain/set of domains? (i.e. prevent hotlinking)

**Comment by legopin** [comment]
I think this could be better handled with a CDN. 
Something like this: https://support.cloudflare.com/hc/en-us/articles/200170026-Understanding-Cloudflare-Hotlink-Protection

As stated in the README for imgproxy, this sounds like it's out of the scope for imgproxy.

> Simplicity
> "No code is better than no code."
> 
> imgproxy only includes the must-have features for image processing, fine-tuning and security. Specifically,
> 
> - It would be great to be able to rotate, flip and apply masks to images, but in most of the cases, it is possible — and is much easier — to do that using CSS3.
> - It may be great to have built-in HTTP caching of some kind, but it is way better to use a Content-Delivery Network or a caching proxy server for this, as you will have to do this sooner or later in the production environment.
> - It might be useful to have everything built in — such as HTTPS support — but an easy way to solve that would be just to use a proxying HTTP server such as nginx.

**Comment by nathanhleung** [comment]
Makes sense. Thanks for your response!
