### ISSUE TITLE
Help With Salt/Key

### ISSUE THREAD

**Issue by xdougx** [imgproxy/imgproxy#398]
I dont undertand how key and salt works on my url, can i have an pratical example?

**Comment by legopin** [comment]
This is the format for simple URL
```
/%signature/%resizing_type/%width/%height/%gravity/%enlarge/plain/%source_url@%extension
/%signature/%resizing_type/%width/%height/%gravity/%enlarge/%encoded_source_url.%extension
```

Advanced URL
```
/%signature/%processing_options/plain/%source_url@%extension
/%signature/%processing_options/%encoded_source_url.%extension
```
The signatrue is calculated from `processing_options` + `source_url` + `extension`, using the provided salt and key.

The examples below all demonstrate how to generate signatures in various languages:
https://github.com/imgproxy/imgproxy/tree/master/examples

**Comment by xdougx** [comment]
Thank you, help very much!
