### ISSUE TITLE
Install from sources on Centos 7

### ISSUE THREAD

**Issue by a-pashkov** [imgproxy/imgproxy#399]
Please help.

I tried install improxy from sources on Centos 7 but:

[root@imgproxy ~]# export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
[root@imgproxy ~]# GO111MODULE=on CGO_LDFLAGS_ALLOW="-s|-w" go get -u github.com/imgproxy/imgproxy/v2
go: finding github.com/golang/groupcache latest
go: finding github.com/kardianos/osext latest
go: finding golang.org/x/xerrors latest
go: finding golang.org/x/tools latest
go: finding golang.org/x/oauth2 latest
go: finding golang.org/x/net latest
go: finding github.com/StackExchange/wmi latest
go: finding golang.org/x/sys latest
go: finding golang.org/x/image latest
go: finding google.golang.org/genproto latest
go: finding golang.org/x/exp latest
go: finding golang.org/x/lint latest
\# github.com/imgproxy/imgproxy/v2
**go/pkg/mod/github.com/imgproxy/imgproxy/v2@v2.13.1/errors_reporting.go:68:42: sentry.Request literal.FromHTTPRequest undefined (type sentry.Request has no field or method FromHTTPRequest)**

cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)

libvips-8.9.2 builded from sources

[root@imgproxy ~]# go version
go version go1.13.6 linux/amd64

[root@imgproxy ~]# go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build955973571=/tmp/go-build -gno-record-gcc-switches"

**Comment by DarthSim** [comment]
Hey!

It looks like for some reason Go doesn't use package versions from `go.mod`. Try downloading a source tarball from the releases page and running `CGO_LDFLAGS_ALLOW="-s|-w" go build` from the source dir.

**Comment by DarthSim** [comment]
I updated the installation manual
