### ISSUE TITLE
AWS Fargate Implementation?

### ISSUE THREAD

**Issue by alteredorange** [imgproxy/imgproxy#409]
Has anyone run this with AWS Fargate? I just got it set up, but I don't think I'm doing it correctly. I create a new Fargate cluster, use the imgproxy docker image, and it auto creates the "first-run-task-definition".

It looks like everything runs great, I can click on the task, and it gives me the IP address of imgproxy, which I can access normally. The only problem is that it looks like the task runs 100% of the time, and so you'd be billed 100% of the time. Unless when imgproxy is idle it doesn't use any resources? Does anyone know if it's only "active" when processing an image?  

If not, does anyone know how to configure the task to only run when processing an image, and then shut down?  Any help would be appreciated, thanks!

**Comment by alteredorange** [comment]
Ok, so it looks like it's not really feasible with Fargate, it will need to run 100% of the time to do what it needs to do. However... I ran into Google Cloud Run, and it's perfect!  You can upload the docker image of imgproxy, and it's always "on", but it only bills you for compute time! You also get 2 days straight of processing per month, which would be a LOT of images. Great solution for anyone looking to treat imgproxy as a serverless function, but still use the docker image!

**Comment by legopin** [comment]
@alteredorange That sounds very impressive. Would you mind sharing a little more on the details?

Are there any special configs that you had to do to make it work? What sort of resources (CPU/RAM) did you have to allocate?

**Comment by alteredorange** [comment]
Hi @legopin , sorry just saw your comment today! Basic steps are:

1. Get a GCP account (make sure you get the $300 free credit) https://cloud.google.com/

2. Import the imgproxy docker image into google cloud run. You'll need the GCP command line tools, then download the imgproxy img, tag it and upload it to GCP cloud run. Google "import docker image into gcp cloud run" for examples and videos.  Here's the docs: https://cloud.google.com/container-registry/docs/pushing-and-pulling

3. Go to the GCP dashboard and then in the lefthand menu go to the Cloud Run section. Click that and then click "Create Service". Pick your region, service name (like imgporxy) and whether or not you want Auth. I just left mine public since I use auth on imgproxy, but if you want to set up IAM credentials, click that.

4. Click next, and select the imgproxy docker image you uploaded to GCP. Then you can set environmental variables, and what not. I let all the Google settings just what they were. Once it's created, you'll see the URL in your dashboard, and you can use it just like a normal imgproxy url!

I've been using it just for my dev environment, but have only racked up 53 seconds of "billable time", Pretty sweet! Let me know if you run into any trouble, I'll see if i can help!
