### ISSUE TITLE
SVG to WEBP loses transparent layer

### ISSUE THREAD

**Issue by legopin** [imgproxy/imgproxy#412]
```
imgproxy version: 12.13.1
IMGPROXY_ENABLE_WEBP_DETECTION=true
```
We are noticing that certain SVG images with opacity layers in them turns into black blobs when converted to WEBP output. I tried searching in the upstream libvips library but could not find a relevant issue. 

Could anyone point us in the right direction to resolve the issue?

Comparison Screenshot
![Screen Shot 2020-06-03 at 2 37 49 PM](https://user-images.githubusercontent.com/15863509/83603957-e5b22400-a5a7-11ea-8508-43418430f251.png)

Original SVG
[product5_5514b08f.svg.zip](https://github.com/imgproxy/imgproxy/files/4721384/product5_5514b08f.svg.zip)

Converted WEBP
[image.webp.zip](https://github.com/imgproxy/imgproxy/files/4721387/image.webp.zip)

**Comment by DarthSim** [comment]
Hey!
This SVG uses `mix-blend-mode` CSS property which is still in the draft stage and isn't supported by librsvg.

**Comment by legopin** [comment]
Thank you, that explains it. 
I didn't even know this property existed until today. 

I'll close this issue for now since there is nothing to do at the moment but wait for `mix-blend-mode` to pass draft stage and get implemented in librsvg
