### ISSUE TITLE
FromHTTPRequest error installing on ubuntu

### ISSUE THREAD

**Issue by waroo** [imgproxy/imgproxy#428]
I followed the instructions at https://docs.imgproxy.net/#/installation for Ubuntu

When I enter `GO111MODULE=on \
  CGO_LDFLAGS_ALLOW="-s|-w" \
  go get -u github.com/imgproxy/imgproxy/v2
`

I get the following error:
`# github.com/imgproxy/imgproxy/v2
go/pkg/mod/github.com/imgproxy/imgproxy/v2@v2.13.1/errors_reporting.go:68:42: sentry.Request literal.FromHTTPRequest undefined (type sentry.Request has no field or method FromHTTPRequest)`

My environment is:
go version go1.14.4 linux/amd64
Ubuntu 20.04 LTS (GNU/Linux 5.4.0-37-generic x86_64)

**Comment by DarthSim** [comment]
Hey!
For some reason, `go get` doesn't use package versions from `go.mod`. I updated the installation manual, please follow the new instructions.
