### ISSUE TITLE
examples incorrectly encode key/salt into hex

### ISSUE THREAD

**Issue by waroo** [imgproxy/imgproxy#434]
The example files at https://github.com/imgproxy/imgproxy/tree/master/examples show the key and salt encoded into hexadecimal before sending to the server.  This is incorrect as it doesn't work in hex.  They should be a normal string.

The server environment variable stores the key and salt in hexadecimal but the client does not.

**Comment by DarthSim** [comment]
Hey!
Sorry, I don't understand what's wrong with storing key/salt pair on the client side encoded to hex.

**Comment by waroo** [comment]
When I send the key/salt to the server as hex encoded, the server gives an invalid signature or forbidden response.  However, when I send the key/salt to the server as an unencoded string it works fine.

**Comment by DarthSim** [comment]
Don't know if this is still an issue for you, but.

Taking the Go example, the key and the salt the way they are defined in the example ARE hex-encoded strings:

```go
key := "943b421c9eb07c830af81030552c86009268de4e532ba2ee2eab8247c6da0881"
salt := "520f986b998545b4785e0defbc4f3c1203f22de2374a3d53cb7a7fe9fea309c5"
```

They should be sent to the server just as they defined in the example:

```
IMGPROXY_KEY="943b421c9eb07c830af81030552c86009268de4e532ba2ee2eab8247c6da0881"
IMGPROXY_SALT="520f986b998545b4785e0defbc4f3c1203f22de2374a3d53cb7a7fe9fea309c5"
```

Thus I don't see why you treat this as an error.

**Comment by waroo** [comment]
Exactly, the key and salt should be sent to the server as they appear in the string.

However in the swift example it converts it to hex which is the issue.

```
let key = "943b421c9eb07c830af81030552c86009268de4e532ba2ee2eab8247c6da0881".hexadecimal()!;
let salt = "520f986b998545b4785e0defbc4f3c1203f22de2374a3d53cb7a7fe9fea309c5".hexadecimal()!;
```

If you take out `.hexadecimal()!` the code will work.

**Comment by DarthSim** [comment]
I'm absolutely not familiar with Swift, but it looks like `hexdecimal` function decodes hex-encoded string that is correct approach.
