### ISSUE TITLE
Non-latin characters in downloadable filename causes error

### ISSUE THREAD

**Issue by pySilver** [imgproxy/imgproxy#437]
Looks like filename cannot contain accent characters. I'm getting "Forbidden" response from imgproxy every time filename contains some non-latin characters. For instance: `Srebrne czółenka Pepe Jeans z zamszu` (if fails even if urlencoded).

I guess it's a bug, since most (all?) OS will let you save file with such characters or it will handle it itself.

**Comment by DarthSim** [comment]
Fixed in master. The `latest` image will be updated soon.

**Comment by DarthSim** [comment]
The fix is released in `v2.14.0`
