### ISSUE TITLE
ico to ico format error: libMagick error: NoDecodeDelegateForThisImageFormat `PNG'

### ISSUE THREAD

**Issue by legopin** [imgproxy/imgproxy#442]
## ENV
imgproxy:v2.13.1

## Expected Behavior

given ICO source image and no processing options, imgproxy should return ICO image

[favicon_0f22de08.ico.zip](https://github.com/imgproxy/imgproxy/files/4951979/favicon_0f22de08.ico.zip)

## Actual Behavior
Error found resulting from libvips or imageMagick

```
{ "level": "error", "stack": "/app/vips.go:213 main.(*vipsImage).Save
/app/process.go:770 main.processImage
/app/processing_handler.go:189 main.handleProcessing
/app/server.go:85 main.withCORS.func1
/app/router.go:100 main.(*router).ServeHTTP
/usr/local/go/src/net/http/server.go:2808 net/http.serverHandler.ServeHTTP
/usr/local/go/src/net/http/server.go:1896 net/http.(*conn).serve
/usr/local/go/src/runtime/asm_amd64.s:1374 runtime.goexit", "method": "GET", "request_id": "AP_aeKwgAba3HauaylCZP", "error": "magicksave_buffer: libMagick error: NoDecodeDelegateForThisImageFormat `PNG' @ error/blob.c/ImageToBlob/2010
", "msg": "Completed in 293.836262ms /9jMofShodG7zCHibMRxkrQVVSGToBVb28t1dg2YUHlY/Z3M6Ly9pbWcubWVlcGNsb3VkLmNvbS9hc3NldHMvYWRtaW4vZmF2aWNvbl8wZjIyZGUwOC5pY28", "status": 500.0 }
```

I'm not sure what options imgproxy uses for libvips and imageMagick, so I'm unable to open issue at those libraries. 
Why would there be PNG errors in an ICO image?

**Comment by DarthSim** [comment]
Hey!

The issue is fixed in v2.14.1.

After digging it I'm surprised that it worked before :)
ICO is in fact a container that can contain BMP or PNG images. The problem was that I used Imagemagick to save ICOs but I built ImageMagick without PNG support. Now I reworked ICO saving flow so it doesn't need ImageMagick at all.

**Comment by legopin** [comment]
Thank you for the quick fix. 

Never knew the world of image formats was so complicated

**Comment by legopin** [comment]
Yes verify v2.14.1 fixed the issue for us. 

Thank you once again
