### ISSUE TITLE
Alpha background color

### ISSUE THREAD

**Issue by sagebind** [imgproxy/imgproxy#443]
Currently the `background` option supports RGB colors to set a background color behind a thumbnail, but it would be very useful for us to also support alpha channel (RGBA) background colors. For example, you could set a partially-transparent background of #99999933 which would result in a partially transparent thumbnail for formats that support it (PNG, WebP, etc). Formats that don't support it (e.g. JPEG) would probably just lose the alpha channel like they already do when the source image contains transparent pixels.

**Comment by DarthSim** [comment]
Hey Stephen!
The main purpose of the `background` option is to remove alpha. I don't even sure if `vips_flatten` would work with colors with alpha channels. Could you give me the use case for the background with alpha?

**Comment by sagebind** [comment]
One example would be to supply a single color that would be transparent if the returned format supports it and a desired color if not; for example, having a background of `#AAAAAA00` would be transparent if a PNG is requested, but gray if a JPEG was requested. Another example would be embedding something on a website where a slight gray shading is desired with a partially-transparent gray background color behind any areas that were originally transparent in the image. Since these links are often generated en-masse without any specific knowledge about individual images being used, this is sometimes a useful feature.

This is an existing feature that we provide customers, and we were hoping that we could transition our image backend fully to imgproxy without removing any customer features.

**Comment by DarthSim** [comment]
Do I remember right that you use the Pro version?

**Comment by sagebind** [comment]
That's correct, this is for [@Widen](https://github.com/Widen).

**Comment by DarthSim** [comment]
I'll add `background_alpha` (`bga`) option to Pro then.

**Comment by DarthSim** [comment]
@sagebind I added [background_alpha](https://docs.imgproxy.net/#/generating_the_url_advanced?id=background-alpha-) to the latest build of Pro, you can test it. The new version will be available soon.

**Comment by molcikas** [comment]
@DarthSim We tried out the background_alpha option and it works great for the image itself, but it doesn't work correctly on the padding when using `resizing_type:fit`. The padding is opaque and either solid black or solid white depending on the source image.
