### ISSUE TITLE
Quality Configuration

### ISSUE THREAD

**Issue by xdougx** [imgproxy/imgproxy#448]
Hello, I'm trying to setup quality with:

```
ENV IMGPROXY_QUALITY=90
```

but the image size isn't change, so is needed to configure something else?

**Comment by DarthSim** [comment]
Hey Douglas!

The difference between 80 (default) and 90 is almost invisible in most cases. If you aren't sure that your quality setting is making an effect, try to set some low value.
Also, the quality setting affects only JPEG, WebP, and TIFF.
