### ISSUE TITLE
Poor aliasing artifacts when resizing a lossy WebP image

### ISSUE THREAD

**Issue by sagebind** [imgproxy/imgproxy#450]
We are seeing a couple examples of poor aliasing and transparency artifacts when resizing some types of images. In particular, we are using WebP images as our source files because they support transparency and lossy compression for large images in the same format. However, it seems like imgproxy is generating some puzzling visual artifacts with certain WebP images which do not occur if the same image is given to imgproxy in either PNG or TIFF format or as a lossless WebP.

Here is an example source image that reproduces this behavior:

[alpha-resize-source-lossy.webp.zip](https://github.com/imgproxy/imgproxy/files/4996172/alpha-resize-source-lossy.webp.zip)

(GitHub doesn't allow me to attach a WebP file directly, so here's a screenshot of what it looks like. The gray areas are fully transparent and are shown that way by my image viewer.)

![alpha-resize-source-lossy webp-screenshot](https://user-images.githubusercontent.com/2192863/88827444-93e4df00-d18f-11ea-9a3b-0e1dcb5b1741.png)

Note that the white rectangle in this image is slightly angled at the bottom and uses transparent aliasing to represent that. We then try to use this image as a source and apply a resizing operation to produce a smaller thumbnail. The imgproxy path looks like this: `/insecure/width:300/bG9jYWw6Ly8vRG93bmxvYWRzL2FscGhhLXJlc2l6ZS1zb3VyY2UtbG9zc3kud2VicA.png`

And here's the image that imgproxy produces:

![alpha-resize-output1](https://user-images.githubusercontent.com/2192863/88827872-1b325280-d190-11ea-92a3-cf6e8a4ef8b5.png)

Note that there are some gray areas around the edges where aliasing was used that seemed to come out of nowhere, as I would expect all the pixel colors to remain white with varying alpha levels. What is interesting is that this _only_ seems to happen when the source file is a lossy WebP. If the source file is an equivalent PNG for example, imgproxy produces a thumbnail like this one:

![alpha-resize-output2](https://user-images.githubusercontent.com/2192863/88828288-a7447a00-d190-11ea-9d46-013be2e3d604.png)

Note that all the pixel colors are fully white at varying alpha levels, and so here on GitHub it looks like just whitespace because the alpha areas blend with the white page to make fully white. The output is the same when using a TIFF or a _lossless_ WebP as the source as well. Here is the source file in other formats that produce the above thumbnail:

- [alpha-resize-source.png.zip](https://github.com/imgproxy/imgproxy/files/4996226/alpha-resize-source.png.zip)
- [alpha-resize-source.tif.zip](https://github.com/imgproxy/imgproxy/files/4996228/alpha-resize-source.tif.zip)
- [alpha-resize-source-lossless.webp.zip](https://github.com/imgproxy/imgproxy/files/4996229/alpha-resize-source-lossless.webp.zip)

Also note that if we run the original image through imgproxy _without_ resizing, then no such artifacts are produced. I've tried all the supported resizing algorithms as well to no avail.

We are hoping that this is a bug that can be fixed so that we don't have to make changes to our previewing stack to work around this.

**Comment by DarthSim** [comment]
Hey Stephen!

imgproxy utilizes WebP's scale-on-load feature to speed up resizing and decrease memory footprint. Since you say that this bug doesn't occur with the other formats, I bet this is the reason for the artifacts. Try to disable scale on load with `IMGPROXY_DISABLE_SHRINK_ON_LOAD=1` and see if it helps.

**Comment by sagebind** [comment]
Thanks for the timely response! I'll give that a try and report back.

**Comment by DarthSim** [comment]
Lossy WebP uses YUV 4:2:0 pixel encoding while lossless WebP uses ARGB. YUV may produce not very good results for some images, and I bet scaling-on-load aggravates this.

**Comment by sagebind** [comment]
That makes a ton of sense of what we are seeing, thanks for sending me down the right direction. We've decided to use lossless WebPs for some images based on their characteristics. Thanks for your expertise!

Closing as I don't think any changes are needed.
