### ISSUE TITLE
Potential code quality issues found

### ISSUE THREAD

**Issue by chsatyap** [imgproxy/imgproxy#451]
I forked this repo a while ago and ran a DeepSource analysis on it. DeepSource found a variety of different issues categorized based on their types and severity which you can view [here](https://deepsource.io/gh/chsatyap/imgproxy/).

Brief description -
Anti-Patterns: 27
Bug Risks: 6
Security Issues: 9

You can find a detailed description and fixes for some of them [here](https://deepsource.io/gh/chsatyap/imgproxy/issues/?category=recommended).

Please let me know what issues you'd like to focus on fixing and I'd be happy to take a look into it. Also, you can choose to hide certain types of issues too (if you wish to ignore them or you believe it is a false positive). I'd also be happy to send a patch with the DeepSource configuration file with the required fixes.

You can find the required configuration file for DeepSource [here](https://github.com/chsatyap/imgproxy/blob/master/.deepsource.toml).

**Comment by DarthSim** [comment]
Hey!
Thanks for the advice, but I already have golangci-lint configured, and I think it's just enough. I prefer to run linters before commit locally razer than fix linting errors afterward.
