### ISSUE TITLE
Upgrade to libvips 8.10.0

### ISSUE THREAD

**Issue by legopin** [imgproxy/imgproxy#457]
Hi, 
We are currently using v2.14.1.
libvips 8.10 is out which fixed a GIF loading error. 

gifload_buffer: bad frame size
https://github.com/libvips/libvips/issues/1701

Please consider updating to
https://github.com/libvips/libvips/releases/tag/v8.10.0

Thanks for your hard work, this is a really great library

**Comment by jbergstroem** [comment]
Looks like the base docker image already landed 8.10.0, so this'll likely be part of the next release.

**Comment by DarthSim** [comment]
Yep, libvips is updated to 8.10.0 in the latest build. I'm still preparing the release.

**Comment by DarthSim** [comment]
Released `v2.15.0` with libvips 8.10
