### ISSUE TITLE
[Watermark] Please tell me how to create text water mark

### ISSUE THREAD

**Issue by haiduong87** [imgproxy/imgproxy#458]
Hi all,

Please help me (as title).
I can't find related document :(

Thank you!

**Comment by legopin** [comment]
Imgproxy currently doesn't seem to support text based watermarks. However, you could potentially create an image that contains the text and set it as the watermark using the directions here:
https://docs.imgproxy.net/#/watermark

**Comment by haiduong87** [comment]
Thanks @legopin,

I tried to combine imgproxy and https://maketext.io/ and achieve what I want.
- Create svg from text
- Use svg as watermark data (url or base64)
