### ISSUE TITLE
Issue with JP2 (JPG-2000) image

### ISSUE THREAD

**Issue by mcjansen** [imgproxy/imgproxy#460]
I have a couple of JPEG-2000 images that can't be converted by imgproxy. It will give the  "Source image type not supported" error.

ImageMagick converts them without any problems.

Is it because imgproxy doesn't support JPEG 2000? Or is there an issue with the images?

Here is an example of an image that will give this error:
https://www.dropbox.com/s/l9l7bi3k5t4668a/img.jpg?dl=0

And I have included more information about the file.

Any thoughts?

Thanks,

Marco

root@0a293fe0fe2f:/app# identify -verbose img.jpg
Image: img.jpg
  Format: JP2 (JPEG-2000 File Format Syntax)
  Mime type: image/jp2
  Class: DirectClass
  Geometry: 2086x2071+0+0
  Units: Undefined
  Colorspace: sRGB
  Type: TrueColor
  Base type: Undefined
  Endianess: Undefined
  Depth: 8-bit
  Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
  Channel statistics:
    Pixels: 4320106
    Red:
      min: 13  (0.0509804)
      max: 255 (1)
      mean: 219.527 (0.86089)
      standard deviation: 54.3338 (0.213074)
      kurtosis: 1.51581
      skewness: -1.81752
      entropy: 0.685798
    Green:
      min: 8  (0.0313725)
      max: 255 (1)
      mean: 206.131 (0.808357)
      standard deviation: 68.4111 (0.268279)
      kurtosis: 1.49448
      skewness: -1.82655
      entropy: 0.703963
    Blue:
      min: 9  (0.0352941)
      max: 255 (1)
      mean: 200.6 (0.786667)
      standard deviation: 54.8693 (0.215174)
      kurtosis: 1.54437
      skewness: -1.8299
      entropy: 0.693616
  Image statistics:
    Overall:
      min: 8  (0.0313725)
      max: 255 (1)
      mean: 208.753 (0.818638)
      standard deviation: 59.2047 (0.232175)
      kurtosis: 1.75247
      skewness: -1.83274
      entropy: 0.694459
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: white
  Border color: srgb(223,223,223)
  Matte color: grey74
  Transparent color: black
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 2086x2071+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: JPEG2000
  Orientation: Undefined
  Properties:
    date:create: 2020-08-20T12:30:02+00:00
    date:modify: 2020-08-20T12:30:02+00:00
    signature: 0f38ac08937aa7eddbdf7cbb08d0ff7111b9ac4c4cb3bcdf995cbbb3f5e6fcc2
  Artifacts:
    filename: img.jpg
    verbose: true
  Tainted: False
  Filesize: 1.02961MiB
  Number pixels: 4.32011M
  Pixels per second: 4.90921MB
  User time: 0.860u
  Elapsed time: 0:01.879
  Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org

**Comment by DarthSim** [comment]
That's right, JP2 is not supported by imgproxy. Since libvips doesn't support JP2, the only currently possible way to load it is to use ImageMagick. I try to minimize its usage, and since I doubt that JP2 is somehow popular now, I'd rather not add its support to imgproxy.
Of course, there is always an option to add JP2 support to libvips, but I don't think it worth it.

**Comment by mcjansen** [comment]
Tx. I'll use ImageMagick as fallback.

**Comment by gdub01** [comment]
I've hit the same problem with jpg2000 images... @mcjansen were you able to solve that with the ImageMagick included in the standard imgproxy docker container? It looks like it includes ImageMagick, but I wonder is there a setting you toggled with an env var or something to make jpg2000 images hit imagemagick instead of libvps or did you solve it with a separate image magick instance?

**Comment by mcjansen** [comment]
In my setup, all incoming images are first processed by ImageMagick. And after that processing step, they are served via imgproxy. ImageMagick is running in another container.
