### ISSUE TITLE
Disable auto-rotation option

### ISSUE THREAD

**Issue by mcjansen** [imgproxy/imgproxy#463]
In issue https://github.com/imgproxy/imgproxy/issues/160 @DarthSim suggested:
_Well, maybe it makes sense to add a config option to disable autorotation. If you have more images with incorrect exif-ifd0-Orientation than with correct ones, the option will help you a little._

In our setup, we have a lot of images with incorrect orientation. Disabling autorotation would be great for us. 

Are there plans to include this in an upcoming release?

**Comment by mcjansen** [comment]
I have created a PR https://github.com/imgproxy/imgproxy/pull/465 that adds a config option to disable autorotation.

**Comment by mcjansen** [comment]
Thanks for the feedback! I'll pick it up later this week.

**Comment by DarthSim** [comment]
`IMGPROXY_AUTO_ROTATE` config and [auto_rotate](https://docs.imgproxy.net/#/generating_the_url_advanced?id=auto-rotate) processing option were added to the latest build.

**Comment by mcjansen** [comment]
Excellent news!
