### ISSUE TITLE
Is it possible to stick imgproxy to the one host?

### ISSUE THREAD

**Issue by Oglan** [imgproxy/imgproxy#464]
I would like to send requests with relative path but all images should be taken from one specific server. Is it possible?

For instance, instead of `http://imgproxy.example.com/AfrOrF3gWeDA6VOlDG4TzxMv39O7MXnF4CXpKUwGqRM/fill/300/400/sm/0/plain/http://example.com/images/curiosity.jpg@png` I would like to use following url: `http://imgproxy.example.com/AfrOrF3gWeDA6VOlDG4TzxMv39O7MXnF4CXpKUwGqRM/fill/300/400/sm/0/images/curiosity.jpg@png`

**Comment by legopin** [comment]
It sounds like a base URL could solve your issue.
https://docs.imgproxy.net/#/configuration?id=miscellaneous

> IMGPROXY_BASE_URL: base URL prefix that will be added to every requested image URL. For example, if the base URL is http://example.com/images and /path/to/image.png is requested, imgproxy will download the source image from http://example.com/images/path/to/image.png. Default: blank.

**Comment by Oglan** [comment]
Thanks, that's exactly what I need 👍
