### ISSUE TITLE
Incorrect jpg resizing when using dpr equal to 0.5 or less

### ISSUE THREAD

**Issue by Yankovsky** [imgproxy/imgproxy#472]
First of all thank you for a great product!

I use dpr values less than zero to shrink images while preserving original aspect ratio. This approach works fine for png, but for some reason it doesn't for jpg images and dpr values less or equal than 0.5.

I've prepared a reproduction scenario, here are results:
![http://s.csssr.ru/U02D248T6/2020-09-07-21-37-41-01tqn_.jpg](http://s.csssr.ru/U02D248T6/2020-09-07-21-37-41-01tqn_.jpg)

You can reproduce test case above by starting imgproxy docker on 8080 port and opening code below in a browser:
```html
<img src="https://i0.wp.com/cdn-prod.medicalnewstoday.com/content/images/articles/325/325466/man-walking-dog.jpg" alt="">
<img src="http://localhost:8080/insecure/dpr:0.501/plain/https://i0.wp.com/cdn-prod.medicalnewstoday.com/content/images/articles/325/325466/man-walking-dog.jpg@jpg" alt="">
<img src="http://localhost:8080/insecure/dpr:0.5/plain/https://i0.wp.com/cdn-prod.medicalnewstoday.com/content/images/articles/325/325466/man-walking-dog.jpg@jpg" alt="">
```

I've tried different png and jpg images and get the same results for all of them, so I think that the problem lies in either jpg library imgproxy is using or in a way imgproxy pass params to this library. I've also looked through this repo's source code, but haven't found anything connected to problems I'm facing.

One more interesting thing I've noticed – jpg with dpr 0.5 is actually a 0.25 version of the original image.

Thank you!

**Comment by DarthSim** [comment]
My bad. Fixed in the latest build

**Comment by Yankovsky** [comment]
Thanks!
