### ISSUE TITLE
Keep exif data in proxied images

### ISSUE THREAD

**Issue by rhyst** [imgproxy/imgproxy#473]
Hello,

Is it possible to keep exif data in the proxied images? 

Not sure if this clashes with the pro `/info/` endpoint which I could also use but it is unclear to me how a person can use the pro version for a personal website.

Thanks

**Comment by legopin** [comment]
Hi, I believe there are two ways to do it. 

One is the global config, controlling exif stripping for jpeg & webp

`IMGPROXY_STRIP_METADATA`
https://docs.imgproxy.net/#/configuration?id=miscellaneous

The other one is a processing option on a case by case override
https://docs.imgproxy.net/#/generating_the_url_advanced?id=strip-metadata
