### ISSUE TITLE
Extend does not take DPR into account

### ISSUE THREAD

**Issue by sagebind** [imgproxy/imgproxy#477]
When using both `dpr` and `extend`, I would expect `extend` to cause the image size to be doubled with `dpr:2`, but instead `extend` appears to be only extending the image until it reaches the requested width and height, rather than `width * dpr` and `height * dpr`.

This is undesirable, as `dpr` is preferred over multiplying each input number by hand since it handles the defaults correctly and automatically otherwise.

Tested on imgproxy pro 2.14.1.

#### Base image

`w:480/h:480/dpr:1.0/resizing_type:fit/ex:1/bg:999999`

<details>
  <summary>Result:</summary>

![480x480x1](https://user-images.githubusercontent.com/2192863/93534849-76b8cb00-f90b-11ea-8cd1-4105c876d55d.png)

</details>

#### With DPR at `2.0`

`w:480/h:480/dpr:2.0/resizing_type:fit/ex:1/bg:999999`

This is not the output I expected, I expected the result to be visually similar to the value of `dpr:1.0`, except double the pixel size. Note how `extend` appears to be ignored here, though I suspect that it was extending up to the literal 480x480 as requested without multiplying first.

<details>
  <summary>Result:</summary>

![480x480x2](https://user-images.githubusercontent.com/2192863/93535120-f050b900-f90b-11ea-920f-2216a795c8ca.png)

</details>

#### Scaling manually

`w:960/h:960/dpr:1.0/resizing_type:fit/ex:1/bg:999999`

This is when the width & height are multiplied by 2 by hand instead of using `dpr`. I'd expect using `dpr:2` to produce this result.

<details>
  <summary>Result:</summary>

![960x960x1](https://user-images.githubusercontent.com/2192863/93535134-f777c700-f90b-11ea-8e78-a27b2ca2aa0e.png)

</details>

**Comment by DarthSim** [comment]
Fixed in the latest build
