### ISSUE TITLE
SVG detection fails when file encoding is not UTF-8

### ISSUE THREAD

**Issue by legopin** [imgproxy/imgproxy#491]
## ENV
```
imgproxy version: 2.15.0
```

Problematic SVG file
```
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
```
[iso-8859-1.svg.zip](https://github.com/imgproxy/imgproxy/files/5414988/iso-8859-1.svg.zip)

## Expected Behavior
Given source image is SVG encoded with iso-8859-1, when requesting the image with `.svg` extension, the output should be svg image passed through per [documentation](https://docs.imgproxy.net/#/image_formats_support?id=svg-support)

## Actual Behavior
imgproxy returns HTTP status 422 "Source image type not supported".

After looking at the code, it seems like the go XML parser library expects the files to be encoded in utf-8
https://github.com/imgproxy/imgproxy/blob/8696be2b251ca41ac07a2d6712cf38e7e0a3c9af/imagemeta/svg.go#L42
> A Decoder represents an XML parser reading a particular input stream. The parser assumes that its input is encoded in UTF-8.
[xml parser doc](https://golang.org/pkg/encoding/xml/#Decoder)

However in Adobe Illustrator there is an option to save files with different encodings
Encoding

> Determines how characters are encoded in the SVG file. UTF (UnicodeTransformation Format) encoding is supported by all XML processors. (UTF‑8 is an 8‑bit format; UTF‑16 is a 16‑bit format.) ISO 8859‑1 and UTF‑16 encoding do not preserve file metadata.

https://helpx.adobe.com/fi/illustrator/using/saving-artwork.html

**Comment by legopin** [comment]
Looks like the xml package does have a way to convert non utf-8 characters to utf-8
https://golang.org/pkg/encoding/xml/#Decoder
```
// CharsetReader, if non-nil, defines a function to generate
// charset-conversion readers, converting from the provided
// non-UTF-8 charset into UTF-8. If CharsetReader is nil or
// returns an error, parsing stops with an error. One of the
// CharsetReader's result values must be non-nil.
CharsetReader func(charset string, input io.Reader) (io.Reader, error)
```

**Comment by legopin** [comment]
Possible conversion method
```
mport "golang.org/x/text/encoding/charmap"

func makeCharsetReader(charset string, input io.Reader) (io.Reader, error) {
    if charset == "ISO-8859-1" {
        // Windows-1252 is a superset of ISO-8859-1, so should do here
        return charmap.Windows1252.NewDecoder().Reader(input), nil
    }
    return nil, fmt.Errorf("Unknown charset: %s", charset)
}
```
https://stackoverflow.com/questions/34712015/unmarshal-multiple-xml-items

**Comment by DarthSim** [comment]
This should be fixed in the latest build.

**Comment by legopin** [comment]
Hi @DarthSim would you mind releasing a new build that contains this fix? The last release image was before this

**Comment by DarthSim** [comment]
Hey @legopin! Sorry, it was a long time since the last release. I'll release 2.16.0 on Monday.
