### ISSUE TITLE
Add processing option for manually rotating image

### ISSUE THREAD

**Issue by PhilippSchreiber** [imgproxy/imgproxy#493]
We have images w/o metadata that are rotated by 90°. We need to rotate them in a transformation. Since rotating is already there (by exif metadata) – would it be hard to add another processing option to achieve this?

**Comment by wilg** [comment]
I need this too – my use case involves nondestructive rotation. I know libvips supports this easily.

**Comment by DarthSim** [comment]
[rotate](https://docs.imgproxy.net/#/generating_the_url_advanced?id=rotate) processing option was added to the latest build.
