### ISSUE TITLE
[Question] Is there a way to serve local files without knowing the extension?

### ISSUE THREAD

**Issue by PedroD** [imgproxy/imgproxy#500]
I want to serve a local file without mentioning the exact extension.

Eg.: If .JPG is not present search for .PNG before sending a 404.

Something like

`local:///logos/evil_martians`
or
`local:///logos/evil_martians.*`
or
`local:///logos/evil_martians.(jpg|png)`

Is this possible?

Thank you! <3

**Comment by DarthSim** [comment]
Hey!
Do you have a use case for this?

**Comment by PedroD** [comment]
> Hey!
> Do you have a use case for this?

Yes. I'm serving files locally and these files are maintained by several people on the server, which can upload them having any format between jpg, jpeg, png, gif, etc.

Also, each image has a unique id as a name, so that urls to the images can be deterministically generated. Eg. let's say that I want image with name xxx (this id is known by a third party app trying to access this image file), but I don't know if the image is jpg, png, etc.

I have 3 solutions to this:

* have each third party app guessing the file extension by trial and error (slow and hackish solution that would need to be replicated in all third party apps) 

* convert all image files to a single format (jpg for eg) on upload (not always possible, for eg. if the user is using ftp to upload images, then we need to ask the user to manually convert the images)

* have the imgproxy server to try a list of formats by a given order before returning the 404 placeholder image (simple, clean, scalable and centralized solution)

**Comment by DarthSim** [comment]
The best practice, in this case, will be to store the full filename of the images so no part of your system won't need to "guess" it.

I see this "guessing" feature as overcomplicating in imgproxy context, and it looks like a very niche feature. So I rather not add it. Feel free to fork this repo and patch [the filesystem transport](https://github.com/imgproxy/imgproxy/blob/master/fs_transport.go) though. Don't be afraid of Go, it's pretty simple :)
