### ISSUE TITLE
Concurrency in benchmark

### ISSUE THREAD

**Issue by riccardomessineo** [imgproxy/imgproxy#519]
Hi there,
  I'm a little bit confused about the the benchmark file (https://github.com/imgproxy/imgproxy/blob/master/BENCHMARK.md).

Above it's written that "Concurrency was set to 8" and in the benchmarking section you use 4 as concurrency (of requests).

By setting concurrency to 8, did you mean that you ran 8 imgproxy instances at the same time or was it just a typo?

**Comment by DarthSim** [comment]
Hey Riccardo!

All the tested tools were configured to process up to 8 images simultaneously, but `ab` was configured to make 4 requests simultaneously. That's why you see `Concurrency Level: 4` in the benchmark results.

**Comment by riccardomessineo** [comment]
To recap:

1. One instance of Imgproxy
2. IMGPROXY_CONCURRENCY set to 8
3. ab simultaneous requests set to 4

Thanks DarthSim 👍

**Comment by DarthSim** [comment]
No problem!
