### ISSUE TITLE
go-nanoid compatibility

### ISSUE THREAD

**Issue by toonvd** [imgproxy/imgproxy#525]
Hi

At the moment, the router is not compatible with the new go-nanoid version:
https://github.com/matoous/go-nanoid/commit/68b72474732cdc7bd8198c02d4af9c94846000df

For this version, `nanoid.Nanoid()` should become `nanoid.New()`.

https://github.com/imgproxy/imgproxy/blob/9e3a1c6c2a4085ae1038787e72420ec2e6bb30c3/router.go#L79

Just a heads up to be careful when updating this dependency. (It also broke installation with `go get` for me but that is easily bypassed)

**Comment by DarthSim** [comment]
Hey!

Thanks for the warning!

> It also broke installation with `go get` for me

Yeah, it turned out that `go get` completely ignores all the go mod stuff in most cases. That's why I rewrote the installation manual to use `go build`.
