### ISSUE TITLE
Can the preset be excluded from the URL signature?

### ISSUE THREAD

**Issue by nayakravi** [imgproxy/imgproxy#526]
We have a single page app. We need to fetch a thumbnail when displaying the image, but we need a different resolution when editing it. Right now, it looks like, we have to create 2 versions of each image URL for these 2 options. I was wondering if there is any reason the preset needs to be included in the signature? If it is outside the signature, then we only need to send one signed version of the url to the front end and it can fetch multiple presets using the same signed URL. Do you see any issues with this?

**Comment by DarthSim** [comment]
Hi Ravi,

Currently, the signature generation process is pretty simple: get the path, sign it. If we start to modify the path, this will lead to complications that may lead to errors in the signature generation process.

Also, this is a minor breach of security. Cutting the presets part from the signed path means that the signature will be valid for the path without presets, which means that an attacker will be able to request originally sized images. I'm pretty sure you don't want this especially if you encode images to PNG, AVIF, or GIF.

If you still want to use the flow you described, you can disable the signature and combine `IMGPROXY_ONLY_PRESETS` with `IMGPROXY_BASE_URL`.
