### ISSUE TITLE
Don't strip color space / P3 color space support

### ISSUE THREAD

**Issue by wilg** [imgproxy/imgproxy#539]
iPhones take photos in P3 color space, but imgproxy strips out all the metadata (which is good!) but this includes the color space data. This means photos taken on an iPhone don't look right.

Here's a related issue on ruby-vips that I filed before I started using imgproxy which explains how to do this operation in vips: https://github.com/libvips/ruby-vips/issues/248 (Basically, just leave the `icc-profile-data` metadata header and remove everything else.)

**Comment by DarthSim** [comment]
The `latest` build transforms ICC profiles to sRGB to be able to remove the profile from the image. However, I'm going to add the ability to keep the profile.

**Comment by DarthSim** [comment]
`IMGPROXY_STRIP_COLOR_PROFILE` config and [strip_color_profile](https://docs.imgproxy.net/#/generating_the_url_advanced?id=strip-color-profile) processing option were added to the latest build.
