### ISSUE TITLE
"fast and secure on-the-fly image prosessing [sic]"

### ISSUE THREAD

**Issue by camelpunch** [imgproxy/imgproxy#545]
I shared imgproxy.net with my team on Slack and their first reaction was the typo in the meta description of the home page!
![Screenshot from 2021-02-04 09-36-14](https://user-images.githubusercontent.com/141733/106873655-968b3880-66cc-11eb-9c41-73105f3e2527.png)

**Comment by DarthSim** [comment]
Ugh, thanks, man! 🤦
