### ISSUE TITLE
Preserving original image quality

### ISSUE THREAD

**Issue by levnovikov** [imgproxy/imgproxy#547]
I have a project where photographers publish their works.
We would like to be able to preserve the original image quality set by the author (JPEG Quality), but at the same time resize the image to an acceptable size (for example, 1800 on the larger side).
So I ask you to add the sameq parameter to the quality option.

Thanks in advance!

**Comment by DarthSim** [comment]
Hey Lev!
Unfortunately, I don't see this as possible:
1. JPEG doesn't store the quality factor it was saved with.
2. Processing an image requires decoding and encoding it back. This basically means that in the case of JPEG the image quality (not the quality factor) will drop with each reencoding.
