### ISSUE TITLE
Support a per-request fallback image

### ISSUE THREAD

**Issue by wilg** [imgproxy/imgproxy#548]
I would really like to have the fallback image be set by my application server on a per-request basis, for example to have several fallback options seeded by the user id, or just to make it easier to configure. My main image is on S3 but the fallback would probably be a HTTPS URL.

Also, a plug for https://github.com/imgproxy/imgproxy/issues/487!

**Comment by DarthSim** [comment]
Hey @wilg!
The `fallback_image_url` option vere added to imgproxy Pro v3.0.0.beta1.

You can subscribe to our imgproxy Pro v3 [Early Access program](https://www.producthunt.com/upcoming/imgproxy)
