### ISSUE TITLE
Running out of memory when processing SVG files with large view box

### ISSUE THREAD

**Issue by enstyled** [imgproxy/imgproxy#550]
I am not sure what the problem is, but when I try to process the attached SVG file to PNG, imgproxy memory consumption explodes and it crashes. I am running v2.16.0 on Heroku:

```
Started /insecure/width:128/height:128/plain/path-to-svg/2494618@png
(imgproxy:4): GLib-GObject-WARNING **: 16:26:53.764: value "0.000720" of type 'gdouble' is invalid or out of range for property 'scale' of type 'gdouble'
Process running mem=1279M(250.0%)
Error R15 (Memory quota vastly exceeded)
```

It works fine if I try to set the size at 512x512 or above, but anything lower seems to crash it.

The source SVG file is peculiar because:
 - view box is crazy large `viewBox="0 0 355572 355572"`
 - there is an element with `id="图层_x0020_1"`
 - contains elements with large sizes `height="51185" width="33977"`

I have tried enabling `IMGPROXY_DEVELOPMENT_ERRORS_MODE`, but I don't get any additional errors.

[test.svg.zip](https://github.com/imgproxy/imgproxy/files/5966957/test.svg.zip)

(I had to zip the SVG file, as GitHub does not allow SVG uploads.)

**Comment by DarthSim** [comment]
Hey Emil!

For some reason, libvips limits the minimal value of scale for `vips_svgload`. I managed to bypass this in the latest build.

**Comment by enstyled** [comment]
Thank you for looking into this, Sergey!

I will test and report back when the next release is out.

**Comment by DarthSim** [comment]
`v2.16.1` includes the fix

**Comment by enstyled** [comment]
I can confirm the fix is working correctly. Thank you so much for the fast reaction! ❤️
