### ISSUE TITLE
VIPS crop/extract_area

### ISSUE THREAD

**Issue by wilg** [imgproxy/imgproxy#551]
I'm somewhat confused if imgproxy is able to perform cropping in the same way as vips.

My current code uses `crop`/`extract_area`: https://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-extract-area.

I think it may not be possible to do this with imgproxy at the moment? If not, would love to add support for this vips function. If it is possible, would love to know how.

**Comment by DarthSim** [comment]
Hey Wil,

imgproxy does support crop before resize with the [crop](https://docs.imgproxy.net/#/generating_the_url_advanced?id=crop) option. The analog of

```c
vips_extract_area (in, out, 10, 20, 100, 200, NULL);
```

is 

```
.../crop:100:200:nowe:10:20
```

**Comment by wilg** [comment]
Ah, I think it was the gravity that was throwing me for a loop. Thanks!
