### ISSUE TITLE
would you mind to add a docker-compose configuration to the DOC

### ISSUE THREAD

**Issue by EhsanSarshar** [imgproxy/imgproxy#555]

**Comment by legopin** [comment]
@EhsanSarshar 

A docker-compose file is a way to use the docker files provided, but I'm not sure is within the scope of this repo to provide that in documentation. 

However, would you mind providing more details so others might be able to help you better:

1. What are you trying to achieve? 
2. What have you tried so far?
2. What difficulty did you run into while using imgproxy in docker-compose?

**Comment by EhsanSarshar** [comment]
I mean just a sample docker-compose file. because most of the time we configure it as a docker file.
