### ISSUE TITLE
Floating point exception after upgrading from 2.13.1 to 2.16.1

### ISSUE THREAD

**Issue by palkan** [imgproxy/imgproxy#573]
Hey-hey!

We've just tried to upgrade our Heroku installation to the latest version and faced the following issue:

![image](https://user-images.githubusercontent.com/1516722/109792570-b149c200-7c24-11eb-8720-ec9599e68ff6.png)

Unfortunately, do not have any other information for now.
/cc @pcreux

**Comment by pcreux** [comment]
Looking at the logs, it seems that the following image was "Started" four times but never completed: https://gist.githubusercontent.com/pcreux/d067cfc0ddb5d3071cebc48d62b4e43e/raw/922da3142f6d71124f53c358dc17f205d37ce98d/ecctajm403r91uztkycx047ihjgf.webp

Let me know if you can reproduce that issue.

**Comment by DarthSim** [comment]
@pcreux Yup, you found it! I'll try to dig it.

**Comment by DarthSim** [comment]
The source of the issue was fixed in libvips by this PR: https://github.com/libvips/libvips/pull/1935. I updated dependencies in the Docker image, so `v2.16.2` works as expected.

**Comment by DarthSim** [comment]
And thanks for the sample!

**Comment by pcreux** [comment]
Thank you @DarthSim !

Would it make sense to version the docker images? I find it a bit counter-intuitive that re-deploying the same image on March 4th would fix this issue. Also, if the updated dependency introduced another bug (say, for animated heic with squirrels) we have no way to easily deploy the March 3rd image.

Do you have any recommendations to prevent such errors from crashing imgproxy on Heroku? In our case, Heroku [gave up](https://devcenter.heroku.com/articles/dynos#dyno-crash-restart-policy) after imgproxy crashed twice in a row. Could imgproxy handle and recover from such errors? Or could it (somehow) manage a cluster of processes and restart them on crash? Or is there a docker image around with extra tooling (nginx, upstart?!) to keep imgproxy alive?

**Comment by DarthSim** [comment]
> Would it make sense to version the docker image? I find it a bit counter-intuitive that re-deploying the same image on March 4th would fix this issue. Also, if the updated dependency introduced another bug (say, for animated webp with squirrels 😅) we have no way to easily deploy the March 3rd image.

What do you mean? Docker images are versioned: https://hub.docker.com/repository/docker/darthsim/imgproxy/tags?page=1&ordering=last_updated

> Do you have any recommendations to prevent such errors from crashing imgproxy on Heroku? In our case, Heroku gave up after imgproxy crashed twice in a row. Could imgproxy handle and recover from such errors?

imgproxy catches and handles every error it can catch. Unfortunately, this kind of error can't be caught. The good news is that this kind of error is very rare.

> Or could it (somehow) manage a cluster of processes and restart them on crash? Or is there a docker image around with extra tooling (nginx, upstart?!) to keep imgproxy alive?

Well, this is the responsibility of the system where you launch your app, in your case - Heroku, but Heroku lets you down here. Upstart and friends won't help you either. However, you can use a wrapper-script that will restart a process every time it exits with non-zero status:

```bash
until imgproxy; do
    echo "imgproxy crashed with exit code $?.  Respawning.." >&2
done
```

You need to build a Docker image on top of imgproxy's one, add this script to it and use it as`ENTRYPOINT`. This should be quite enough to handle crashes without stoping a dino.

**Comment by pcreux** [comment]
Hey @DarthSim, thank you for your reply!

> Docker images are versioned

Well, they are... but the Docker image tagged `v2.16.2` was replaced on March 4th with updated dependencies. I would expect a tagged image to be immutable to be confident that I'm deploying the exact same image across environments.

> Heroku lets you down here

Not the first nor the last time. :D

`until imgproxy; do` is much simpler than `upstart`. I'll give that a try.

Thank you!

**Comment by DarthSim** [comment]
> Well, they are... but the Docker image tagged v2.16.2 was replaced on March 4th with updated dependencies.

No, it wasn't. Updated deps is the only diff between 2.16.1 and 2.16.2, you can check it yourself in commits.

**Comment by pcreux** [comment]
Oh, @DarthSim, I'm so sorry, my mistake. I thought that I was already on 2.6.2.
