### ISSUE TITLE
Configure imgproxy in docker?

### ISSUE THREAD

**Issue by sheriffmarley** [imgproxy/imgproxy#574]
I'm currently locking into imgproxy and I'm consufed how to configure imgproxy with docker. 

I read the article https://12factor.net but I'm not sure how to configure imgproxy within the docker container. Do I configure it inside the container or am I doing it outside and pass the file to the container?

**Comment by DarthSim** [comment]
imgproxy is configured with environment variables. When using Docker ones can be set with the `-e`/`--env` or `--env-file` flags.
