### ISSUE TITLE
avif error="heifsave: Unsupported compression\n"

### ISSUE THREAD

**Issue by frankenbubble** [imgproxy/imgproxy#578]
Hi,

I built libvips 8.10.5 , and imgproxy 2.16.2 , everything works ok except avif formats.  requesting an avif output of a jpg origin, I get 

error="heifsave: Unsupported compression\n"

the vips commandline tool can handle the image and convert it ok,  and I wrote a small php script with libvips that also appears to handle it ok.  
There are no errors in building imgproxy, I can only assume it's a linked library issue, how can I debug further ?

**Comment by DarthSim** [comment]
libvips should be built with libheif support (looks like you did this). libheif should be built with rav1e or libaom support.

**Comment by frankenbubble** [comment]
yep, that was it,  build libheif with libaom support, and it's all good, thanks !
