### ISSUE TITLE
min-height and min-width

### ISSUE THREAD

**Issue by iaK** [imgproxy/imgproxy#598]
Imgix has a neat function to specify a minimum height and width.

It enables you to resize smaller images, while bigger images are untouched.
That functionality would be awesome to see in imgproxy.

More about the feature [here](https://docs.imgix.com/apis/rendering/size/min-w)

**Comment by legopin** [comment]
@iaK 
Hi, I'm just another imgproxy user here.

I took a look at the link you provided on minimum-width, and I think this feature is currently available in imgproxy under a different name.



## imgix sample
Let me reiterate the example to make sure I got it right.
Minimum-Width

![Screen Shot 2021-03-29 at 4 49 36 PM](https://user-images.githubusercontent.com/15863509/112811671-e116a900-90ae-11eb-8781-4fb6f471f9f8.png)

Given an original image that is
https://assets.imgix.net/unsplash/alley.jpg
3744×5616

When specifying `fit=crop&h=200&min-w=300`
you would expect the image to be cropped and then stretched to fit a width of 300x200

This seems to be different than what you described:
> It enables you to resize smaller images, while bigger images are untouched.

![Screen Shot 2021-03-29 at 4 53 53 PM](https://user-images.githubusercontent.com/15863509/112812192-65692c00-90af-11eb-9dc5-9d0eff3613b9.png)


## Imgproxy Equivalent

I wonder if setting `resize:fill` provides you with the desired result.
https://docs.imgproxy.net/#/generating_the_url_advanced?id=resizing-type

Sample Resizer on imgproxy.net
![Screen Shot 2021-03-29 at 5 00 47 PM](https://user-images.githubusercontent.com/15863509/112813141-79615d80-90b0-11eb-8d42-f8b1039b15a2.png)
![Screen Shot 2021-03-29 at 5 01 13 PM](https://user-images.githubusercontent.com/15863509/112813151-7b2b2100-90b0-11eb-95b9-bcb6cadfcbd6.png)

**Comment by iaK** [comment]
Thanks for your answer @legopin!

What min-width and min-height brings to the table is that larger images will be unaffected. Say if you have one 100x100 image and a 500x500 image and set rs:fill:300:300 - it will resize both images. What i want is the 100x100 image to become 300x300, but the large 500x500 image should keep its size.

**Comment by legopin** [comment]
Ah I see, the documentation on imgix was confusing then. This is what you meant right?

Large image remaining the same.

![Screen Shot 2021-03-29 at 5 49 12 PM](https://user-images.githubusercontent.com/15863509/112819512-41114d80-90b7-11eb-86f2-f497e0194051.png)

**Comment by DarthSim** [comment]
Hey everyone!
`min-width` & `min-height` were added to v3.0.0.beta1.

You can try the OSS version of `v3.0.0.beta1`, or you can subscribe to our imgproxy Pro v3 [Early Access program](https://www.producthunt.com/upcoming/imgproxy)
