### ISSUE TITLE
Slow thumbnail generation for avif extension

### ISSUE THREAD

**Issue by dannyvw** [imgproxy/imgproxy#600]
We are using the docker container darthsim/imgproxy:v2.16.2 with default configuration and generating avif thumbnails (from a .jpeg file) is very slow, mostly more than 7 seconds. v2.16.1 looks a few seconds faster but still more than 4 seconds. Do you have any idea?

**Comment by DarthSim** [comment]
Well, AVIF is a damn slow format ¯\_(ツ)_/¯

**Comment by dannyvw** [comment]
It is.. but is there something we can do about it? Or is this something we need to deal with?

**Comment by DarthSim** [comment]
As I said, AVIF is slow, it's in its nature. We use a pretty fast encoder, and it's still slow. So, yeah, here's no choice but to live with this.

**Comment by dannyvw** [comment]
Too bad, maybe it will be better in the future. But thanks for the information.
