### ISSUE TITLE
IMGPROXY_ENABLE_DEBUG_HEADERS=true does not change headers

### ISSUE THREAD

**Issue by shuggiefisher** [imgproxy/imgproxy#606]
Is this because the debug header is `Set()` after `WriteHeader()` has been called?

Behavior observed using the latest and v2.16.2 docker containers.

**Comment by DarthSim** [comment]
Ouch, how could I miss this while reviewing the PR... Thank you! Fixed in v2.16.3 and latest.

![](https://img.17qq.com/images/crrsuswqaqx.jpeg)
