### ISSUE TITLE
Is the figure larger than 5000X5000 all equal to failure ？

### ISSUE THREAD

**Issue by RootPeter** [imgproxy/imgproxy#613]
If all images over 5000x5000 fail, all are "Invalid source image", how can this ensure that the images can be accessed normally?

**Comment by DarthSim** [comment]
Hey @RootPeter!

If you take a look at the logs, you'll see the `Source image resolution is too big` error. That's because 5000x5000 is larger that the resolution allowed by default. Increasing `IMGPROXY_MAX_SRC_RESOLUTION` config will solve the issue.

**Comment by RootPeter** [comment]
Are you sure this parameter exists in the help file? I don't seem to have this global variable

**Comment by DarthSim** [comment]
Absolutely sure https://docs.imgproxy.net/#/configuration?id=security

**Comment by RootPeter** [comment]
6000X6000 How much should I write?

**Comment by DarthSim** [comment]
6000*6000 = 36000000 = 36 megapizels

**Comment by RootPeter** [comment]
thank ,bro
