### ISSUE TITLE
`dpr` doesn't respect `enlarge`

### ISSUE THREAD

**Issue by alexfedoseev** [imgproxy/imgproxy#615]
I'm not sure if it's by design, but when `dpr` value that supposed enlarged resulting image gets passed, the resulting image gets enlarged even if `enlarge` is set to `false`.

**Comment by DarthSim** [comment]
Hi Alex!
It's made by design. The behavior may change in v3 but not it works like this.

**Comment by alexfedoseev** [comment]
Gotcha, thanks! I handled it on my side. Let me know if I should close this issue.
