### ISSUE TITLE
Google Cloud Storage suggestion

### ISSUE THREAD

**Issue by Tokenyet** [imgproxy/imgproxy#625]
Just try the connection to my bucket with pure docker commands.

```
docker run -v /home/myaccount/Imgproxy/:/auth/ --env IMGPROXY_BIND=80 --env IMGPROXY_USE_GCS=true --env IMGPROXY_GCS_KEY=/auth/gcp-key.json --env IMGPROXY_ALLOWED_SOURCE=gs:// -p 8000:80 -it darthsim/imgproxy
```

This won't work and I don't know why with the following error message:
`FATAL   [2021-04-27T12:22:57Z] Can't create GCS client: dialing: invalid character '/' looking for beginning of value `

Instead, using `GOOGLE_APPLICATION_CREDENTIALS` from the [official documentation](https://cloud.google.com/docs/authentication/production), works!

```
docker run -v /home/myaccount/Imgproxy/:/auth/ --env IMGPROXY_BIND=:80 --env IMGPROXY_USE_GCS=true --env GOOGLE_APPLICATION_CREDENTIALS=/auth/gcp-key.json --env IMGPROXY_ALLOWED_SOURCE=gs:// -p 8000:80 -it darthsim/imgproxy
```

So I suggest we should use `GOOGLE_APPLICATION_CREDENTIALS` instead of `IMGPROXY_GCS_KEY` to decouple the dependency.

Just my opinion, because I can't find how to fix It. This issue is a suggestion and also a bug report 😄

**Comment by DarthSim** [comment]
Hey!

When using `IMGPROXY_GCS_KEY`, you need to provide the content of the key, not the path to it.

**Comment by Tokenyet** [comment]
> Hey!
> 
> When using `IMGPROXY_GCS_KEY`, you need to provide the content of the key, not the path to it.

Oh! I'm missing It! Thanks for point out the problem! I'm using GCP for years, thought It has the same conecpt 😰
