### ISSUE TITLE
Increased latency

### ISSUE THREAD

**Issue by autresrhumbs** [imgproxy/imgproxy#626]
Hello,

I am running the latest version of imgproxy using Google Cloud Run, but has the same issue with Scaleway.
At the beginning, images are processed within 1 sec but after a few days, I start to experience some latencies (sometimes up to 30 sec).

I usually set the resources to 2Gb of RAM and 2 CPUs, so should be enough I guess?

Do you have an idea of what could cause this?

Many thanks for your help. 
bruno.

**Comment by DarthSim** [comment]
Hey Bruno!
Sorry, can't say anything without metrics. Do you collect ones?

**Comment by autresrhumbs** [comment]
Hey!
I didn’t have metrics so far but your comment made me create a new relic account.
And latency mainly comes from image download and not image processing.
So nothing related to imgproxy then!

Thanks for the hint, I will investigate our network issues...
