### ISSUE TITLE
Developer requesting custom change to crypt.go & rebuild of docker image

### ISSUE THREAD

**Issue by claflico** [imgproxy/imgproxy#635]
We have a developer that has provided us with a modified crypt.go file and asking us to rebuild and deploy the custom docker image instead of the public docker image. 

Developer's explanation is: 
```
https://imgproxy.TEST_DOMAIN/insecure/plain/https://helpx.adobe.com/content/dam/help/en/photoshop/using/convert-color-image-black-white/jcr_content/main-pars/before_and_after/image-before/Landscape-Color.jpg

it's about the change of how we validate the url, the current validation will strict the image url from resizing the image on the fly
```

Updated crypt.go file is:

```
package main

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"errors"
)

var (
	errInvalidSignature         = errors.New("Invalid signature")
	errInvalidSignatureEncoding = errors.New("Invalid signature encoding")
)

type securityKey []byte

func validatePath(signature, path string) error {
	messageMAC, err := base64.RawURLEncoding.DecodeString(signature)
	if err != nil {
		return errInvalidSignatureEncoding
	}
	for i := 0; i < len(conf.Keys); i++ {
		if hmac.Equal(messageMAC, signatureFor( i)) {
			return nil
		}
	}

	return errInvalidSignature
}

func signatureFor(pairInd int) []byte {
	mac := hmac.New(sha256.New, conf.Keys[pairInd])
	mac.Write(conf.Salts[pairInd])
	expectedMAC := mac.Sum(nil)
	if conf.SignatureSize < 32 {
		return expectedMAC[:conf.SignatureSize]
	}
	return expectedMAC
}
```

Changes appear to be on line 23 & line 35.

If you don't mind helping, what would the impact of the changes be and is there any way we can achieve what the developer is asking by using environment variables?

**Comment by DarthSim** [comment]
Hi Cory,
This code removes the path from the signature calculation breaking the whole idea of signing the URL. Thus this change can't be made by using env vars.
However, if you want to completely disable the signature validation, you can set the empty key/salt pair.

**Comment by claflico** [comment]
Thank you Sergey for the reply. Am asking the developer to provide more specific details because they are claiming that images can't be formatted on the fly when we have IMGPROXY_KEY & IMGPROXY_SALT env vars configured in the deployment with the current publicly available image.
