### ISSUE TITLE
which file we can set configuration

### ISSUE THREAD

**Issue by kapilkarda** [imgproxy/imgproxy#636]
I have installed imgproxy and set up it via ubuntu service but I am unable to do setting environment variable I am trying to find .env file but I am unable to find it.

**Comment by DarthSim** [comment]
Hi Kapil,
imgproxy itself does not support env files. If you run imgproxy as a Docker container, you can use the `--env-file` argument. If you run it as a binary, you can write a wrapper over it with the needed env vars set.

**Comment by kapilkarda** [comment]
Hello @DarthSim ,

Thank you for your help.

I am not using docker I have installed separately, I am facing issue with IMGPROXY_MAX_SRC_RESOLUTION but I don't know where I can set this and after setting this do I have to restart the service

Thanks

**Comment by DarthSim** [comment]
Basically, you should somehow set env vars so imgproxy can see it. You can use some kind of wrapper like this:

```bash
IMGPROXY_BIND=":8080" \
IMGPROXY_MAX_SRC_RESOLUTION=30 \
imgproxy
```

And yes, as soon as a process sees env variables as they were set at the moment the process started, you'll need to restart the process when you change the variables.

**Comment by kapilkarda** [comment]
but @DarthSim , it is running from system services I don't know where I can set this env vars I tried to setup in config.go file as well as an export method but nothing is working.

**Comment by DarthSim** [comment]
I'm honestly not sure what you mean by "system services". I'd recommend you to use the official Docker image with `docker swarm` or `docker service` as it's a guaranteed way to get things working. There's plenty of potential issues you may face with a custom build.

**Comment by kapilkarda** [comment]
okay, but I want to solve it without docker :(

**Comment by kapilkarda** [comment]
Hello @DarthSim  I have setup with Docker now it is working fine thank you @DarthSim 

Can you please help me with how I can store my cached file to Azure for a long time, is there any env configuration for the same?

**Comment by Eideen** [comment]
This works:
````bash

#?/bin/bash

## interupt handler
trap 'echo $( date ) Imgproxy interrupted >&2; exit 2' INT TERM


#address and port or Unix socket to listen on. Default: :8080;
export IMGPROXY_BIND=:9001
# network to use. Known networks are tcp, tcp4, tcp6, unix, and unixpacket. Default: tcp;
export IMGPROXY_NETWORK="tcp"
# the maximum duration (in seconds) for reading the entire image request, including the body. Default: 10;
export IMGPROXY_READ_TIMEOUT="10"
#the maximum duration (in seconds) for writing the response. Default: 10;
export IMGPROXY_WRITE_TIMEOUT="10"

export IMGPROXY_QUALITY="50"

###         LOG
export IMGPROXY_LOG_FORMAT="pretty"
export IMGPROXY_LOG_LEVEL="INFO"

## Sign

export IMGPROXY_KEY="943b421c9eb07c830af81030552c86009268de4e532ba2ee2eab8247c6da0881"
export IMGPROXY_SALT="520f986b998545b4785e0defbc4f3c1203f22de2374a3d53cb7a7fe9fea309c5"

echo "startering Imgproxy"

/usr/local/bin/imgproxy

````

**Comment by DarthSim** [comment]
@kapilkarda imgproxy doesn't have any caching options. I recommend putting a caching proxy or CDN (CloudFront, Google Cloud CDN, Fastly, Cloudflare, etc) in front of imgproxy.
