### ISSUE TITLE
How to track 500 errors?

### ISSUE THREAD

**Issue by pySilver** [imgproxy/imgproxy#643]
I'm having an issue with imgproxy (?) which is not very clear. My CND reports there are ~2K 500 error responses daily observed. An indeed there are some errors in the logs regarding invalid original image urls. However its just few of them, like 4-5 a day and I'm not sure if its reported as 500 or 404 error.

Any clues how do I investigate the issue?

My setup is imgproxy -> traefik -> cnd (bunny.net).

I've checked the logs at traefik and imgproxy and havent found anything to that rate. Unfortunately there are no specific failure URLs (all reported 500 error imgproxy-urls are working fine every time I check it but it may be the result of bunny retries.

**Comment by pySilver** [comment]
Ok. Cloudflare says it's gateway timeout errors. Is it imgproxy issue? https://cln.sh/KqdShh

**Comment by DarthSim** [comment]
Hey!
Sorry for the delay, I was on vacation without access to GH.

Gateway timeout (504) means that your gateway (I guess it's traefik) didn't get a response from the origin (imgproxy) in the expected time. Try to increase traefik timeouts.

**Comment by pySilver** [comment]
@DarthSim makes sense, I'll try that. Does timeout errors are reported by imgproxy itself?

**Comment by DarthSim** [comment]
If you mean reporting to Honeybadger, Sentry, etc, then no, they're not reported. imgproxy just responds with 503 in case of timeouts.

**Comment by pySilver** [comment]
@DarthSim I've ment logging. Does such errors are bing reported with default  `IMGPROXY_LOG_LEVEL = info` ?

**Comment by DarthSim** [comment]
Yeah, sure:

```
ERROR   [2021-06-07T12:36:14Z] Completed in 1.890393855s /unsafe/rs:fill:312:312/wm:0.5:nowe/pd:10/plain/local:///animated_gif3.gif  request_id=8ZDeacYK9uhMIKbXV6OIp method=GET status=503 error="Timeout after 1.89033474s"
```

**Comment by pySilver** [comment]
@DarthSim what should I do when I see this type of errors:

```
Could not load image. Using fallback image: Get "https://static.convertiser.com/media/product_images/266/de47ed9c1bae4ec2da7af851d2a5a4d2/962c5d3b5e92d26b27e1d96b44c64f825a37536a.jpg": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

My timeouts are already increased to 20s

```
IMGPROXY_READ_TIMEOUT=20
IMGPROXY_WRITE_TIMEOUT=20
IMGPROXY_KEEP_ALIVE_TIMEOUT=20
IMGPROXY_DOWNLOAD_TIMEOUT=20
```

and yet, problem still happens every once in a while. Sometimes it's Cloudflare temporary issue, sometimes (surprisingly) AWS3. Sometimes this logs have different body:


```
Could not load image. Using fallback image: context deadline exceeded (Client.Timeout or context cancellation while reading body)
```

```
Could not load image. Using fallback image: Can't download image; Status: 502; <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```

As I can never catch this problem online (checking failing URLs always works) I was wondering if there is or planned connection retry functionality?

Is that possible that timeouts can be related to imgproxy itself. LA is low, but you know I can try to spawn more instances in case it may help mitigate timeouts (I feel it will not help and it's probably Cloudflare/s3 issues...)

**Comment by pySilver** [comment]
It's also would be nice to have requested URL in logs when something like `Could not load image.` happens. Otherwise it's kinda hard to track issues on backend level.

**Comment by DarthSim** [comment]
"context deadline exceeded" error kind means that the request for the source image was timed out. I'll try to change the message to something more informative.

As for image URLs in errors, imgproxy always logs URLs of failed requests, so you can determine the source URL from it.

**Comment by DarthSim** [comment]
> As for image URLs in errors, imgproxy always logs URLs of failed requests, so you can determine the source URL from it.

Sorry, this is not the case when using a fallback image. I'll try to do something here.

**Comment by DarthSim** [comment]
Added some improvements of error messages to `v2.16.5`

**Comment by pySilver** [comment]
@DarthSim thanks! I'll deploy it right away!
