### ISSUE TITLE
docker imgproxy, which is now all down

### ISSUE THREAD

**Issue by rustxj** [imgproxy/imgproxy#649]
I have tested numerous possibilities, memory problems, network problems, DNS problems, CPU without any load, all unavailable, I repull imgproxy is also the same, now imgproxy is completely unavailable?

CPU 3% ;
mem 533mb

code:

docker run -dt  -p 8080:8080 -e IMGPROXY_KEY=xxx -e IMGPROXY_MAX_SRC_RESOLUTION=9999 -e IMGPROXY_SALT=xxxx  -e IMGPROXY_USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36" -e IMGPROXY_WATERMARK_PATH=/root/dev.png -v /etc/resolv.conf:/etc/resolv.conf -v /root/dev.png:/root/dev.png -e  IMGPROXY_USE_ETAG=true -e IMGPROXY_CACHE_CONTROL_PASSTHROUGH=true -e IMGPROXY_TTL=99999999999999 darthsim/imgproxy:latest

**Comment by DarthSim** [comment]
Hey!
Sorry, I don't understand what do you mean by "completely unavailable".
