### ISSUE TITLE
PNGs with transparency and shadow: long processing and broken result

### ISSUE THREAD

**Issue by bsboris** [imgproxy/imgproxy#658]
Hello!

Here is the source image: 
![1624520111_f3a936](https://user-images.githubusercontent.com/591230/123223555-a66bb380-d4d9-11eb-92f1-7bd7c2c5c6ba.png)

Transformations: `rs:fit:1280:0:0` (but could be anything)

The result: 
![1624520111_f3a936-1](https://user-images.githubusercontent.com/591230/123223894-f64a7a80-d4d9-11eb-985e-e2c1f1e2464a.png)

And processing takes very long time, about 15 seconds.

**Comment by DarthSim** [comment]
Hey Eugene!

About the shadow bug:
I found the source of the bug and I'll fix it soon.

About the speed issue:
I didn't notice any speed issues with this image on my machine. However, your image is a 4MB file, and it may take a time to download it through a slow network. Also, PNG does not support a scale-on-load feature, so resizing it takes more time than resizing of JPGs or WebPs.

**Comment by DarthSim** [comment]
Broken result's fixed in `v2.16.5`

**Comment by bsboris** [comment]
Thanks! I can confirm that visual bug was fixed. 

We tried `v2.16.5` in production for couple of days with relatively high load, and it looks like there is performance regression in this version. Here is our LA chart to illustrate:  
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/591230/124238276-0c32ed80-db21-11eb-8442-b7fa2fb33ae8.png">

**Comment by DarthSim** [comment]
Fixed the regression and fixed a couple of things in v2.16.6
