### ISSUE TITLE
Hide original image url

### ISSUE THREAD

**Issue by Yegorov** [imgproxy/imgproxy#666]
Hello!
It possible hide (encrypt) original image url.
For example, if i add watermark (or blur filter) for preview, user can extract original image url and downloaded it.

I want instead of such url:
`http://localhost:8080/signature/rs:fill/w:500/h:500/g:sm/blur:2.0/el:0/plain/https://www.example.com/large_original_without_watermark.png`
something like this
`http://localhost:8080/signature/rs:fill/w:500/h:500/g:sm/blur:2.0/el:0/plain/encrypted_original_image_path.png`
or this
`http://localhost:8080/encrypted_options_and_original_image_path.png`

Or what are the suggestions that the user can not see and download the original image?

**Comment by DarthSim** [comment]
Hey Artem!

Well, there's no such feature, but here're some things you can do to hide the full source URL:
- If you store your images in some kind of storage (S3, GCS, Azure Blob Storage, etc), you can make the storage private and use imgproxy's integration with it.
- If the host of your source URLs is always the same, you can use `IMGPROXY_BASE_URL` to hide the host.
- Finally, you can create some endpoint on your side that checks User-Agent and redirects to the source image URL.

Of course, you can also make a PR with this feature ;)

**Comment by shinsenter** [comment]
@Yegorov my setup in #714 may help

**Comment by DarthSim** [comment]
Encrypted source URLs support was added to imgproxy Pro `v3.8.0`
