### ISSUE TITLE
strip_metadata doesn't actually strip all metadata for certain output formats

### ISSUE THREAD

**Issue by sagebind** [imgproxy/imgproxy#668]
Certain EXIF metadata is always included in imgproxy thumbnails regardless of the presence of the `strip_metadata:1` option. I would like all metadata to be stripped from the output, especially fields related to DPI (xres, yres, etc).

Sample source image:

![relaxation-mode](https://user-images.githubusercontent.com/2192863/125099715-ee740400-e09d-11eb-81b0-2dfa57994106.jpg)

Has this metadata:

```
$ exiftool relaxation-mode.jpg
ExifTool Version Number         : 12.00
File Name                       : relaxation-mode.jpg
Directory                       : .
File Size                       : 502 kB
File Modification Date/Time     : 2021:07:09 10:10:27-05:00
File Access Date/Time           : 2021:07:09 10:11:14-05:00
File Inode Change Date/Time     : 2021:07:09 10:10:27-05:00
File Permissions                : rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Image Width                     : 5120
Image Height                    : 3686
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:4:4 (1 1)
Image Size                      : 5120x3686
Megapixels                      : 18.9
```

When asking for a JPEG thumbnail, stripping metadata, the image produced has this metadata:

```
$ curl -s 'http://localhost:8181/insecure/w:640/sm:1/scp:1/plain/local:///relaxation-mode.jpg' | exiftool -
ExifTool Version Number         : 12.00
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Exif Byte Order                 : Little-endian (Intel, II)
Orientation                     : Horizontal (normal)
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Y Cb Cr Positioning             : Centered
Exif Version                    : 0210
Components Configuration        : Y, Cb, Cr, -
Flashpix Version                : 0100
Color Space                     : Uncalibrated
Exif Image Width                : 640
Exif Image Height               : 460
Image Width                     : 640
Image Height                    : 460
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 640x460
Megapixels                      : 0.294
```

Similarly, for WebP:

```
$ curl -s 'http://localhost:8181/insecure/w:640/sm:1/scp:1/plain/local:///relaxation-mode.jpg@webp' | exiftool -
ExifTool Version Number         : 12.00
File Type                       : WEBP
File Type Extension             : webp
MIME Type                       : image/webp
VP8 Version                     : 0 (bicubic reconstruction, normal loop)
Image Width                     : 640
Horizontal Scale                : 0
Image Height                    : 460
Vertical Scale                  : 0
Exif Byte Order                 : Little-endian (Intel, II)
Orientation                     : Horizontal (normal)
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Y Cb Cr Positioning             : Centered
Exif Version                    : 0210
Components Configuration        : Y, Cb, Cr, -
Flashpix Version                : 0100
Color Space                     : Uncalibrated
Exif Image Width                : 640
Exif Image Height               : 460
Image Size                      : 640x460
Megapixels                      : 0.294
```

For these two formats at least, it seems that you must instruct libvips to _not_ write a standard EXIF block with default values when writing the output. For example, [`vips_jpegsave()`](https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-jpegsave) has a `strip` option that should be set to `true`:

> If `strip` is set, no EXIF data, IPTC data, ICC profile or XMP metadata is written into the output file.

Similarly, [`vips_webpsave()`](https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-webpsave) also has a `strip` option:

> The writer will attach ICC, EXIF and XMP metadata, unless `strip` is set to `TRUE`.

I think the right behavior here would be to pass along the `strip_metadata` preference into the save routine so that if true, certain format writers can set their various `strip` options if requested.

It seems that "pixels per unit" is also included for PNG outputs:

```
curl -s 'http://localhost:8181/insecure/w:640/sm:1/scp:1/plain/local:///relaxation-mode.jpg@png' | exiftool -
ExifTool Version Number         : 12.00
File Type                       : PNG
File Type Extension             : png
MIME Type                       : image/png
Image Width                     : 640
Image Height                    : 460
Bit Depth                       : 8
Color Type                      : RGB
Compression                     : Deflate/Inflate
Filter                          : Adaptive
Interlace                       : Noninterlaced
Pixels Per Unit X               : 2835
Pixels Per Unit Y               : 2835
Pixel Units                     : meters
Image Size                      : 640x460
Megapixels                      : 0.294
```

but seeing as `vips_pngsave()` has no equivalent `strip` option, I don't know if anything can be done about that.

**Comment by DarthSim** [comment]
Hi Stephen!

Unfortunately, it is how it works :( Vips regenerates some EXIF fields unless `strip` is true. But we can't use `strip` since it will cut the ICC profile even if we want to keep it.

I'll think about what we can do here.

**Comment by DarthSim** [comment]
John says that these fields are required by JPEG spec: https://github.com/libvips/libvips/issues/1026#issuecomment-652803530.
Since the EXIF data generated by libvips is tiny (186 bytes) I'd rather keep it in the resulting image. Is there a specific reason why you need this data to be stripped?

**Comment by sagebind** [comment]
In particular we wanted to avoid including any sort of DPI-related metadata on the output file. Our customers tend to scrutinize any file that comes out of our system and they put a lot of stock in the DPI of such files, even when it doesn't make much sense to do so. Since thumbnails are not intended for print use whatsoever, we'd like to not have any specified DPI, or at the very least a constant DPI. As it is, it seems that by default libvips fills in the DPI with different values depending on the format when not specified.

If it absolutely must be present for some formats, then perhaps a way to _set_ the DPI to a particular value as a new parameter would work. I wouldn't expect such a parameter to affect the pixels themselves whatsoever, only DPI metadata.

**Comment by DarthSim** [comment]
libvips sets the DPI to 72 which is a kind of default DPI. At least, it's a default DPI in every single graphic software and lib I ever used :)

> As it is, it seems that by default libvips fills in the DPI with different values depending on the format when not specified, which is why our customers reported this as a concern.

As I see from your data, it sets 72 DPI for JPEG and WebP. It sets 2835 pixels per meter for PNG which is basically 72 DPI. It seems it's how the resolution tag works for PNGs.

**Comment by sagebind** [comment]
Yes, it does look like it is defaulting to 72 DPI if not specified, which is the reasonable default.

However, we don't always have control over the source files with which we are creating thumbnails over, and those files may have all sorts of DPI settings present. If we can't remove that metadata, then having an option to setting it to a constant value (e.g. 72 DPI) regardless of the source file would be a desirable feature for us.

**Comment by sagebind** [comment]
I just verified that `strip_metadata` sometimes seems to remove (or "reset") the DPI for some source formats and not others; perhaps this is still a bug then.

For example, when asking a JPEG from a JPEG:

```
$ exiftool generic-thumbnail.jpg
ExifTool Version Number         : 12.00
File Name                       : generic-thumbnail.jpg
Directory                       : .
File Size                       : 505 kB
File Modification Date/Time     : 2021:07:19 12:51:21-05:00
File Access Date/Time           : 2021:07:19 12:51:24-05:00
File Inode Change Date/Time     : 2021:07:19 12:51:21-05:00
File Permissions                : rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Resolution Unit                 : None
X Resolution                    : 1
Y Resolution                    : 1
[...]

$ curl -s 'http://localhost:8181/insecure/w:640/sm:1/scp:1/plain/local:///generic-thumbnail.jpg@jpg' | exiftool -
ExifTool Version Number         : 12.00
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Exif Byte Order                 : Little-endian (Intel, II)
Orientation                     : Horizontal (normal)
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Y Cb Cr Positioning             : Centered
Exif Version                    : 0210
Components Configuration        : Y, Cb, Cr, -
Flashpix Version                : 0100
Color Space                     : Uncalibrated
Exif Image Width                : 640
Exif Image Height               : 460
Image Width                     : 640
Image Height                    : 460
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 640x460
Megapixels                      : 0.294
```

Note how the resolution changes from 1 to 72 when `strip_metadata:true`, which is what I would expect. But when asking a JPEG of a WebP:

```
$ exiftool generic-thumbnail.webp
ExifTool Version Number         : 12.00
File Name                       : generic-thumbnail.webp
Directory                       : .
File Size                       : 146 kB
File Modification Date/Time     : 2021:07:09 09:23:31-05:00
File Access Date/Time           : 2021:07:19 12:51:20-05:00
File Inode Change Date/Time     : 2021:07:09 09:23:36-05:00
File Permissions                : rw-rw-rw-
File Type                       : WEBP
File Type Extension             : webp
MIME Type                       : image/webp
Profile CMM Type                : Linotronic
Profile Version                 : 2.1.0
Profile Class                   : Display Device Profile
Color Space Data                : RGB
Profile Connection Space        : XYZ
Profile Date Time               : 1998:02:09 06:49:00
Profile File Signature          : acsp
Primary Platform                : Microsoft Corporation
CMM Flags                       : Not Embedded, Independent
Device Manufacturer             : Hewlett-Packard
Device Model                    : sRGB
Device Attributes               : Reflective, Glossy, Positive, Color
Rendering Intent                : Perceptual
Connection Space Illuminant     : 0.9642 1 0.82491
Profile Creator                 : Hewlett-Packard
Profile ID                      : 0
Profile Copyright               : Copyright (c) 1998 Hewlett-Packard Company
Profile Description             : sRGB IEC61966-2.1
Media White Point               : 0.95045 1 1.08905
Media Black Point               : 0 0 0
Red Matrix Column               : 0.43607 0.22249 0.01392
Green Matrix Column             : 0.38515 0.71687 0.09708
Blue Matrix Column              : 0.14307 0.06061 0.7141
Device Mfg Desc                 : IEC http://www.iec.ch
Device Model Desc               : IEC 61966-2.1 Default RGB colour space - sRGB
Viewing Cond Desc               : Reference Viewing Condition in IEC61966-2.1
Viewing Cond Illuminant         : 19.6445 20.3718 16.8089
Viewing Cond Surround           : 3.92889 4.07439 3.36179
Viewing Cond Illuminant Type    : D50
Luminance                       : 76.03647 80 87.12462
Measurement Observer            : CIE 1931
Measurement Backing             : 0 0 0
Measurement Geometry            : Unknown
Measurement Flare               : 0.999%
Measurement Illuminant          : D65
Technology                      : Cathode Ray Tube Display
Red Tone Reproduction Curve     : (Binary data 2060 bytes, use -b option to extract)
Green Tone Reproduction Curve   : (Binary data 2060 bytes, use -b option to extract)
Blue Tone Reproduction Curve    : (Binary data 2060 bytes, use -b option to extract)
VP8 Version                     : 0 (bicubic reconstruction, normal loop)
Image Width                     : 5120
Horizontal Scale                : 0
Image Height                    : 3686
Vertical Scale                  : 0
Image Size                      : 5120x3686
Megapixels                      : 18.9

$ curl -s 'http://localhost:8181/insecure/w:640/sm:1/scp:1/plain/local:///generic-thumbnail.webp@jpg' | exiftool -
ExifTool Version Number         : 12.00
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Exif Byte Order                 : Little-endian (Intel, II)
Orientation                     : Horizontal (normal)
X Resolution                    : 25.4
Y Resolution                    : 25.4
Resolution Unit                 : inches
Y Cb Cr Positioning             : Centered
Exif Version                    : 0210
Components Configuration        : Y, Cb, Cr, -
Flashpix Version                : 0100
Color Space                     : Uncalibrated
Exif Image Width                : 640
Exif Image Height               : 461
Image Width                     : 640
Image Height                    : 461
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 640x461
Megapixels                      : 0.295
```

Note how the DPI of the output is 25.4. I'm not actually sure which field of the WebP file corresponds to the physical dimensions, but it seems like `strip_metadata:true` isn't resetting the DPI to 72 like it does for other formats.

**Comment by DarthSim** [comment]
@jcupitt Hi! Can I ask for your help here?

Context:
I remove all meta from the image before saving using `vips_image_remove`. But libvips regenerates EXIF data and @sagebind claims that it sets different DPIs for different images. Is there a way to completely strip meta or at least use a constant DPI for all images?

Thanks!

**Comment by DarthSim** [comment]
I got it, I need to reset `img->Xres` and `img->Yres` as well.
@jcupitt sorry for bothering you!

**Comment by jcupitt** [comment]
Hi @DarthSim,

libjpeg has a minimal set of exif that is required in all files, so libvips always attaches it. If you don't have this minimal set, at least some viewers will fail to open the file (from memory).

Resolution in JPEG is very annoying -- due to an accident of history, it can be given in EXIF and JFIF. If you give resolution in both places, some viewers become confused.

From memory, libvips tries to only use EXIF resolution (the more modern standard). If you build libvips without EXIF support, then it will set JFIF resolution, but the generated files may not work everywhere.

**Comment by jcupitt** [comment]
Oh heh, yes, from your point of view all you need to do is set `xres` and `yres` and the libvips JPEG writer ought to do the right thing for you.

Officially you're supposed to set xres/yres like this:

```C
vips_copy( image, &out, "xres", 12.3, "yres", 14.3, NULL);
```

Or you can get race conditions due to caching.

**Comment by DarthSim** [comment]
Thanks for the explanation! `vips_copy` is definitely a more proper way.

**Comment by DarthSim** [comment]
@sagebind Do I understand right that setting DPI to 72 when meta is stripped is ok for you?

**Comment by sagebind** [comment]
Yeah, if `strip_metadata` simply resets the DPI to 72, then that solves our problem.

**Comment by jcupitt** [comment]
Ooop, sorry, I was wrong (it's been too long).

Now I check I see `strip` will block all exif and jfif, so the jpeg file will have no resolution information. On load, you then get the default res, which is 72 DPI.

**Comment by DarthSim** [comment]
@jcupitt Unfortunately, `strip` is not an option as it removes ICC profiles as well. Anyway, resetting `xres` and `yres` on copy solves the issue. Thanks again!

@sagebind `v2.16.7` is ready to pull

**Comment by sagebind** [comment]
@DarthSim Just pulled, and it seems to be working as desired in all my example and bug report scenarios we got complaints about. Thanks! 👍 We'll put this into production shortly.
