### ISSUE TITLE
Caching converted images

### ISSUE THREAD

**Issue by dmke** [imgproxy/imgproxy#686]
Hi,

I haven't found anything in the docs, nor does the sources look like it's supported, but maybe I'm blind:

Does imgproxy cache the converted images somewhere, or does it always start the processing pipeline each time the same URL is hit? The ETag/If-Modified-Since handling may help if the *same* browser instance hits the same URL again, but does not if two different browser request the URL.

For my use case I'm interested in exchanging CPU time for storage space; ideally imgproxy could also keep track on the last access timestamp and auto-remove a cached item after a week or so. Is there something like this planned, and if not, would you be interested in a PR?

**Comment by DarthSim** [comment]
Hi Dominik,

imgproxy does not do any caching by design. Proper caching is not as trivial as it may seem. There are a lot of things that should be taken into account and a lot of mechanics that should be implemented like partial cache cleaning and stuff. So I prefer to concentrate on things that imgproxy does the best - processing your images - and to leave the caching stuff to the tools meant for this like CDNs and caching servers.

**Comment by dmke** [comment]
Hello Sergey,

thanks for the quick response. I do agree that caching is one of the two hard problems (actually cache invalidation, besides naming things and off-by-one errors :-)), and I applaud your preference to keep things simple.

Still, I believe that imgproxy might be the right place for this, because:

- it has access to the processing options,
- it has access to the configuration (especially `IMGPROXY_ENABLE_{WEBP,AVIF}_DETECTION`), and
- it can access to the source image (and maybe even it's ETag).

While the first two points is actually just the request path (save for the order of processing options) and the `Accept` header (when auto-support detection is enabled), a caching server in front of imgproxy will have a hard time detecting changes in the source image...

I'll close this for now though. I might come back with a prototype for this, if only for using it for my use case :-)

**Comment by DarthSim** [comment]
`IMGPROXY_ENABLE_{WEBP,AVIF}_DETECTION` sucks, and I hate this feature 😅 Especially because it causes problems with caching. I'm absolutely sure that the `<picture>` tag is the most proper way to get the image in the right format.

**Comment by dmke** [comment]
> I'm absolutely sure that the <picture> tag is the most proper way to get the image in the right format.

Sure, but in Rails, `imgproxy.rb` acts mostly as drop-in for the ActiveStorage URL generation. We'd need a helper to generate that tag, its `<source />` and fallback `<img />` (easily done, but... meh...)

I'm actually quite fond of the auto detection, as it let's me keep a simple/single `<img />` tag (kind of: here's a source image, imgproxy do the right thing). Also, I've come across a lot of Javascript widgets (currently: image sliders/galleries), which only accept one URL per image, not a proper source set...

I hope you intend to keep that feature, despite it having the aforementioned drawback 🙏
