### ISSUE TITLE
Response status code shouldn't be 404 if source is unavailable

### ISSUE THREAD

**Issue by matteocontrini** [imgproxy/imgproxy#701]
Hello,

in my use case I need to distinguish two cases:

- source image doesn't exist (anymore), in which case the source would return 404 and imgproxy should also return 404. (imgproxy already works like that)
- the source is unavailable and it timeouts or returns an HTTP error. In this case I expect imgproxy to return 500 or similar, not 404

This would allow 404 responses (maybe with a fallback image) to be cached at the CDN level to avoid useless requests for images that don't exist, while requests that fail with 500 would not be cached and instead retried.

If I'm not missing something, this is currently not possible. Thanks!

(Partially related to #487)

**Comment by DarthSim** [comment]
Hey @matteocontrini! This is a good idea, added this to `v3.0.0.beta2` and `latest`.
