### ISSUE TITLE
Support for IMGPROXY_ENABLE_PNG_DETECTION and IMGPROXY_ENFORCE_PNG

### ISSUE THREAD

**Issue by phoenix-bjoern** [imgproxy/imgproxy#705]
imgproxy already supports IMGPROXY_ENABLE_WEBP_DETECTION and IMGPROXY_ENFORCE_WEBP configurations to deliver a WebP image instead of the original image type in case the client's Accept HTTP header indicates its supporting it. This config is also available for AVIF.
IMHO it would make sense to support the same for PNG.

Currently the order/priority of formats seem to be hard coded ATM:

> imgproxy prefers AVIF over WebP. This means that if both AVIF and WebP detection/enforcement are enabled and the browser supports both of them, AVIF will be used.

Having a configuration like `IMGPROXY_IMAGE_TYPE_PREFERENCE=avif,webp,png` would give the user more control/freedom.

**Comment by DarthSim** [comment]
Hey Björn!
Unlike AVIF and WebP, PNG is supported by every modern browser, so I don't see any need for this feature.

**Comment by phoenix-bjoern** [comment]
https://caniuse.com/?search=png
Valid point. Will close the ticket.
