### ISSUE TITLE
Contribute a production ready docker-compose setup with nginx caching

### ISSUE THREAD

**Issue by shinsenter** [imgproxy/imgproxy#714]
@DarthSim 
Thanks for a great tool!

I created production ready server setup for imgproxy with Nginx caching using docker-compose.
・No troubles of Image URL signature.
・High availability and performance.
・Customizable serving fallback image.
・Flexible in customizing URL and origin servers without exposing imgproxy options.
・Easy SSL configuration with built-in HTTP/2 support.

Check it out: https://github.com/shinsenter/docker-imgproxy

I hope you consider mentioning my setup as an example to use imgproxy with docker-compose. 

Best regards

**Comment by shinsenter** [comment]
@ArvindhMangoleap 
CloudFront is just a CDN service, and I think it will help reduce the load on the origin server if you put my setup as origin server behind CloudFront.  Regarding CloudFront caching, I think you should consult and set it up by using CloudFront's control panel.

**Comment by DarthSim** [comment]
Hey @shinsenter!

I appreciate what you've done, yet I can't recommend this config as it doesn't use URL signatures so I can't call it secure.
