### ISSUE TITLE
Ability to skip processing for particular image with Query param

### ISSUE THREAD

**Issue by sashberd** [imgproxy/imgproxy#716]
Hi guys
I did not find this feature in your docs
Cam you add option to add some flag to query params, e.g. no_process=true, so it will be possible to turn off processing for particular image and not for all format (like it requested  #476 ) 
Thanks

**Comment by DarthSim** [comment]
Hey Alex!

We have [skip_processing](https://docs.imgproxy.net/generating_the_url?id=skip-processing) option which allows skipping processing of particular formats. The whole point of it as I see it is to skip processing of heavy formats like GIF when you don't know the source image format.

If you want to skip processing no matter what, it's better to use a direct link to the original image bypassing imgproxy.

**Comment by shinsenter** [comment]
@sashberd my setup in #714 may help

**Comment by legopin** [comment]
The newly released v3 seems to support this, you can list the format as no processing in the param
https://docs.imgproxy.net/generating_the_url?id=skip-processing
