### ISSUE TITLE
Gen url example error

### ISSUE THREAD

**Issue by quydox** [imgproxy/imgproxy#717]
Dear team,

Thanks for you source code, it works well with default php example gen url encoded

But it same path params is fixed in order /resize/width/height/gravity/enlarge...

I try to change 

```
<?php

$key  = '736563726574';
$salt = '68656C6C6F';

$keyBin = pack("H*", $key);
if (empty($keyBin)) {
    die('Key expected to be hex-encoded string');
}

$saltBin = pack("H*", $salt);
if (empty($saltBin)) {
    die('Salt expected to be hex-encoded string');
}

$resize    = 'fit';
$width     = '150';
$height    = '150';
$gravity   = 'ex:1';
$enlarge   = 'g:ce:0:0';
$extension = 'png';

$url        = 'https://domain.com/path/to/image/MP1904290005_BASIC_origin.jpg';
$encodedUrl = rtrim(strtr(base64_encode($url), '+/', '-_'), '=');

$path = "/{$resize}/{$width}/{$height}/{$gravity}/{$enlarge}/{$encodedUrl}.{$extension}";

$signature = rtrim(strtr(base64_encode(hash_hmac('sha256', $saltBin . $path, $keyBin, true)), '+/', '-_'), '=');

print(sprintf("http://localhost:8080/%s%s", $signature, $path)) . PHP_EOL;
```

It show Invalid URL

How can I use another processing option like preset, extend?

Thanks

**Comment by DarthSim** [comment]
Hey @quydox!
Sorry for the huge delay :(
You're trying to use the advanced options with the old basic URL format. Please, check out [the docs](https://docs.imgproxy.net/generating_the_url) or the new [PHP example](https://github.com/imgproxy/imgproxy/blob/master/examples/signature.php).
