### ISSUE TITLE
Latest tag points to beta version

### ISSUE THREAD

**Issue by jvincze84** [imgproxy/imgproxy#735]
Hi,

Your latest tag in dockerhub points to the 3.0.0.beta2.

```bash
docker run -it darthsim/imgproxy:latest imgproxy version
3.0.0.beta2
 ```

Is it just a mistake or you did it on purpose?
In the releases page the v.217.0 is marked as latest.

Thanks,
Janos Vincze

**Comment by DarthSim** [comment]
Hey @jvincze84!
The `latest` image is built from the `master` branch. v3 is in the `master` now.
