### ISSUE TITLE
Auto rotation does not work with HEIC source

### ISSUE THREAD

**Issue by bschulz87** [imgproxy/imgproxy#736]
Using Docker with Image darthsim/imgproxy:v2.17 requesting a HEIC image does not apply auto rotation. Converted to jpeg the file works.
Example-Repo: https://github.com/bschulz87/imgproxy-example

**Comment by DarthSim** [comment]
There's a huge problem with HEIC and orientation. There're two ways to define the orientation: EXIF and transformations. By HEIF specs, EXIF orientation should be just informative and shouldn't be used for processing. Yet some software set EXIF and doesn't set transformations. And it seems like Apple changes this behavior in every major iOS release 😖

https://github.com/strukturag/libheif/issues/227
https://github.com/libvips/libvips/pull/1680

**Comment by DarthSim** [comment]
@bschulz87 Could you tell me where you took this photo? I tried a lot of other HEICs and can't reproduce the problem.

Can it be the case that the photo is just supposed to be upside-down? In this case, everything fits: the photo is upside down and EXIF data inform us that it is.

**Comment by bschulz87** [comment]
Thanks for your reply. It's actually from a coworker who reported the problem. I'll do a test with another photo as well.

**Comment by bschulz87** [comment]
Can't reproduce it with certainty using other images.
