### ISSUE TITLE
Problem processing Sentry event: "release: Discarded invalid value"

### ISSUE THREAD

**Issue by martonsz** [imgproxy/imgproxy#739]
I am getting the following error when looking at a Sentry event.

```
There was 1 problem processing this event

release  Discarded invalid value
Reason   invalid character '/'
Value    imgproxy/2.17.0
```

It seems that Sentry server doesn't like the forward slash in the `relase` variable.

Sentry server version: ? We are using Cloud Sentry (latest release for the self hosted is [21.11.0](https://github.com/getsentry/self-hosted/releases/tag/21.11.0))
Imgproxy version: v2.17.0

**Comment by DarthSim** [comment]
Yup, we should use `@` instead of `/`. Fixed in `v3.0.0`

**Comment by martonsz** [comment]
I am running v3.0.0 now and trying to create a Sentry event. But I can't manage to create an error that is sent to Sentry.
I only manage to create warnings.


I have activated `IMGPROXY_REPORT_DOWNLOADING_ERRORS` in the Helm values.yaml to increase the chance to create a Sentry event.

```yaml
# ENV['IMGPROXY_REPORT_DOWNLOADING_ERRORS']
    # when `true`, imgproxy will report downloading errors.
    reportDownloadingErrors: true
```

What is an download error? I get the following log if the image is missing. But it is only a warning. Not an error.
```log
WARNING [2021-11-26T07:38:40Z] Could not load image https://storage.gra.cloud.ovh.net/v1/AUTH_secret/public/testing/monalisa-100-149-dont-exists.jpg. Using fallback image. Can't download source image: Status: 404; <html><h1>Not Found</h1><p>The resource could not be found.</p></html>
```

**Comment by martonsz** [comment]
I managed to create an error! `*ierrors.Error embed: parameter height not set`

And have confirmed that the `release` variable is now OK in v3.0.0! 🙂
