### ISSUE TITLE
Sentry events shows local IP instead of remote IP

### ISSUE THREAD

**Issue by martonsz** [imgproxy/imgproxy#740]
The sentry events are showing local IP e.g. `10.231.96.0` instead of the users real IP.

Our imgproxy runs in a kubernetes cluster and recieve traffic from an nginx ingress server.

The real remote IP  can be found in the header [X-Forwarded-For](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For).

I use the following golang code in one of our projects to get the remote IP. It checks several known headers for the IP. It found that not all proxies uses the same standard :(
I found the snippet on the internet and modified it so that it can handle comma separated values in `X-Forwarded-For`

```go
// getUserIP returns the public IP of the caller
func getUserIP(req *http.Request) string {
	var userIP string
	if len(req.Header.Get("CF-Connecting-IP")) > 1 {
		userIP = req.Header.Get("CF-Connecting-IP")
		return fmt.Sprint(net.ParseIP(userIP))
	} else if len(req.Header.Get("X-Forwarded-For")) > 1 {
		userIP = req.Header.Get("X-Forwarded-For")
		if index := strings.Index(userIP, ","); index > 0 {
			userIP = userIP[:index]
			userIP = strings.TrimSpace(userIP)
		}
		return fmt.Sprint(net.ParseIP(userIP))
	} else if len(req.Header.Get("X-Real-IP")) > 1 {
		userIP = req.Header.Get("X-Real-IP")
		return fmt.Sprint(net.ParseIP(userIP))
	} else {
		userIP = req.RemoteAddr
		if strings.Contains(userIP, ":") {
			return fmt.Sprint(net.ParseIP(strings.Split(userIP, ":")[0]))
		} else {
			return fmt.Sprint(net.ParseIP(userIP))
		}
	}
}
```

Another solution could be that you have a setting in imgproxy where you can choose which header to get client IP from?

**Comment by DarthSim** [comment]
Hey @martonsz! It looks like the Sentry package just uses `req.RemoteAddr`. I made some changes to rewrite `RemoteAddr` according to headers. Should work in `v3.0.0`.

**Comment by martonsz** [comment]
I can cofirm that this is now working in v3.0.0. Sentry is showing the users real IP.
Thank you @DarthSim !
