### ISSUE TITLE
Google Cloud Storage not working on v3

### ISSUE THREAD

**Issue by yoitsro** [imgproxy/imgproxy#741]
I _think_ think is to do with Google Cloud Storage, but it might not be. I'm running this on Google Cloud Run.

Message returned: `Source image is unreachable`

In the logs, I see a debug level message:

```
Can't download source image: parse "~)e\xd7M4\xdfM\x1cz\xda\xeey\x9d\xcc輽\xcdх\x9d\xa5\xb9\x9c\xb5\xd5͕ȵ\xa5\xb5\x85\x9d\x95̹\x91\x95ͅ\xb9\x84\xb9\xa5\xbc\xbd̵\x90\xc4\xdc\xc0\xc4\xe0\xd0ȵ\x94\xd8\xe4ܴ\xd0шش\xe0\xe4\xd4̴͌\xc1\x99\x94\xc0\xe1\x84ф\xc8\xd4": net/url: invalid control character in URL
```

**Comment by DarthSim** [comment]
Hey @yoitsro!
It looks like the problem is with the source URL encoding. Could you show the imgproxy URL you use?

**Comment by yoitsro** [comment]
https://hostname/wlcH58rn87TCKtApGPHIVG_VDuBxGFaMOkI6b8J_NTM/fill/1000/300/ce/true/Z3M6Ly9zdGFnaW5nLXVzZXItaW1hZ2VzLmRlc2FuYS5pby9zLTQ1ZjUwYTJmLTE1MmQtNGI4MS1iNzE4LTQ5YjdiOWU0MDE2Yw.webp

**Comment by DarthSim** [comment]
I see now. You're using an outdated URL format that was deprecated and was removed from v3. Please use the only supported formally known as "advanced" URL format: https://docs.imgproxy.net/generating_the_url
