### ISSUE TITLE
Source URL Not allowed with V3 and multiple sources

### ISSUE THREAD

**Issue by shakalandy** [imgproxy/imgproxy#749]
Hi,

Somehow the logic on  IMGPROXY_ALLOWED_SOURCES is broken with the update on V3.

We are having multiple allowed sources, for example:

  `    IMGPROXY_ALLOWED_SOURCES: s3://,https://*.example.com/,https://example.com/`

upgrading to v3 (Docker:latest) we are getting "Source URL is not allowed" as error message in the logs.
Downgrade to docker:v2 and delivery works as expected.

is there a config change needed or something else on multiple sources when upgrading to v3?

Thanks!

**Comment by DarthSim** [comment]
Hey @shakalandy!
Just checked your example, and everything works as expected. If you could reveal your real `IMGPROXY_ALLOWED_SOURCES` value and the URL that doesn't work, I'd help you better.

**Comment by shakalandy** [comment]
Hey @DarthSim,

The Domains are `api.kruu.com` and `kruu.com`.

The following error appears in V3 in the log:

```
{"log":"\u001b[33mWARNING\u001b[0m [2021-12-03T15:25:25Z] Completed in 427.258µs /RwB0fpLImw6vOCql_0pvePKtARF-N2OrlrTzhM_TMhU/fit/400/276/sm/0/aHR0cHM6Ly9hcGkua3J1dS5jb20vdXBsb2Fkcy9sb2NhdGlvbi1tZWRpYXMvMi81LzMvVHJhZm93ZXJrLU1hbm5oZWltLXJ1bmRlLVRpc2NoZS5qcGc  \u001b[1mrequest_id\u001b[0m=1DC4fBh3rxW-OQabUEXfA \u001b[1mmethod\u001b[0m=GET \u001b[1mstatus\u001b[0m=404 \u001b[1mclient_ip\u001b[0m=\"2a00:fb8:2077:3000:2833:7e81:e52b:93e2\" \u001b[1merror\u001b[0m=\"Source URL is not allowed: ~+x\\xd3M\\xbb\\xeaɴhttps://api.kruu.com/uploads/location-medias/2/5/3/Trafowerk-Mannheim-runde-Tische.jpg\"\n","stream":"stderr","time":"2021-12-03T15:25:25.918031557Z"}
``` 

Everything works fine with the same settings and just a downgrade to imgproxy:v2 docker image.

Will try again and may the force be with you.

**Comment by DarthSim** [comment]
You're using the deprecated basic URL format. v3 supports only the advanced one: https://docs.imgproxy.net/generating_the_url

**Comment by shakalandy** [comment]
Oh narf, thanks very much!

not an easy error message for that, but this will be it.
closing.

**Comment by DarthSim** [comment]
Yeah, I probably should add some kind of detection of the basic format with a proper error message. Too many users are confused with this.
