### ISSUE TITLE
Imgproxy for Digital Ocean Spaces

### ISSUE THREAD

**Issue by billypap1** [imgproxy/imgproxy#752]
Hello, we are using Digital Ocean as our Cloud Provider and for storing files Digital's Ocean Spaces. Can we configure Imgproxy to get files from Spaces (instead of S3, GCS, Azure)?

**Comment by DarthSim** [comment]
Hey @billypap1!

Since Spaces are S3-compatible, you should be able to use the S3 integration https://docs.imgproxy.net/serving_files_from_s3.

Here's a config example for the `nyc3` region (replace it with yours) that should work for you:

```
IMGPROXY_USE_S3=1
AWS_ACCESS_KEY_ID="your_spaves_key"
AWS_SECRET_ACCESS_KEY="your_spaces_secret"
IMGPROXY_S3_REGION ="nyc3"
IMGPROXY_S3_ENDPOINT="https://nyc3.digitaloceanspaces.com"
```
