### ISSUE TITLE
3.0.0 checksum changed

### ISSUE THREAD

**Issue by iMichka** [imgproxy/imgproxy#754]
Hi

Homebrew maintainer here. We shipped the 3.0.0  release a few days ago, but meanwhile the checksum of the release has changed. Can you confirm that this was a re-tag, and nothing was compromised on your side.

For reference: https://github.com/Homebrew/homebrew-core/pull/90670

**Comment by DarthSim** [comment]
Hey @iMichka! Yeah, I retagged 3.0.0 like a day after release. Sorry for the mess 😓

**Comment by iMichka** [comment]
No issue. We prefer that wrong releases get their tag deleted, and a new 3.0.1 is published instead. That's the best solution for these cases.
The git manual also states that retagging is a bad thing do: https://git-scm.com/docs/git-tag#_on_re_tagging
