### ISSUE TITLE
Etags + S3 causes intermittent errors

### ISSUE THREAD

**Issue by ricardobeat** [imgproxy/imgproxy#757]
If you enable `IMGPROXY_USE_ETAG` and `IMGPROXY_USE_S3` at the same time, every other request to an image fails:

- the first request succeeds, client receives `ETag` header
- on the second request, imgproxy forwards the ETag to S3
- S3 responds with a 304 Not Modified
- imgproxy barfs a `Can't download source image` error
- client receives 500, erases ETag
- 3rd request succeeds
- [repeat]

**Comment by DarthSim** [comment]
Hey! Thanks for catching this! Fixed in the latest build.
