### ISSUE TITLE
Save the images in the gcloud bucket

### ISSUE THREAD

**Issue by alimot22** [imgproxy/imgproxy#758]
In the imgproxy [documentation](https://docs.imgproxy.net/about_processing_pipeline),  it said `And finally, imgproxy saves the image to the desired format.`

i can't find anything in the documentation of how we can save the images, or how we can save the images in the desired format.

Can anyone help me about how can I save the images with the imgproxy on gcloud bucket or any other file storages?

**Comment by DarthSim** [comment]
Hey @alimot22!

imgproxy doesn't save the results anywhere

**Comment by ctaity** [comment]
we cannot save the result to a local or cloud storage for later use? 
for example, imgproxy servers an image, later the image is deleted, we cannot retrieve the img anymore

**Comment by DarthSim** [comment]
You can always develop a service that would do this for you
