### ISSUE TITLE
[Question] How i can use multiple watermarks?

### ISSUE THREAD

**Issue by approached** [imgproxy/imgproxy#759]
Hi @ all

Docs: https://docs.imgproxy.net/watermark?id=specifying-watermark-image

How i can use multiple watermarks?
Does me need 2 docker container for this Job?

**Comment by DarthSim** [comment]
Hi @approached!

Do you mean multiple watermarks on a single image or different watermarks on different images?

**Comment by approached** [comment]
... different watermarks on different images

**Comment by applecat** [comment]
I have the same question. For instance, I want use small watermarks (only company's sign) on previews, and big watermarks on large detail images.

Also it will be useful to have possibility to rotate watermark before merge with image.

**Comment by DarthSim** [comment]
Sorry for abandoning this issue. OSS version of imgproxy only allows you to specify a single watermark via config. imgproxy Pro allows specifying a custom watermark for every request.
