### ISSUE TITLE
Read the health URL from an environment variable, if one exists

### ISSUE THREAD

**Issue by Nadavpe** [imgproxy/imgproxy#762]
Looking at this:
https://github.com/imgproxy/imgproxy/blob/5d787f936727b16ff47938679c390dde56b4d3c2/server.go#L32
(That's the version we currently use, our calls are not compatible version 3 I'm afraid)

Having the ability to change the health URL to one's environment's standard would be of great help. Common URLs are /healthz and /api/healthz and it would be great to get imgproxy aligned with the automation's standard.

**Comment by DarthSim** [comment]
Hey @Nadavpe!
Added `IMGPROXY_HEALTH_CHECK_PATH` config to `v3.3.0`

**Comment by Nadavpe** [comment]
Thanks 🙂
