### ISSUE TITLE
Add `scale` processing options

### ISSUE THREAD

**Issue by devova** [imgproxy/imgproxy#763]
Which will be similar to `size` but it will be just proportional resize.
Examples
- `sc:0.5` downscale to half of original size
- `sc:2` upscale twice of original size

**Comment by DarthSim** [comment]
Hey @devova!
Sorry, I didn't mention it here, but I added the [zoom](https://docs.imgproxy.net/generating_the_url?id=zoom) option in `v3.2.0`
