### ISSUE TITLE
How can I create a squared image if the resized image is smaller than the requested size

### ISSUE THREAD

**Issue by shinsenter** [imgproxy/imgproxy#764]
@DarthSim 
Thank you for giving us this amazing project!

As the same of this issue title, I want to create a square image even when the original image is smaller than the requested size.

For example, I have a 300x200px animated GIF, I want to make a squared image from it, but I dont want to enlarge the GIF because the processing is slow and it produces huge GIF file. 

The expected GIF output size is 300x300px.
I have tried `/rs:fit:1000:1000:1:1/bg:ffffff`, but what I wanted is like `/rs:fit-down:1000:1000:1:1/bg:ffffff`.

How can I workaround with imgproxy v3?

**Comment by DarthSim** [comment]
Hey Shin!

I believe `.../rs:fill-down:1000:1000/...` is what you're looking for

**Comment by shinsenter** [comment]
@DarthSim 
I dont want my thumbnail to be cropped when using fill-down options.

**Comment by DarthSim** [comment]
So you want to extend the image to a square size? Currently, you can do so, but I'll think about it.

**Comment by shinsenter** [comment]
@DarthSim 
Thank you for quick responding.
Hope there will be an resize option `fit-down` in the next release.

**Comment by DarthSim** [comment]
I believe, [extend_aspect_ratio](https://docs.imgproxy.net/generating_the_url?id=extend-aspect-ratio) is what you need
