### ISSUE TITLE
Strip all metadata besides copyright data

### ISSUE THREAD

**Issue by schonert** [imgproxy/imgproxy#771]
We currently only support stripping all the metadata. This is usually what we want when optimising for performance. 

In general i feel we should avoid removing creator specific items from the metadata since that means we encourage stripping away prof of ownership.

This is not purely an ethical thing but i know Google uses it when indexing images. 
https://developers.google.com/search/docs/advanced/appearance/image-rights-metadata

Cloudflare is pushing in a similar direction - keeping copyright as a default. Scroll down to metadata https://developers.cloudflare.com/images/image-resizing/url-format

Changing this would be a change in default behaviour so I'd suggest opting in for now. 

Deprecating `strip_metadata=1|0` in favour of a `metadata=none|copyright|keep` seems like a good long term direction. There might be a more straightforward middleground for now tho. 

Initial keys to keep (from Google):
- [IPTC Creator](https://iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#creator)
- [IPTC Credit line](https://iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#credit-line)
- [IPTC Copyright Notice](https://iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#copyright-notice)

**Comment by DarthSim** [comment]
Hey Stefan!

I agree that keeping the copyright info is a good intention. Yet I'm afraid that implementing IPTC builder may not be an easy task. For the start, I'd offer to keep the whole IPTC meta without modification. It's not the best solution in terms of the file size yet it's a good starting point.

**Comment by DarthSim** [comment]
Released `v3.5.0`. Now imgproxy keeps copyrights in EXIF, IPTC and XMP unless `IMGPROXY_KEEP_COPYRIGHT` is `false`.

**Comment by schonert** [comment]
Brilliant @DarthSim - thanks for considering and implementing this 🙏🏻 appreciated!
