### ISSUE TITLE
Automatic webp seems to be only working on Firefox 

### ISSUE THREAD

**Issue by StitiFatah** [imgproxy/imgproxy#775]
Hi, 

I'm using the v3 docker image of imgproxy, my env variables contains : 

```
IMGPROXY_KEY=random_hex_key
IMGPROXY_SALT=random_hex_salt
IMGPROXY_ENABLE_WEBP_DETECTION=true
```

while requesting an image url I can see that it's taken in annouct since the server logs print : 

```
2022-01-17T17:49:31.061158684Z INFO [2022-01-17T17:49:31Z] Completed in 557.838668ms /jwGMiq27m3XBPsAtd_5VAv7Em-KdJvcDGhtclOYpEMo/rs:fill:0:0:false/g:ce:0:0/aHR0cHM6Ly9jZG4u/d2FsbHBhcGVyc2Fm/YXJpLmNvbS80Mi80/OS93V2JqNnQuanBn request_id=Lv_5EiuvQiimjpJg4ZNwj method=GET status=200 client_ip=81.64.71.120 image_url="https://cdn.wallpapersafari.com/42/49/wWbj6t.jpg" processing_options="ResizingType: fill; Format: webp; PreferWebP: true"
```

however while taking a look at the image propreties via this chrome extension https://chrome.google.com/webstore/detail/view-image-info-propertie/jldjjifbpipdmligefcogandjojpdagn?hl=fr or by downloading the image and doing `magick identify image.extension` I don't see it being webp but it retains the original image format. 

Here is an example image : https://imgproxy.caprover.archeroe.xyz/jwGMiq27m3XBPsAtd_5VAv7Em-KdJvcDGhtclOYpEMo/rs:fill:0:0:false/g:ce:0:0/aHR0cHM6Ly9jZG4u/d2FsbHBhcGVyc2Fm/YXJpLmNvbS80Mi80/OS93V2JqNnQuanBn 

On Archlinux I've tested with : Google Chrome Chromium and Brave, same output. It's only working on Firefox . 
On ChromeOs I've tested with Google Chrome, same output. 
On Android I've tested with Brave, same output. 

Thanks in advance.

**Comment by DarthSim** [comment]
Hey @StitiFatah!

It looks like Chrome sends an additional request without an `Accept` header when you try to save a WebP image. The same goes for the extension you've mentioned.

**Comment by StitiFatah** [comment]
@DarthSim , thanks, is there a way I could confirm the delivered image is really in webp tho ?

**Comment by DarthSim** [comment]
Since you are sure it works fine in Firefox, you can compare the response sizes or the `content-length` headers in FF and Chrome.

**Comment by StitiFatah** [comment]
Content-length matches and the content-type header says image/webp on Chromium too, thanks !
