### ISSUE TITLE
Limiting the amount of redirect follows

### ISSUE THREAD

**Issue by toonvd** [imgproxy/imgproxy#786]
Hi

A client that had multiple bad URLs (infinite loop) causing imgproxy to become very slow.
When this error happens a lot we are starting to see request timeouts and response times of 11 seconds.
This was the final result of 1 such requests: `stopped after 10 redirects`.

I believe we can prevent slowdowns / max connection being hit by setting a max amount of redirects (or a no-follow entirely).
I haven't found such option in the docs. Is it possible to implement this?

**Comment by DarthSim** [comment]
Hey Toon!
Added `IMGPROXY_MAX_REDIRECTS` to the latest build

**Comment by toonvd** [comment]
Hi DarthSim

Awesome! Thanks a lot for the fast implementation! I have rolled out the latest release on our staging environments and customers are testing.
So far so good! I will close this already.
