### ISSUE TITLE
v3.2.2-amd64 performance degradation

### ISSUE THREAD

**Issue by dstthbe** [imgproxy/imgproxy#792]
Hello,

we were experiencing a significant performance degradation with imgproxy Docker version v3.2.2-amd64 (compared to v3.2.1).

The following test setup and results for both versions.

AWS ECS cluster with 10 Fargate tasks with 512 vCpu and 1024 Memory (lab environment, no other pressure)
Two connected Docker images per task
    - nginx (entry; as a proxy without caching imgproxy responses)
    - imgproxy
Served via AWS Elastic Load Balancer

3 tests per Docker image version

each test
- running image transformation of a 1 MB jpg file to rs:fill:300:300
- 7 concurrent requests
- 5000 calls overall

_v3.2.2-amd64 stats (per minute)_
ECS CPUUtilization average 40 to 45 %
ECS CPUUtilization maximum 55 to 60 %

ELB TargetResponseTime average 180 to 210 ms
ELB TargetResponseTime Percentile99 460 to 520 ms

_v3.2.1 stats (per minute)_
ECS CPUUtilization average 25 to 30 %
ECS CPUUtilization maximum 45 to 50 %

ELB TargetResponseTime average 110 to 130 ms
ELB TargetResponseTime Percentile99 290 to 360 ms

Currently we are trying to find the reason what changes could have caused this.

--

Just to mention: other than the above issue/glitch, we are still quite impressed with imgproxy. It's working very stable and reliably within our image-pipeline servicing images for a major Austrian media company with more than 40 million visits per month.

Kind regards.

**Comment by DarthSim** [comment]
Hi @dstthbe!
I noticed the problem today too. The problem is caused by the new base image. I'll fix `v3.2.2` and `latest` till the end of the day.

**Comment by dstthbe** [comment]
That's great to hear, @DarthSim! Thank you very much!

**Comment by DarthSim** [comment]
Fixed. Sorry for this.
