### ISSUE TITLE
Validate file size before downloading it

### ISSUE THREAD

**Issue by artyom-p** [imgproxy/imgproxy#799]
Hi,

Is there a way to tell imgproxy to not download images with content-length > x ?

We are facing some issues with that, because we cant control the content that we fetch, sometimes accidentially someone puts huge (90 mb+) files to the origin. When multiple requests are requesting those files, seems like imgproxy loads those in memory and then compares the size with maxSrcFileSize option.  That causes imgproxy restarts because of OOM errors. 

Is it possible to check Content-Lenght header before actually downloading the image?

**Comment by DarthSim** [comment]
Hey @artyom-p!

imgproxy checks `Content-Length` before downloading - https://github.com/imgproxy/imgproxy/blob/master/imagedata/read.go#L43-L45. Yet some sources may not set it properly. Which source do you use (http, s3, GCS, etc)?

**Comment by artyom-p** [comment]
Oh, ok that's good.

We use HTTP source in that case.
Hm, ill try to collect more info on that issue, please don't close the ticket for now.

**Comment by DarthSim** [comment]
Sure. Also, in case `Content-Length` wasn't set properly, imgproxy stops downloading the file if the file size limit is reached.
