### ISSUE TITLE
Where does zoom fit in the processing pipeline?

### ISSUE THREAD

**Issue by nmilev-scribe** [imgproxy/imgproxy#803]
This is a question / suggestion for change of a documentation file.

In [about_processing_pipeline.md](https://github.com/imgproxy/imgproxy/blob/master/docs/about_processing_pipeline.md), there is the order in which the operations are performed (if specified). Can you specify where in this pipeline the [zoom](https://docs.imgproxy.net/generating_the_url?id=zoom) processing option is being handled (if specified, of course)?

**Comment by DarthSim** [comment]
Hey @nmilev-cursive!
The `zoom` option only affects the scaling factor, so it can be said that it's handled in the resizing phase.

**Comment by nmilev-scribe** [comment]
Thanks!
