### ISSUE TITLE
How to handle "slash" in base64 encoded Source URL?

### ISSUE THREAD

**Issue by danielgrabowski** [imgproxy/imgproxy#804]
As I can see in docs, I can add slashes in base64 encoded URLs and they are (as far as I understand it) ignored. The problem is that "/" is a valid base64 character and it appears in encoded string if the original contains "?" on certain (divisable by 3) position.
I have some source URL's containing query strings so more less 1/3 of them encodes to base64 string with "/" in it. But such string passed to imgproxy as source produces en error "net/url: invalid control character in URL".

Here's a quick example:

source image url: 
https://www.nasa.gov/sites/default/files/styles/card_page_banner/public/galleries-banner.jpg

encoded: 
aHR0cHM6Ly93d3cubmFzYS5nb3Yvc2l0ZXMvZGVmYXVsdC9maWxlcy9zdHlsZXMvY2FyZF9wYWdlX2Jhbm5lci9wdWJsaWMvZ2FsbGVyaWVzLWJhbm5lci5qcGc=

test url (based on imgproxy Getting started howto):
http://localhost:8080/insecure/rs:fill:300:400/g:sm/aHR0cHM6Ly93d3cubmFzYS5nb3Yvc2l0ZXMvZGVmYXVsdC9maWxlcy9zdHlsZXMvY2FyZF9wYWdlX2Jhbm5lci9wdWJsaWMvZ2FsbGVyaWVzLWJhbm5lci5qcGc=.jpg

it works fine.

And now we add some query string...
source image url:
https://www.nasa.gov/sites/default/files/styles/card_page_banner/public/galleries-banner.jpg?foo=bar

encoded:
aHR0cHM6Ly93d3cubmFzYS5nb3Yvc2l0ZXMvZGVmYXVsdC9maWxlcy9zdHlsZXMvY2FyZF9wYWdlX2Jhbm5lci9wdWJsaWMvZ2FsbGVyaWVzLWJhbm5lci5qcGc/Zm9vPWJhcg==

test url:
http://localhost:8080/insecure/rs:fill:300:400/g:sm/aHR0cHM6Ly93d3cubmFzYS5nb3Yvc2l0ZXMvZGVmYXVsdC9maWxlcy9zdHlsZXMvY2FyZF9wYWdlX2Jhbm5lci9wdWJsaWMvZ2FsbGVyaWVzLWJhbm5lci5qcGc/Zm9vPWJhcg==.jpg

And the result is "Invalid URL".

Is there any way I can handle this situation properly? I receive the sources already encoded so I can't just change them.

**Comment by DarthSim** [comment]
Hey @danielgrabowski!

> The source URL can be encoded with URL-safe Base64

[URL-safe](https://en.wikipedia.org/wiki/Base64#The_URL_applications) basically means that `/` and `+` should be replaced with `_` and `-`. You can also strip trailing `=`'s.

**Comment by danielgrabowski** [comment]
OK, I've missed that. Thanks.
