### ISSUE TITLE
What cache proxy do you recommend using with imgproxy?

### ISSUE THREAD

**Issue by timojokinen** [imgproxy/imgproxy#814]
I'm trying to set up imgproxy behind a cache proxy for my project. 
Using a CDN is not really an option for my project since it's very regional (only switzerland) and most CDN providers really only have 1 server here.

I'm really inexperienced in this area, I did some research on nginx and varnish but can't really decide which one to use. Can anyone using these technologies share their experiences with me? Can you recommend one of them over the other?

As far as my understanding goes nginx does not support purging without paying for nginx plus. Varnish on the other hand seems to be less suitable for static content. Any help is appreciated.

**Comment by DarthSim** [comment]
We used CloudFront and Fastly on our projects. If your project is very regional, CF won't do recurrent requests from different edge servers and this is, actually, good for you.

I don't have much experience with self-hosted cache servers, but from what I heard, Varnish is the strongest guy in the yard.

**Comment by DarthSim** [comment]
CloudFront is a black box 🤷‍♂️ Though its documentation explains how it works, we don't know all the details. So if I could try something that doesn't require much effort, I'd give it a shot.

**Comment by andreas-venturini** [comment]
Ok, you convinced me, I'll bump the min TTL!

Anyways, thanks, imgproxy is awesome! :slightly_smiling_face:
