### ISSUE TITLE
s3 http-status 404 leads to imgproxy http-status 500

### ISSUE THREAD

**Issue by antimonad** [imgproxy/imgproxy#822]
Given an correctly formulated and signed transformation url with a reference to a s3 original, 
improxy responses with http-status 500 in cases when the s3 request to the original responses with 404.
We already ruled out misconfiguration in s3, auth issues (403 instead 404 when s3-list permissions are missing) and "url" issues between imgproxy and s3 and can't find a way to achieve the 

expected behaviour:
missing originals file in s3 leads to http-status 404 instead of http-status 500 responses by imgproxy.

The error error logged:

Can't download source image: Get "s3://yxzyxzyx/folderfolder/folderfolder/filenamefilename.jpg": NoSuchKey: The specified key does not exist.
status code: 404, request id: NQVE08RK......, host id: ......

The status logged by imgproxy:
status	500

Any hints regarding ways to pinpoint the root-cause?

**Comment by DarthSim** [comment]
Ugh, s3 client is killing me... Fixed in v3.3.3

**Comment by antimonad** [comment]
That's good news anyways ;) we will "apply" the update and come back with result. Thanks!

**Comment by antimonad** [comment]
After the update to v3.3.3, files not found in s3 result in http-404 as expected.
Thanks for the prompt update! Cheers

**Comment by DarthSim** [comment]
I guess we can close the issue then :)
