### ISSUE TITLE
[Question] need dockerfile support

### ISSUE THREAD

**Issue by Yucangs** [imgproxy/imgproxy#827]
How to change dockerfile to support `vips_thumbnail_buffer` and `vips_pdfload_buffer` functions?  

I add two vips function to this repo:
https://www.libvips.org/API/current/libvips-resample.html#vips-thumbnail-buffer  
https://www.libvips.org/API/current/VipsForeignSave.html#vips-pdfload-buffer  
It works for my local env. but when i pack it into a docker image. It did not work. 
for example: vips_thumbnail_buffer aways return -1.

**Comment by DarthSim** [comment]
Hey @Yucangs!

Probably, libvips in your Docker image misses some dependencies required for these functions to work. For example, libvips from the imgproxy's base image is not built to support PDFs.

**Comment by Yucangs** [comment]
I need to change the base docker image compile options to support these functions.  
https://github.com/imgproxy/imgproxy-docker-base  
https://github.com/libvips/libvips
