### ISSUE TITLE
[Question] Proxy videos without processing

### ISSUE THREAD

**Issue by pjhartin** [imgproxy/imgproxy#828]
I was wondering if it was possible to proxy a video file through imgproxy without any form of processing?

I am currently using imgproxy to serve images to a web app. Our files are stored on Minio/S3 and I love that, in addition to the fantastic processing ability, it provides a method to securely expose assets from a private bucket. 
I was hoping to do the same with our video urls, but I cannot determine if this is possible.

Please also let me know if this is indeed bad practice, and if you'd advise an alternative approach for this.

Thank you!

**Comment by DarthSim** [comment]
Hey @pjhartin!

Unfortunately, this is not possible. Streaming video is a completely different process as you need to support ranged requests. On the one hand, this is pretty simple as you just need to check the signature, send a request to S3 and stream the response back to the client. On the other hand, this is absolutely out of imgproxy's scope.

I see two alternatives here:

1. AWS itself supports signed URLs. You can sign URLs to private S3 objects or you can sign CloudFront URLs. AWS signatures are time-limited and don't live long, so this may be a problem. Yet it's possible.

2. As I said earlier, simple video file streaming with a signature check is... well, simple :) Go app for this would hardly be larger than 1k lines.

**Comment by pjhartin** [comment]
Thanks @DarthSim for the in-depth response! I'll get studying the alternatives you suggested and hopefully wrap my head around it! Cheers 🙂
