### ISSUE TITLE
IMGPROXY_MAX_SRC_FILE_SIZE affects video?

### ISSUE THREAD

**Issue by bsboris** [imgproxy/imgproxy#831]
Hi!

I've noticed that setting `IMGPROXY_MAX_SRC_FILE_SIZE` option also affects video thumbnails generation (so, previews from videos larger than specified size wouldn't be generated). Is this inteded behavior? I was under  the expression that only small fraction of video file downloaded by Imgproxy to create thumbnail. Isn't is so?

**Comment by DarthSim** [comment]
Hey Eugene!
Unfortunately, currently, it is. We check `Content-Length` before downloading anything. I'm going to add an additional check for the `Content-Type` so imgproxy won't check `Content-Length` for `video/*` MIMEs.

**Comment by DarthSim** [comment]
Changed the behavior in the `latest` build. I'm going to make a release soon.
