### ISSUE TITLE
Issue processing Japanese fonts

### ISSUE THREAD

**Issue by Priemerk** [imgproxy/imgproxy#839]
Hi - we processing PDF slide presentations and our users often notice that Japanese characters are getting processed with lines through them.

Sample - https://speakerdeck.com/yattom/tesutofalsesuraido-nei-rong-nasi
Slide 1 - font processed with lines in it
Slide 2 - how it should look (jpg screenshot of actual letters)

Google Doc the user created - https://docs.google.com/presentation/d/1wTAbPqxkRR192ZUmcmPrssGCDq1i7mXBnuKadHdntpk/edit#slide=id.p

Users have often noted they created the presentation in Google Slides and exported the PDF, then uploaded to our site, where we process them.  

Any ideas on how this can be fixed?  Additional examples are available if needed.

**Comment by DarthSim** [comment]
Hi @Priemerk!
I saved the Google Doc you sent as a PDF and processed it with imgproxy v3.3.3, no issues were noted. Is there a chance you're using an old version of imgproxy?
