### ISSUE TITLE
illegal instruction | non zero exit 132

### ISSUE THREAD

**Issue by K4CZP3R** [imgproxy/imgproxy#856]
I'm trying to run imgproxy on my Raspberry Pi 4, but with no luck. When using premade docker image, container crashes with 132 error code. And when I'm compiling it by myself i'm getting:
```
...
github.com/imgproxy/imgproxy/v3/vips
# pkg-config --cflags  -- vips
pkg-config: signal: illegal instruction (core dumped)
github.com/imgproxy/imgproxy/v3/metrics/newrelic
github.com/imgproxy/imgproxy/v3/metrics
github.com/imgproxy/imgproxy/v3/router
The command '/bin/sh -c docker/go.sh build -v -o /usr/local/bin/imgproxy' returned a non-zero code: 2
```

**Comment by DarthSim** [comment]
Hey @K4CZP3R!

It looks like Pi's CPU doesn't support optimizations imgproxy's dependencies are built with. Which is actually doesn't surprise me as ARM builds of imgproxy are made mostly for Amazon Graviton and Apple Silicon. Unfortunately, I don't see any way to make it work except of building both [the base image](https://github.com/imgproxy/imgproxy-docker-base) and the main image on Pi. But this will take A LOT of time.

**Comment by Sumis34** [comment]
Hello :)

Do you have some sort of tutorial or reference link that explains the entire process?  other than the already provided one?

**Comment by saendu** [comment]
any progress on this front? having issues to let this run on my k3s rasperry pi cluster with ARM chips.

**Comment by DarthSim** [comment]
@saendu Sorry, there won't be any progress on this front from our side. imgproxy and its deps are built with the `-march=armv8.2-a+fp16` C flag. This is a good compromise between wide CPU support and good optimization. Raspberry Pi is not so popular for imgproxy, so we'd rather provide better performance on popular CPUs like Apple Silicon and Amazon Graviton.

There are two ways to make a custom build for your Pi:

1. Build a custom base image with [this line](https://github.com/imgproxy/imgproxy-docker-base/blob/master/build-bash-profile.sh#L31) changed and then build imgproxy's image on top of it.
2. Build imgproxy from source using libvips provided by your system. We generally don't recommend this, but this is an easy way.

**Comment by saendu** [comment]
> @saendu Sorry, there won't be any progress on this front from our side. imgproxy and its deps are built with the `-march=armv8.2-a+fp16` C flag. This is a good compromise between wide CPU support and good optimization. Raspberry Pi is not so popular for imgproxy, so we'd rather provide better performance on popular CPUs like Apple Silicon and Amazon Graviton.
> 
> 
> 
> There are two ways to make a custom build for your Pi:
> 
> 
> 
> 1. Build a custom base image with [this line](https://github.com/imgproxy/imgproxy-docker-base/blob/master/build-bash-profile.sh#L31) changed and then build imgproxy's image on top of it.
> 
> 2. Build imgproxy from source using libvips provided by your system. We generally don't recommend this, but this is an easy way.

Understood. Thanks for taking the time to reply and provide some workarounds! Apperciate it.
