### ISSUE TITLE
Fontconfig error: Cannot load default config file when resizing SVGs that include <text> elements

### ISSUE THREAD

**Issue by SmaugPool** [imgproxy/imgproxy#860]
Using docker image v3 (v3.5.0) on amd64:
```
$ docker images --digests
REPOSITORY          TAG       DIGEST                                                                    IMAGE ID       CREATED      SIZE
darthsim/imgproxy   v3        sha256:d447291d7a679e0fbf2d503ba3a19921445f1b7fbe42b4ce8cc85f625c62ae77   808ea1ce7858   3 days ago   145MB
```

When resizing an SVG file that includes some `text` elements, the process fails with the following error:

```
Fontconfig error: Cannot load default config file: No such file: (null)

(process:1): Pango-CRITICAL **: 21:43:01.939: pango_font_describe: assertion 'font != NULL' failed

(process:1): Pango-CRITICAL **: 21:43:01.939: pango_font_description_get_variant: assertion 'desc != NULL' failed

(process:1): Pango-CRITICAL **: 21:43:01.939: pango_font_get_hb_font: assertion 'PANGO_IS_FONT (font)' failed
```

It seems that fonts are not configured correctly in the docker image to allow SVG text rendering.

**Comment by SmaugPool** [comment]
It's similar to https://github.com/imgproxy/imgproxy/issues/157 but now it seems that SVGs with text are not processed at all instead of characters being replaced by squares like in older versions.

**Comment by DarthSim** [comment]
Hey @SmaugPool! I updated Pango and friends in `v3.5.1` and it seems like this fixed the issue with failures. However, yes, it doesn't render text with unknown fonts now :( As I said in #157, custom fonts in SVGs are not a quite popular thing, so I'd rather not add another 40MB to the Docker image. However, it's always possible to build an image on top of the official one and include needed fonts.

**Comment by SmaugPool** [comment]
Yes, it's fine. I can add the fonts I need myself.

Thank you and well done for this awesome software🙏
