### ISSUE TITLE
Optionally provide Blurhash string

### ISSUE THREAD

**Issue by a0v0** [imgproxy/imgproxy#880]
https://github.com/bbrks/go-blurhash

**Comment by schonert** [comment]
Brilliant idea! We currently have a different process where we extract colors and use them as placeholders - this would be next level.
Having imgproxy serve a string and not an actual image seems a bit off tho. 
I'd suggest either adding the blurhash to the metadata under the **/info/** path or converting the blurhash into a small svg/img.

**Comment by a0v0** [comment]
Can't blurhash feature be brought down to oss edition?

**Comment by DarthSim** [comment]
Since `v3.20.0`, imgproxy Pro can return a BlurHash string as a part of the `/info` response: https://docs.imgproxy.net/getting_the_image_info?id=blurhash

> Can't blurhash feature be brought down to oss edition?

Sorry, but this sounds like "Could you do some work for free so I shouldn't pay for the rest of your work?" 😉
