### ISSUE TITLE
Website shows infinite spinner

### ISSUE THREAD

**Issue by TrySound** [imgproxy/imgproxy#881]
https://docs.imgproxy.net/#/generating_the_url_advanced

<img width="880" alt="image" src="https://user-images.githubusercontent.com/5635476/170677516-2fcd9f0c-fabb-4568-906c-91d7fa7270b0.png">

**Comment by DarthSim** [comment]
Hey!
This is a pretty old URL that is not valid anymore. Here's the new one: https://docs.imgproxy.net/generating_the_url

**Comment by TrySound** [comment]
Thanks! Found it in our internal docs.
