### ISSUE TITLE
DecodeTiffMeta err

### ISSUE THREAD

**Issue by crystal-lee** [imgproxy/imgproxy#885]
I use imgproxy to handle a NEF pic. 
It decode use tiff.go, the size is 160x120
```
tiff -> DecodeTiffMeta:  160 0
tiff -> DecodeTiffMeta:  160 120
```
but the pic size is 7380 × 4928

the pic is https://bos-media.sxtvs.com.cn/smc-test/75c046979256455eaef05eb9bbf3204b.NEF
the test param is /resizing_type:fit/enlarge:0/width:500/watermark:0.0/gravity:sm/

**Comment by DarthSim** [comment]
Hey @crystal-lee!

imgproxy doesn't support NEF format. However, it is based on the TIFF format. [Specification](http://lclevy.free.fr/nef/) says that NEF stores a 160x120 thumbnail as the main image, so imgproxy sees NEF files as 160x120 TIFF images.

**Comment by crystal-lee** [comment]
thanks, i get it. and i use magick to handle it.
