### ISSUE TITLE
unsupported BMP image 

### ISSUE THREAD

**Issue by vtsztr** [imgproxy/imgproxy#901]
Hi,

I installed imgproxy via brew, but I have the same issue running the docker from the master branch. I attached the used BMP as a zip, and below there's the error that I got:

ERROR   [2022-06-20T16:59:03+01:00] Completed in 19.367706ms /resize:fit:240:180:0/gravity:ce/plain/local:///test_image.bmp  request_id=pEel3vVAps0T7gqrr8uKj method=GET status=500 client_ip="::1" error="unsupported BMP image"
github.com/imgproxy/imgproxy/v3/ierrors/errors.go:35 github.com/imgproxy/imgproxy/v3/ierrors.New
github.com/imgproxy/imgproxy/v3/server.go:103 main.withCORS.func1
github.com/imgproxy/imgproxy/v3/server.go:150 main.withPanicHandler.func1
github.com/imgproxy/imgproxy/v3/router/router.go:102 github.com/imgproxy/imgproxy/v3/router.(*Router).ServeHTTP
net/http/server.go:2917 net/http.serverHandler.ServeHTTP
net/http/server.go:1967 net/http.(*conn).serve
runtime/asm_amd64.s:1572 runtime.goexit

[test_image.bmp.zip](https://github.com/imgproxy/imgproxy/files/8946850/test_image.bmp.zip)

**Comment by DarthSim** [comment]
Hey @vtsztr!
Thanks for catching this! Fixed in v3.7.0
