### ISSUE TITLE
CDN Cache Issues -> MISS everytime

### ISSUE THREAD

**Issue by levydanqc** [imgproxy/imgproxy#916]
I deployed imgproxy on heroku and everything works great.

When loading the image url in a tab, the cache header `cf-cache-status` is **HIT**, but when loading the image inside my web app (with rails gem) it is always **MISS**.

Why isn't CloudFare caching the image please ?

**Comment by DarthSim** [comment]
Hi @levydanqc!

By "web app" you mean an HTML page with an `<img/>` tag, right? If you open the image from this `img` tag in the new tab, does it still misses the cache?
