### ISSUE TITLE
Facebook/OpenGraph and Twitter not rendering cards with imgproxy images

### ISSUE THREAD

**Issue by jdpedrie** [imgproxy/imgproxy#927]
Tested on v3.5.0 and v3.6.0.

It seems that recently, opengraph (seemingly only in the context of Facebook) or twitter cards have ceased to render images when the image source is an imgproxy URL.

We've discovered a couple other sites also using imgproxy and noticed that the issue appears to not be isolated to us.

When testing with the [Twitter Validator](https://cards-dev.twitter.com/validator), we've noticed that the fetch operation returns a 403 from the twitter service, but no further detail.

We have verified that imgproxy is responding with the correct data to requests, including requests from facebook and twitterbot (by checking network logs).

Finally, we tested `IMGPROXY_ENFORCE_WEBP=false`, with no improvement.

**Comment by DarthSim** [comment]
Hi John,

This doesn't seem to be related to imgproxy. I've tested Twitter's and Facebook's card validators, and both of them don't show cards properly even if the tested page doesn't use imgproxy. They don't work properly even with my GitHub page. However, when I try to post a URL of a page that uses imgproxy, Facebook generates a card for it without a problem. And for Twitter, there's a pretty old discussion about not working cards: https://twittercommunity.com/t/summary-card-with-large-image-fails-despite-adhering-to-specs/162662
