### ISSUE TITLE
Extract vibrant/dominant colors from source

### ISSUE THREAD

**Issue by schonert** [imgproxy/imgproxy#941]
Would we be able to extract colors from an image and add it to the values exposed through `/info`?

There's a Go package, quite dated, that does exactly what I had in mind (https://github.com/dayvonjersen/vibrant). 
It looks like the package downloads the entire image to be able to extract the colors - in that case, I could imagine it impacting the performance?

We currently use a package similar to the one above that uses ImageMagic behind the scene. Would be great to rid of that from our build. 
Also, we currently request a smaller resized (w:250) version of the image through Imgproxy. We found that letting Imgproxy resize the image before feeding it to ImageMagic gave us quite an improvement in performance.

I know you're working on blurhash/svg placeholders (#880) - this might fit into that palette of features?

**Comment by schonert** [comment]
Not sure how i add the `feature request` label

**Comment by DarthSim** [comment]
Hey @schonert!

It's a pretty simple and pretty complex feature at the same time. There are several `/info` fields that I want to add, but all of them require images to be fully loaded and sometimes decoded. So I need to prepare imgproxy for this first, implement some kind of info options (like processing options but for `/info`) and stuff.

**Comment by schonert** [comment]
Would love to hear what else you've got on the roadmap 🤓

Slowing down metadata would be a shame. How about specifying the fields. Eg. `iptc`, `exif`, `blurhash`, `colors`, `svg`

`/info` -> file info (width, height, etc)
`/info:iptc` -> only IPTC
`/info:blurhash:colors` -> only blurhash and colors

This way we could avoid heavy fields if not needed. This will not be as backwards compatible tho. 

We could also add an `/inspect` endpoint that requires specifying fields. 

Blurhash, svg and colors could also live under a different endpoint. This would allow them to be used directly in the client. Eg. `https://example.com/preview:svg/w:350.........`
Where everything after the preview will transform the source. And the transformed source will be wrapped in the svg skeleton.

**Comment by DarthSim** [comment]
It's going to be more like processing options: `/info/signature/blurhash:1/dominant_colors:1/palette:256/detect:person:dog:cat/...`, etc. By default, it'll return what it currently returns.

**Comment by schonert** [comment]
Exciting! Any rough estimates on any of this? 🤓

**Comment by DarthSim** [comment]
No estimations for now, but I'll move it up.

Please don't close feature requests 'till they are implemented :)

**Comment by schonert** [comment]
Sure! I closed because the request  seemed to already be in the pipeline 👍🏻

**Comment by artyom-p** [comment]
Any updates on this?

**Comment by DarthSim** [comment]
Here it is https://docs.imgproxy.net/getting_the_image_info?id=dominant-colors ☺️
